(()=>{
if(!/\/grow\/?$/.test(location.pathname))return;
const PREFIX='warera_grow_v1_',DB='warera-grow',STORE='pets';
const getViewer=()=>{try{return localStorage.getItem('warera_chat_perspective')==='も'?'も':'み'}catch(e){return'み'}};
const getKey=()=>{const v=getViewer(),t=v==='み'?'も':'み';return`${PREFIX}${v}_${t}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(getKey())||'null')}catch(e){return null}};
const writeLocal=s=>{try{localStorage.setItem(getKey(),JSON.stringify(s))}catch(e){}};
function putDb(s){return new Promise(resolve=>{try{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};r.onerror=()=>resolve();r.onsuccess=()=>{const db=r.result;try{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(s);q.onsuccess=q.onerror=()=>{db.close();resolve()}}catch(e){db.close();resolve()}}}catch(e){resolve()}})}
const traitMeta={affection:['💗','甘やかされ気味'],playful:['🎮','ちょっかい慣れ'],food:['🍙','ごはん好き'],routine:['🛏️','よく寝かされる'],weird:['🌀','われわれ語多め'],independent:['🌱','ひとりでも平気'],night:['🌙','夜ふかし育ち']};
const needMeta={
 hunger:{icon:'🍚',label:'おなかすき',care:'ごはん',low:'満足',mid:'ちょっと',high:'ぺこぺこ'},
 sleep:{icon:'💤',label:'ねむさ',care:'ねかせる',low:'元気',mid:'ちょいねむ',high:'ねむい'},
 mood:{icon:'🎲',label:'あそびたい',care:'あそぶ',low:'満足',mid:'ちょっと',high:'たいくつ'},
 bond:{icon:'💗',label:'かまって',care:'なでる・ぎゅ',low:'満足',mid:'ちょっと',high:'かまって'},
 clean:{icon:'🫧',label:'よごれ',care:'おふろ',low:'きれい',mid:'ちょっと',high:'おふろ'}
};
const buttonNames={feed:'ごはんをあげる',snack:'おやつをあげる',sleep:'ねかせる',wash:'おふろに入れる',play:'あそぶ',pat:'なでる',hug:'ぎゅする',chat:'しゃべる',teach:'ことばを教える',check:'ようすを見る',log:'われわれログを見せる'};
function css(){if(document.getElementById('growUxV6Style'))return;const s=document.createElement('style');s.id='growUxV6Style';s.textContent=`#speechNote{display:none!important}.mini-panel:has(#history){display:none!important}.needs>.need:not(.ux-need){visibility:hidden!important}.need.ux-need{padding:7px!important;border:1px solid #ddd;border-radius:8px;background:#fafafa}.need-state{display:block;margin-top:4px;color:#666;font-size:8px;font-weight:700;line-height:1.2}.need-care{display:block;margin-top:2px;color:#888;font-size:7px;line-height:1.25}.needs-help{margin:0 0 9px;color:#777;font-size:8px;line-height:1.45}.trait-summary{margin:0 0 10px;padding:8px 9px;border-left:3px solid #111;background:#f7f7f7;font-size:10px;font-weight:700;line-height:1.55}.teach-help{margin:3px 0 8px;color:#777;font-size:8px;line-height:1.45}@media(max-width:580px){.needs{grid-template-columns:repeat(3,minmax(0,1fr))!important}.need-head{font-size:8px!important}}`;document.head.append(s)}
function needView(s){if(!s?.needs)return null;const out={};for(const k of Object.keys(needMeta))out[k]=Math.max(0,Math.min(100,100-Number(s.needs[k]??80)));return out}
function ensureNeedHelp(){const n=document.getElementById('needs');if(!n)return null;let p=document.getElementById('needsHelpV6');if(!p){p=document.createElement('p');p.id='needsHelpV6';p.className='needs-help';n.insertAdjacentElement('afterend',p)}return p}
function stateWord(meta,v){return v>=76?meta.high:v>=42?meta.mid:meta.low}
function renderNeeds(){const n=document.getElementById('needs'),s=read(),stage=document.getElementById('stageLabel')?.textContent?.trim();if(!n||!s)return;if(stage==='たまご'){n.style.display='none';const h=ensureNeedHelp();if(h)h.textContent='孵化すると、おなか・ねむさ・あそびたい・かまって・よごれが出てくるよ。';return}n.style.display='grid';const v=needView(s);const sig=Object.entries(v).map(([k,x])=>`${k}:${Math.round(x)}`).join('|');if(n.dataset.uxSig===sig&&[...n.children].every(x=>x.classList.contains('ux-need')))return;n.dataset.uxSig=sig;n.replaceChildren();for(const [k,m] of Object.entries(needMeta)){const x=Math.round(v[k]),d=document.createElement('div');d.className='need ux-need';d.innerHTML=`<div class="need-head"><span>${m.icon} ${m.label}</span></div><div class="meter"><i style="width:${x}%"></i></div><small class="need-state">${stateWord(m,x)}</small><small class="need-care">${x>=52?'→ '+m.care:'まだ平気'}</small>`;n.append(d)}const h=ensureNeedHelp();if(h)h.textContent='バーが伸びるほど、そのお世話が必要。お世話すると下がって、時間がたつとまた少しずつ伸びるよ。'}
function rewriteStateLabel(){const el=document.getElementById('stateLabel'),s=read();if(!el||!s||document.getElementById('stageLabel')?.textContent.trim()==='たまご')return;const v=needView(s),[k,x]=Object.entries(v).sort((a,b)=>b[1]-a[1])[0];let text='おけけ。通常運転';if(x>=42){const mild={hunger:'🍚 おなかすいた',sleep:'💤 ねむそう',mood:'🎲 あそびたそう',bond:'💗 かまってほしそう',clean:'🫧 そろそろおふろ'},hard={hunger:'🍚 かなりおなかすいた',sleep:'💤 かなりねむい',mood:'🎲 かなりあそびたい',bond:'💗 だいぶかまってほしい',clean:'🫧 だいぶよごれてる'};text=(x>=76?hard:mild)[k]}if(el.textContent!==text)el.textContent=text}
function rewriteActions(){document.querySelectorAll('#actionGrid [data-action]').forEach(b=>{const a=b.dataset.action,n=buttonNames[a];if(!n)return;const l=b.querySelector('.label');if(l&&l.textContent!==n)l.textContent=n});const h=document.getElementById('actionHint');if(h){const text=document.getElementById('stageLabel')?.textContent.trim()==='たまご'?'たまごの時だけのお世話だよ':'いまの様子で、できるお世話が少し変わるよ';if(h.textContent!==text)h.textContent=text}}
function teachHelp(){const p=document.getElementById('teachPanel');if(!p)return;const b=p.querySelector('b');if(b&&b.textContent!=='ことばを1つ教える')b.textContent='ことばを1つ教える';let h=p.querySelector('.teach-help');if(!h){h=document.createElement('p');h.className='teach-help';b?.insertAdjacentElement('afterend',h)}const text='ログに出てくることばから1つ選ぶよ。何度も教えるほど、そのことばが返事や口ぐせに出やすくなる。';if(h.textContent!==text)h.textContent=text}
function learnedWord(s){const a=Object.entries(s?.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);if(!a.length)return'';const pool=[];for(const [w,n] of a)for(let i=0;i<Math.min(4,n);i++)pool.push(w);return pool[(Number(s.totalCare||0)+pool.length)%pool.length]||a[0][0]}
async function mixLearned(action){if(action==='teach')return;await new Promise(r=>setTimeout(r,80));const s=read(),w=learnedWord(s),sp=document.getElementById('speech');if(!s||!w||!sp)return;if((Number(s.totalCare||0)+action.length)%4>1)return;const node=sp.firstChild,base=node?.nodeValue?.trim()||sp.textContent.trim();if(!base||base.includes(w))return;const text=Number(s.totalCare||0)%2?`${w}。${base}`:`${base} ${w}`;if(node)node.nodeValue=text;else sp.textContent=text;s.lastSpeech=text;writeLocal(s);await putDb(s)}
function personality(){const panels=[...document.querySelectorAll('.mini-panel')],p=panels.find(x=>x.querySelector('h2')?.textContent.trim()==='この個体のらしさ');const s=read();if(!p||!s)return;let sum=p.querySelector('.trait-summary');if(!sum){sum=document.createElement('p');sum.className='trait-summary';p.querySelector('h2')?.insertAdjacentElement('afterend',sum)}const groups=p.querySelectorAll('.trait-group');if(groups[0]?.querySelector('b'))groups[0].querySelector('b').textContent='本人のログから';if(groups[1]?.querySelector('b'))groups[1].querySelector('b').textContent='育て方で変わったところ';const innate=[...p.querySelectorAll('#innateTags .trait-tag')].map(x=>x.textContent.replace(/^\S+\s*/,'' )).slice(0,2);const ranked=Object.entries(s.traits||{}).sort((a,b)=>Number(b[1])-Number(a[1])).filter(([,v])=>Number(v)>1);const grow=ranked[0]?traitMeta[ranked[0][0]]?.[1]:'まだ育て方のクセなし';const target=getViewer()==='み'?'もっち':'みちゃこ';const text=`${target}のログでは「${innate.join('・')||'まだ不明'}」が目立つ。いまの育て方では「${grow}」がいちばん濃い。`;if(sum.textContent!==text)sum.textContent=text;const box=document.getElementById('traitTags');if(box){const wanted=ranked.length?ranked.slice(0,4).map(([k,v])=>{const m=traitMeta[k],lv=v>=14?'かなり':v>=7?'強め':'少し';return m?`${m[0]} ${m[1]}・${lv}`:''}).filter(Boolean):['まだ育て方のクセは薄い'];if([...box.children].map(x=>x.textContent).join('|')!==wanted.join('|')){box.replaceChildren();for(const label of wanted){const t=document.createElement('span');t.className='trait-tag';t.textContent=label;box.append(t)}}}const l=document.getElementById('learnedLine'),learned=Object.entries(s.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).slice(0,5);const line=learned.length?`覚えたことば：${learned.map(([w,n])=>`${w}×${n}`).join(' / ')}。返事や口ぐせに出てくるよ。`:'まだことばは覚えてない。教えたことばは、あとで返事や口ぐせに混ざるよ。';if(l&&l.textContent!==line)l.textContent=line}
function removeGrowthLog(){document.querySelectorAll('.mini-panel h2').forEach(h=>{if(h.textContent.trim()==='成長記録')h.closest('.mini-panel')?.remove()})}
function textCleanup(){document.querySelectorAll('.grow-shell *').forEach(el=>{if(el.children.length===0&&el.textContent.includes('ごあん'))el.textContent=el.textContent.replaceAll('ごあん','ごはん')})}
let busy=false;function tidy(){if(busy)return;busy=true;try{css();removeGrowthLog();renderNeeds();rewriteStateLabel();rewriteActions();teachHelp();personality();textCleanup()}finally{busy=false}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tidy,{once:true});else tidy();
new MutationObserver(()=>tidy()).observe(document.documentElement,{childList:true,subtree:true,characterData:true});
document.addEventListener('click',e=>{const b=e.target.closest('#actionGrid [data-action]');if(b)mixLearned(b.dataset.action)},true);
setInterval(tidy,1500);
})();