(()=>{
if(!/\/grow\/?$/.test(location.pathname))return;
const P='warera_grow_v1_',DB='warera-grow',STORE='pets',N={み:'みちゃこ',も:'もっち'};
const TRAITS=['affection','playful','food','routine','weird','independent','night'];
const TM={affection:'甘やかされ育ち',playful:'あそび好き',food:'ごはん好き',routine:'生活しっかり',weird:'われわれ語多め',independent:'ひとりでも平気',night:'夜ふかし育ち'};
const WORDS=['われわれ','しょもしょも','おけけ','オフトゥン','てぇてぇ','はすはす','ガラスープ','かわいい','好き','ねむい','だん！','カラダ・アラウ','おはよ','おやすみ','ごはん','ほんと','なるほど','待って','やだ','ありがとう','ごめん','ちっち','ぱっちくん','もっかい','えらい','むり','まだねない','すや…','いいよ','なに','はい'];
const CSS=`
#g10{max-width:1220px;margin:auto;color:#111}.g10w{overflow:hidden;border:1px solid #111;border-radius:12px;background:#f4f4f4;box-shadow:4px 4px 0 rgba(0,0,0,.4)}
.g10top{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 14px;border-bottom:1px solid #111;background:#fff}.g10id{display:flex;align-items:center;gap:10px}.g10logo{display:grid;place-items:center;width:44px;height:44px;border:1px solid #111;border-radius:50%;background:#f1f1f1;font-size:22px}.g10title b{font-size:18px;font-weight:800}.g10title span{display:block;margin-top:2px;color:#666;font-size:10px}.g10meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:flex-end}.g10chip,.g10share{height:34px;padding:0 10px;border:1px solid #111;border-radius:9px;background:#fff;color:#111;font:700 10px 'Noto Sans JP',sans-serif;box-shadow:2px 2px 0 rgba(0,0,0,.25)}
.g10body{padding:12px}.g10grid{display:grid;grid-template-columns:minmax(0,2.65fr) minmax(260px,.72fr);gap:12px;align-items:start}.g10card,.g10room,.g10dock{border:1px solid #111;border-radius:10px;background:#fff;box-shadow:3px 3px 0 rgba(0,0,0,.24)}.g10left,.g10right{min-width:0}.g10card{padding:14px}.g10name{display:flex;justify-content:space-between;align-items:center;gap:10px}.g10name strong{font-size:22px}.g10stage{padding:4px 7px;border:1px solid #111;border-radius:999px;font-size:9px;font-weight:800;background:#fff}
.g10room{position:relative;min-height:390px;margin:10px 0 12px;overflow:hidden;background:linear-gradient(#fff0f4 0 53%,#f2d1b2 53%);box-shadow:none}.g10room[data-t="も"]{background:linear-gradient(#eef7ff 0 53%,#f2d1b2 53%)}.g10room.night{background:linear-gradient(#d8dbea 0 53%,#c8aa8b 53%)}.g10room:before{content:'';position:absolute;left:7%;top:10%;width:35%;height:31%;border:5px solid #9b7a64;border-radius:5px;background:#9bd8ff}.g10room.night:before{background:#4e628d}.g10room:after{content:'';position:absolute;left:25%;right:18%;bottom:6%;height:18%;border-radius:50%;background:repeating-linear-gradient(45deg,#f8e3e6 0 18px,#efcfd5 18px 36px)}.g10bed{position:absolute;left:5%;bottom:12%;width:30%;height:16%;border:1px solid #111;border-radius:45% 45% 18% 18%;background:#f7bdc9}.g10shelf{position:absolute;right:5%;bottom:16%;width:20%;height:31%;border:4px solid #9b6a4b;background:#d5a27d}.g10note{position:absolute;right:3%;top:4%;z-index:5;max-width:220px;padding:8px 10px;border:1px solid #111;border-radius:7px;background:#fff;box-shadow:2px 2px 0 rgba(0,0,0,.2);font-size:10px;font-weight:800;line-height:1.45}.g10speech{position:absolute;left:50%;bottom:61%;z-index:8;max-width:300px;transform:translateX(-50%);padding:8px 11px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:2px 2px 0 rgba(0,0,0,.2);font-size:11px;font-weight:800;text-align:center}.g10petbox{position:absolute;left:50%;bottom:10%;z-index:6;transform:translateX(-50%) scale(1.16)}
.g10pet{--p:#ffe6a6;--d:#111;position:relative;width:150px;height:170px}.g10pet[data-t="み"]{--p:#ffdce8}.g10bodyp{position:absolute;left:50%;bottom:12px;width:136px;height:128px;transform:translateX(-50%);border:3px solid var(--d);border-radius:46%;background:var(--p)}.g10ear{position:absolute;top:17px;width:47px;height:58px;border:3px solid var(--d);background:var(--p)}.g10ear.l{left:18px;border-radius:65% 25% 20% 40%;transform:rotate(-14deg)}.g10ear.r{right:18px;border-radius:25% 65% 40% 20%;transform:rotate(14deg)}.g10eyes{position:absolute;left:50%;top:47%;z-index:3;display:flex;gap:42px;transform:translateX(-50%)}.g10eyes i{width:16px;height:21px;border-radius:45%;background:var(--d);transition:.18s}.g10mouth{position:absolute;left:50%;top:58%;z-index:3;width:25px;height:10px;transform:translateX(-50%);border-bottom:3px solid var(--d);border-radius:0 0 55% 55%}.g10pet.sleeping .g10eyes i{height:4px;margin-top:9px;border-radius:999px}.g10pet.sleeping .g10mouth{width:16px;height:4px;border-bottom-width:2px}.g10pet.egg .g10ear,.g10pet.egg .g10eyes,.g10pet.egg .g10mouth{display:none}.g10pet.egg .g10bodyp{height:158px;border-radius:50% 50% 44% 44%/58% 58% 42% 42%;background:linear-gradient(135deg,#fff,var(--p))}.g10poop{position:absolute;bottom:14%;z-index:7;font-size:24px}.p1{left:31%}.p2{right:28%}
.g10ident{padding:9px;border:1px solid #ddd;border-radius:8px;background:#fafafa;font-size:10px;font-weight:700;line-height:1.55}.g10st{display:grid;gap:9px;margin-top:12px}.g10r{display:grid;grid-template-columns:80px 1fr 72px;align-items:center;gap:8px}.g10r b{font-size:10px}.g10bar{height:12px;border:1px solid #111;border-radius:999px;background:#fff;overflow:hidden}.g10bar i{display:block;height:100%;border-radius:999px}.good i{background:#98cfa5}.mid i{background:#e5c66f}.low i{background:#e5a19a}.g10r span{color:#666;font-size:8px;font-weight:700;text-align:right}.g10growth{margin-top:12px;padding:10px;border-top:1px solid #ddd}.g10growhead{display:flex;justify-content:space-between;gap:8px;margin-bottom:6px;font-size:9px;font-weight:800}.g10growbar{height:9px;border:1px solid #111;border-radius:999px;background:#fff;overflow:hidden}.g10growbar i{display:block;height:100%;background:#111}.g10growtext{margin-top:5px;color:#666;font-size:8px}
.g10right{display:grid;gap:12px;align-content:start}.g10h{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:0 0 9px;font-size:14px}.g10h small{color:#777;font-size:8px}.g10words{display:grid;gap:9px}.g10word-group{display:grid;gap:5px}.g10word-label{display:flex;align-items:center;justify-content:space-between;gap:8px;color:#666;font-size:8px;font-weight:800}.g10word-list{display:flex;flex-wrap:wrap;gap:6px}.g10word{padding:5px 7px;border:1px solid #111;border-radius:999px;background:#fff;font-size:8px;font-weight:800}.g10word.catch{background:#111;color:#fff}.g10word.training{border-style:dashed;background:#fafafa}.g10word small{font-size:7px;color:#777}.g10word.catch small{color:#ddd}.g10explain{margin:0 0 9px;color:#666;font-size:9px;line-height:1.55}.g10add{width:100%;margin-top:8px;padding:8px;border:1px dashed #999;border-radius:8px;background:#fafafa;font:800 9px 'Noto Sans JP',sans-serif}.g10memo{display:grid;gap:7px}.g10mrow{display:flex;justify-content:space-between;gap:12px;padding-bottom:6px;border-bottom:1px solid #eee;font-size:9px}.g10mrow span{color:#666}.g10mrow b{text-align:right}.g10restart{width:100%;margin-top:10px;padding:8px;border:1px solid #111;border-radius:8px;background:#fff;font:800 9px 'Noto Sans JP',sans-serif}
.g10dock{grid-column:1/-1;padding:12px}.g10care{display:grid;grid-template-columns:repeat(6,1fr);gap:9px}.g10care button{position:relative;min-height:102px;padding:10px 6px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:2px 2px 0 rgba(0,0,0,.2);cursor:pointer}.g10care button.rec{background:#111;color:#fff}.g10care em{position:absolute;right:5px;top:5px;padding:2px 5px;border:1px solid currentColor;border-radius:999px;font:800 6px sans-serif}.g10care i{display:block;font-style:normal;font-size:29px}.g10care b{display:block;margin-top:5px;font-size:11px}.g10care small{display:block;margin-top:3px;color:#777;font-size:7px}.g10care button.rec small{color:#ddd}.g10tools{display:flex;justify-content:flex-end;gap:6px;margin-top:8px}.g10tools button{padding:5px 8px;border:1px solid #111;border-radius:7px;background:#fff;font:700 8px sans-serif}
.g10modal{position:fixed;inset:0;z-index:160;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.28)}.g10modal[hidden]{display:none}.g10dlg{width:min(100%,390px);padding:16px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:4px 4px 0 rgba(0,0,0,.35)}.g10dlg h2{margin:0 0 7px;font-size:18px}.g10dlg p{margin:0 0 12px;color:#666;font-size:10px;line-height:1.6}.g10teach-block{margin-top:10px}.g10teach-label{margin:0 0 6px;font-size:9px;font-weight:800}.g10twords{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;max-height:280px;overflow:auto}.g10twords button,.g10close,.g10danger,.g10cancel{padding:9px;border:1px solid #111;border-radius:8px;background:#fff;font-weight:800}.g10twords button.catch{background:#111;color:#fff}.g10twords button.training{border-style:dashed}.g10twords button small{display:block;margin-top:2px;color:#777;font-size:7px}.g10twords button.catch small{color:#ddd}.g10close{width:100%;margin-top:8px}.g10danger{width:100%;background:#111;color:#fff}.g10cancel{width:100%;margin-top:7px}
@media(max-width:980px){.g10grid{grid-template-columns:minmax(0,2fr) minmax(250px,.78fr)}.g10care{grid-template-columns:repeat(3,1fr)}}
@media(max-width:720px){.g10title span,.clock{display:none}.g10top{align-items:flex-start}.g10meta{max-width:52%}.g10body{padding:8px}.g10grid{display:flex;flex-direction:column}.g10left{order:1;width:100%}.g10dock{order:2;width:100%;margin-top:0}.g10right{order:3;width:100%}.g10room{min-height:335px}.g10petbox{transform:translateX(-50%) scale(.92)}.g10speech{bottom:61%;max-width:230px}.g10care{grid-template-columns:repeat(3,1fr);gap:6px}.g10care button{min-height:82px;padding:7px 4px}.g10care i{font-size:24px}.g10care b{font-size:9px}.g10care small{font-size:6.5px}.g10r{grid-template-columns:72px 1fr 58px}.g10twords{grid-template-columns:repeat(2,1fr)}}`;
let V=getV(),G=V==='み'?'も':'み',S;
function getV(){try{return localStorage.getItem('warera_chat_perspective')==='も'?'も':'み'}catch(e){return'み'}}
const K=()=>`${P}${V}_${G}`,clamp=v=>Math.max(0,Math.min(100,Number(v)||0)),now=()=>Date.now(),today=()=>new Date().toISOString().slice(0,10);
function fresh(){const t={};TRAITS.forEach(k=>t[k]=0);return{id:K(),version:10,viewer:V,target:G,born:today(),totalCare:0,growthXP:0,traits:t,needs:{hunger:84,sleep:84,mood:80,bond:76,clean:92},learned:{},poop:0,toiletMeter:0,careMistakes:0,lastSpeech:'……おけけ？',lastAction:'',lastTick:now(),sleepUntil:0,updatedAt:now()}}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
async function readDb(){try{const db=await openDb(),x=await new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(K());q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)});db.close();return x}catch(e){return null}}
function readLocal(){try{return JSON.parse(localStorage.getItem(K())||'null')}catch(e){return null}}
async function load(){const [a,b]=await Promise.all([readDb(),Promise.resolve(readLocal())]);if(a&&b)return Number(a.updatedAt||0)>=Number(b.updatedAt||0)?a:b;return a||b||fresh()}
async function save(){S.id=K();S.viewer=V;S.target=G;S.version=10;S.updatedAt=now();try{localStorage.setItem(K(),JSON.stringify(S))}catch(e){}try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(S);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch(e){}}
async function del(){try{localStorage.removeItem(K())}catch(e){}try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).delete(K());q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch(e){}}
function migrate(){S=S||fresh();S.traits=S.traits||{};TRAITS.forEach(k=>S.traits[k]=Number(S.traits[k]||0));S.needs=S.needs||{};for(const[k,v]of Object.entries({hunger:84,sleep:84,mood:80,bond:76,clean:92}))S.needs[k]=clamp(S.needs[k]??v);S.learned=S.learned||{};S.totalCare=Number(S.totalCare||0);S.growthXP=Math.max(Number(S.growthXP||0),Math.min(760,S.totalCare*4));S.poop=Number(S.poop||0);S.toiletMeter=Number(S.toiletMeter||0);S.careMistakes=Number(S.careMistakes||0);S.sleepUntil=Number(S.sleepUntil||0);S.lastTick=Number(S.lastTick||now());S.lastSpeech=S.lastSpeech||'……おけけ？'}
function decay(){const h=Math.min(72,Math.max(0,(now()-S.lastTick)/36e5));if(h<.02)return;S.needs.hunger=clamp(S.needs.hunger-h*3);S.needs.sleep=clamp(S.needs.sleep-h*(isAsleep()?-.8:2.2));S.needs.mood=clamp(S.needs.mood-h*1.2);S.needs.bond=clamp(S.needs.bond-h*.45);S.needs.clean=clamp(S.needs.clean-h*.65);S.toiletMeter+=h*2.7;while(S.toiletMeter>=100&&S.poop<2){S.toiletMeter-=100;S.poop++;S.needs.clean=clamp(S.needs.clean-18)}const l=lv();if(h>=2&&Object.values(l).some(v=>v<18))S.careMistakes++;S.lastTick=now()}
function stage(){return S.growthXP>=820?['adult','おとな',820,820]:S.growthXP>=320?['child','こども',320,820]:S.growthXP>=80?['baby','あかちゃん',80,320]:['egg','たまご',0,80]}
function lv(){return{hunger:clamp(S.needs.hunger),sleep:clamp(S.needs.sleep),mood:clamp((S.needs.mood+S.needs.bond)/2),clean:clamp(S.needs.clean)}}
function isAsleep(){return now()<Number(S.sleepUntil||0)}
function stateWord(k,v){const a={hunger:['ぺこぺこ','おなかすいた','まだ平気','おなかいっぱい'],sleep:['かなりねむい','ねむそう','まだ平気','元気いっぱい'],mood:['ごきげんななめ','ちょい退屈','まあまあ','ごきげん'],clean:['よごれてる','そろそろおふろ','まだきれい','ぴかぴか']};return a[k][v<25?0:v<50?1:v<75?2:3]}
function need(){if(isAsleep())return['sleeping','🌙','すやすや寝てる'];if(S.poop>0)return['toilet','🚽','トイレしたみたい'];const l=lv(),[k,v]=Object.entries(l).sort((a,b)=>a[1]-b[1])[0];if(v>=55)return['fine','☀️','ごきげんだよ'];const a={hunger:['🍚','おなかすいてる'],sleep:['🌙','ねむそう'],mood:['🎮','あそびたそう'],clean:['🫧','そろそろおふろ']};return[k,a[k][0],a[k][1]]}
function topTrait(){return TRAITS.slice().sort((a,b)=>S.traits[b]-S.traits[a])[0]||'affection'}
function catchwords(){return Object.entries(S.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1])}
function maybeCatch(line){const c=catchwords();if(!c.length)return line;const [w,n]=c[0];const chance=Math.min(.72,.12+n*.14);if(Math.random()>chance)return line;return Math.random()<.5?`${line} ${w}`:`${w}。${line}`}
function pet(){return`<div class="g10pet"><i class="g10ear l"></i><i class="g10ear r"></i><i class="g10bodyp"></i><span class="g10eyes"><i></i><i></i></span><i class="g10mouth"></i></div>`}
function mount(){document.querySelector('.grow-shell')?.setAttribute('style','display:none!important');if(document.getElementById('g10'))return;const st=document.createElement('style');st.textContent=CSS;document.head.append(st);const x=document.createElement('div');x.id='g10';x.innerHTML=`<section class="g10w"><div class="g10top"><div class="g10id"><div class="g10logo">🥚</div><div class="g10title"><b>われわれ育成所</b><span>相手を、勝手に育てる。</span></div></div><div class="g10meta"><span class="g10chip" id="g10v"></span><span class="g10chip clock" id="g10c"></span><button class="g10share" id="g10s">画像にする</button></div></div><div class="g10body"><div class="g10grid"><section class="g10card g10left"><div class="g10name"><strong id="g10n"></strong><span class="g10stage" id="g10stage"></span></div><section class="g10room" id="g10room"><div class="g10bed"></div><div class="g10shelf"></div><div class="g10note" id="g10note"></div><div class="g10speech" id="g10speech"></div><span class="g10poop p1" id="g10p1" hidden>💩</span><span class="g10poop p2" id="g10p2" hidden>💩</span><div class="g10petbox" id="g10pet">${pet()}</div></section><p class="g10ident" id="g10ident"></p><div id="g10status"></div><div class="g10growth" id="g10growth"></div></section><section class="g10dock"><div class="g10care" id="g10care"></div><div class="g10tools"><button id="g10back">バックアップ</button></div></section><aside class="g10right"><section class="g10card"><h2 class="g10h">🗣 ことば <small id="g10wc"></small></h2><p class="g10explain">同じことばを3回教えると「くちぐせ」になる。くちぐせになったことばは、返事に出やすくなるよ。</p><div class="g10words" id="g10words"></div><button class="g10add" id="g10teach">＋ ことばを教える</button></section><section class="g10card"><h2 class="g10h">この子の育ちメモ</h2><div class="g10memo" id="g10memo"></div><button class="g10restart" id="g10restart">この子とお別れする</button></section></aside></div></div></section><div class="g10modal" id="g10wordmodal" hidden><div class="g10dlg"><h2>ことばを教える</h2><p>1回教えるごとに練習が進んで、3回でくちぐせになるよ。</p><div id="g10tw"></div><button class="g10close" id="g10wclose">やめとく</button></div></div><div class="g10modal" id="g10resetmodal" hidden><div class="g10dlg" id="g10resetbox"></div></div>`;document.querySelector('.conversation-shell')?.append(x);wire()}
const $=id=>document.getElementById(id);
function renderPet(){for(const p of document.querySelectorAll('.g10pet')){p.dataset.t=G;p.classList.toggle('egg',stage()[0]==='egg');p.classList.toggle('sleeping',isAsleep())}}
function render(){decay();const d=new Date(),L=lv(),ST=stage(),Q=need(),age=Math.max(0,Math.floor((new Date()-new Date((S.born||today())+'T00:00:00'))/864e5));$('g10v').textContent=`表示：${V}目線`;$('g10c').textContent=`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;$('g10room').dataset.t=G;$('g10room').classList.toggle('night',d.getHours()<6||d.getHours()>=18);$('g10n').textContent=N[G];$('g10stage').textContent=`${age}日目・${ST[1]}`;const tt=topTrait();$('g10ident').textContent=`${N[G]}成分 × ${N[V]}育ち。いまは「${TM[tt]}」がいちばん濃い。`;
if(ST[0]==='egg'){$('g10status').innerHTML=`<div class="g10st"><b>たまごのようす</b><small>${S.growthXP<28?'まだ静か。':S.growthXP<58?'たまにコトコトする。':'そろそろ出てきそう。'}</small></div>`}else{$('g10status').innerHTML=`<div class="g10st">${Object.entries({hunger:['🍚','満腹'],sleep:['🌙','元気'],mood:['✨','ごきげん'],clean:['🫧','きれい']}).map(([k,m])=>{const v=Math.round(L[k]),c=v<35?'low':v<70?'mid':'good';return`<div class="g10r ${c}"><b>${m[0]} ${m[1]}</b><div class="g10bar"><i style="width:${v}%"></i></div><span>${stateWord(k,v)}</span></div>`}).join('')}</div>`}
const start=ST[2],goal=ST[3],pct=ST[0]==='adult'?100:Math.max(0,Math.min(100,((S.growthXP-start)/(goal-start))*100));$('g10growth').innerHTML=ST[0]==='adult'?`<div class="g10growhead"><span>育ちポイント</span><b>${Math.round(S.growthXP)} pt</b></div><div class="g10growtext">おとなになった。</div>`:`<div class="g10growhead"><span>育ちポイント</span><b>${Math.round(S.growthXP)} / ${goal} pt</b></div><div class="g10growbar"><i style="width:${pct}%"></i></div><div class="g10growtext">あと ${Math.max(0,Math.ceil(goal-S.growthXP))} pt くらいで「${ST[0]==='egg'?'あかちゃん':ST[0]==='baby'?'こども':'おとな'}」へ。</div>`;
$('g10note').innerHTML=`いまのようす<br>${Q[1]} ${Q[2]}`;$('g10speech').textContent=isAsleep()?'すや…':(S.lastSpeech||'おけけ。');$('g10p1').hidden=S.poop<1;$('g10p2').hidden=S.poop<2;renderPet();learned();memo();care(ST,Q);save()}
function learned(){const a=catchwords(),habit=a.filter(([,n])=>n>=3),training=a.filter(([,n])=>n<3);$('g10wc').textContent=`くちぐせ ${habit.length}こ`;$('g10words').innerHTML=(habit.length||training.length)?`${habit.length?`<div class="g10word-group"><div class="g10word-label"><span>くちぐせ</span><span>返事に出やすい</span></div><div class="g10word-list">${habit.slice(0,8).map(([w,n])=>`<span class="g10word catch">${w}</span>`).join('')}</div></div>`:''}${training.length?`<div class="g10word-group"><div class="g10word-label"><span>練習中</span><span>あと少しでくちぐせ</span></div><div class="g10word-list">${training.slice(0,8).map(([w,n])=>`<span class="g10word training">${w} <small>あと${3-n}回</small></span>`).join('')}</div></div>`:''}`:'<span style="font-size:9px;color:#777">まだことばを教えていないよ。</span>';$('g10teach').style.display=stage()[0]==='egg'?'none':'block'}
function memo(){const c=catchwords().filter(([,n])=>n>=3).map(([w])=>w),ST=stage(),goal=ST[3];$('g10memo').innerHTML=`<div class="g10mrow"><span>お世話した</span><b>${S.totalCare}回</b></div><div class="g10mrow"><span>いちばん濃い育ち</span><b>${TM[topTrait()]}</b></div><div class="g10mrow"><span>くちぐせ</span><b>${c.length?c.slice(0,3).join('・'):'まだなし'}</b></div><div class="g10mrow"><span>お世話ミス</span><b>${S.careMistakes}回</b></div><div class="g10mrow"><span>育ちポイント</span><b>${Math.round(S.growthXP)}${ST[0]==='adult'?' pt':` / ${goal} pt`}</b></div>`}
function care(ST,Q){if(ST[0]==='egg'){const d={warm:['🫶','あたためる','ぬくぬくする'],call:['📣','名前を呼ぶ',`${N[G]}って呼ぶ`],tap:['👉','コツコツ','そっとノック'],hum:['🎵','うたう','適当に歌う'],listen:['👂','ようすを見る','中をうかがう'],word:['🌀','われわれ語','聞かせておく']};$('g10care').innerHTML=Object.entries(d).map(([k,v])=>`<button data-e="${k}"><i>${v[0]}</i><b>${v[1]}</b><small>${v[2]}</small></button>`).join('');return}const d={feed:['🍴','ごはん','たべものをあげる'],bath:['🛁','おふろ','からだをきれいに'],toilet:['🚽','トイレ','でたら片づける'],play:['🎮','あそぶ','いっしょにあそぶ'],pat:['💗','なでる','ちょっと甘やかす'],sleep:[isAsleep()?'☀️':'🌙',isAsleep()?'起こす':'ねる',isAsleep()?'そろそろ起きる':'オフトゥンへ']},r={hunger:'feed',sleep:'sleep',mood:'play',clean:'bath',toilet:'toilet',sleeping:'sleep'}[Q[0]];$('g10care').innerHTML=Object.entries(d).map(([k,v])=>`<button class="${r===k?'rec':''}" data-a="${k}">${r===k?'<em>いま</em>':''}<i>${v[0]}</i><b>${v[1]}</b><small>${v[2]}</small></button>`).join('')}
function pick(a){const pool={feed:['ごはん、だん！','これは食べる。','おけけ。ごはん。','もっとある？','食べた。えらい。'],bath:['カラダ・アラウ。','ぴかぴか、だん！','洗われた。','おけけ、きれい。','もう出ていい？'],toilet:['でた。見なかったことにして。','かたづけた。えらい。','おけけ。すっきり。'],play:['しょもしょもしようず。','もっかい。','それやる。','だん！','はやく。'],pat:['はすはすされてる。','てぇてぇ判定。','もっと。','そこ。','かわいいって言え。'],sleep:['オフトゥンいく。','ねう。','もうむり。','おやすみ。','すや…'],wake:['おはよ。','起きた。','まだねむい。','おけけ、起きる。'],teach:['覚えた。たぶん。','それ言えばいいの？','おけけ。覚える。']};const p=pool[a]||['おけけ。'];return p[Math.floor(Math.random()*p.length)]}
function eggReact(a){const p={warm:['……ぬく。','……あったか。','……コト。'],call:[`……${N[G]}？`,'……よんだ？','……。'],tap:['……コト。','……コツ。','……やめないで。'],hum:['……ふんふん。','……なにそれ。','……♪'],listen:['……おけけ。','……いる。','……コトコト。'],word:['……われわれ……？','……おけけ……？','……覚えたかも。']};const a2=p[a]||['……'];return a2[Math.floor(Math.random()*a2.length)]}
function reward(a){const L=lv(),proper={feed:L.hunger<65,bath:L.clean<65,toilet:S.poop>0,play:L.mood<70,pat:S.needs.bond<70,sleep:L.sleep<65}[a];const repeat=S.lastAction===a;return (proper?10:5)-(repeat?3:0)}
async function act(a){if(a!=='sleep'&&isAsleep()){S.sleepUntil=0;S.lastSpeech=pick('wake')}const n=S.needs;if(a==='feed'){if(n.hunger>92){S.lastSpeech='まだ入ると思ってる？';S.careMistakes++;}else{n.hunger+=34;n.mood+=5;S.toiletMeter+=32;S.traits.food+=1.7;S.lastSpeech=maybeCatch(pick('feed'))}}if(a==='bath'){n.clean+=52;S.traits.routine+=.6;S.lastSpeech=maybeCatch(pick('bath'))}if(a==='toilet'){if(S.poop>0){S.poop=0;n.clean+=18;S.lastSpeech=maybeCatch(pick('toilet'))}else{S.lastSpeech='まだでない。'}}if(a==='play'){if(n.sleep<20){S.lastSpeech='ねむい。いまむり。'}else{n.mood+=34;n.bond+=10;n.hunger-=7;n.sleep-=8;S.traits.playful+=1.8;S.lastSpeech=maybeCatch(pick('play'))}}if(a==='pat'){n.bond+=31;n.mood+=12;S.traits.affection+=1.7;S.lastSpeech=maybeCatch(pick('pat'))}if(a==='sleep'){if(isAsleep()){S.sleepUntil=0;S.lastSpeech=pick('wake')}else if(n.sleep>92){S.lastSpeech='まだねない。'}else{S.sleepUntil=now()+90*60*1000;n.sleep+=45;S.traits.routine+=1.5;S.lastSpeech=pick('sleep')}}for(const k in n)n[k]=clamp(n[k]);S.totalCare++;S.growthXP+=Math.max(2,reward(a));S.lastAction=a;await save();render()}
async function egg(a){S.totalCare++;S.growthXP+=S.lastAction===a?5:8;if(['warm','call'].includes(a))S.traits.affection++;if(a==='tap')S.traits.playful+=.7;if(a==='word')S.traits.weird++;S.lastSpeech=eggReact(a);S.lastAction=a;await save();render()}
function teachOpen(){const known=new Map(catchwords()),habit=WORDS.filter(w=>(known.get(w)||0)>=3),training=WORDS.filter(w=>{const n=known.get(w)||0;return n>0&&n<3}),freshWords=WORDS.filter(w=>(known.get(w)||0)===0);const buttons=(arr,type)=>arr.map(w=>{const n=known.get(w)||0,label=type==='habit'?'くちぐせ':type==='training'?`あと${3-n}回`:'まだ教えてない';return`<button class="${type==='habit'?'catch':type==='training'?'training':''}" data-w="${w}">${w}<small>${label}</small></button>`}).join('');$('g10tw').innerHTML=`${training.length?`<div class="g10teach-block"><div class="g10teach-label">練習中</div><div class="g10twords">${buttons(training,'training')}</div></div>`:''}<div class="g10teach-block"><div class="g10teach-label">まだ教えてない</div><div class="g10twords">${buttons(freshWords,'fresh')}</div></div>${habit.length?`<div class="g10teach-block"><div class="g10teach-label">もう、くちぐせ</div><div class="g10twords">${buttons(habit,'habit')}</div></div>`:''}`;$('g10wordmodal').hidden=false}
function resetAsk(step=1){$('g10resetmodal').hidden=false;$('g10resetbox').innerHTML=step===1?`<h2>${N[G]}とお別れする？</h2><p>今の育ち方・覚えたことば・お世話回数は全部なくなるよ。</p><button class="g10danger" id="g10resetnext">お別れする</button><button class="g10cancel" id="g10resetcancel">やっぱりやめる</button>`:`<h2>本当にお別れする？</h2><p>この操作は元に戻せないよ。新しいたまごから育て直すことになる。</p><button class="g10danger" id="g10resetgo">本当に育て直す</button><button class="g10cancel" id="g10resetcancel">やめる</button>`;const c=$('g10resetcancel');if(c)c.onclick=()=>{$('g10resetmodal').hidden=true};const n=$('g10resetnext');if(n)n.onclick=()=>resetAsk(2);const g=$('g10resetgo');if(g)g.onclick=async()=>{await del();S=fresh();await save();$('g10resetmodal').hidden=true;render()}}
function wire(){$('g10care').onclick=e=>{const b=e.target.closest('[data-a],[data-e]');if(b)b.dataset.a?act(b.dataset.a):egg(b.dataset.e)};$('g10teach').onclick=teachOpen;$('g10tw').onclick=async e=>{const b=e.target.closest('[data-w]');if(!b)return;const w=b.dataset.w;S.learned[w]=(S.learned[w]||0)+1;S.traits.weird+=1.1;S.totalCare++;S.growthXP+=5;S.lastSpeech=maybeCatch(`${w}。……${w}。`);$('g10wordmodal').hidden=true;await save();render()};$('g10wclose').onclick=()=>{$('g10wordmodal').hidden=true};$('g10restart').onclick=()=>resetAsk(1);$('g10back').onclick=()=>{const b=new Blob([JSON.stringify({app:'warera-grow',version:10,state:S},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`warera-grow-${V}-${G}.json`;a.click()};$('g10s').onclick=()=>document.getElementById('shareBtn')?.click()}
async function boot(){V=getV();G=V==='み'?'も':'み';S=await load();migrate();mount();render()}
setTimeout(boot,0);let seen=V;setInterval(async()=>{const v=getV();if(v!==seen){seen=v;document.getElementById('g10')?.remove();await boot()}else if(S)render()},60000);
})();