(()=>{
if(!/\/grow\/?$/.test(location.pathname))return;
const P='warera_grow_v1_',DB='warera-grow',STORE='pets',N={み:'みちゃこ',も:'もっち'};
const TRAITS=['affection','playful','food','routine','weird','independent','night'];
const TM={affection:'甘やかされ育ち',playful:'あそび好き',food:'ごはん好き',routine:'生活しっかり',weird:'われわれ語多め',independent:'ひとりでも平気',night:'夜ふかし育ち'};
const WORDS=['われわれ','しょもしょも','おけけ','オフトゥン','てぇてぇ','はすはす','ガラスープ','かわいい','好き','ねむい','だん！','カラダ・アラウ','おはよ','おやすみ','ごはん','ほんと','なるほど','待って','やだ','ありがとう','ごめん','ちっち','ぱっちくん','もっかい','えらい','むり','まだねない','すや…','いいよ','なに','はい','ふむ','ほう','よし','いや','まって','わかる','知らんけど','それな','おなかすいた','ねう','起きた','もうむり','たしかに','草','わろた','うける','ん？','え？','ほーん','まじか','だめ','いいじゃん','やる','やらん','あとで','いま','まだ','もう','ちょっと','めっちゃ','すご','天才','えらすぎ','かわよ','むふ','ふふ','へへ','ぬく','さむ','あつ','ねむ','お腹いっぱい','おふろ','きれい','ぴかぴか','でた','すっきり','あそぼ','もっかい！','そこ','もっと','はやく','おそい','はいはい','りょ','了解','承知','おけ','おけけけ','だんだん！','よい','よき','よかった','ほんま？','なんで','どうして','しらん','なる','なるほどね','そゆこと','たぶん','たしか','ほんとに？','ま？','まじ？','ひえ','うわ','わーい','やった','やったー','うれし','かなし','しょん','むず','むりぽ','いける','いけそう','がんばる','がんばれ','おつ','おつかれ','おかえり','ただいま','いってら','いってきます','おは','おやす','ねてた','起こされた','腹へった','飯','おやつ','甘いの','なんか食べたい','お水','のむ','あそびたい','ひま','かまって','なでて','ぎゅ','すきすき','ちゅ','やめれ','こら','よしよし','えへ','むふふ'];
const SAY={
feed:['ごはん、だん！','これは食べる。','おけけ。ごはん。','もっとある？','食べた。えらい。','飯きた。','おなかに入った。','うま。','もぐもぐしてる。','これ好き。','それも食べる。','一口でいった。','まだいける。','お腹いっぱいになってきた。','ごはんは正義。','食べたのでえらい。','今日はこれか。','もっかいある？','おやつではない？','完食。だん！'],
bath:['カラダ・アラウ。','ぴかぴか、だん！','洗われた。','おけけ、きれい。','もう出ていい？','あわあわ。','そこ洗った？','きれいになった気がする。','湯船ある？','おふろの時間だった。','洗浄された。','つるつる。','まだ入ってる。','あったかい。','長風呂の予感。','泡まみれ。','カラダ・アラウ・完了。','ぴかぴか判定。'],
toilet:['でた。見なかったことにして。','かたづけた。えらい。','おけけ。すっきり。','流された。','なかったことになった。','トイレ完了。','すっきりした顔。','見た？','ちゃんと流して。','何もなかった。いいね？','だん！','片づいた。'],
play:['しょもしょもしようず。','もっかい。','それやる。','だん！','はやく。','まだ終わらん。','もう一回だけ。','遊ぶやつきた。','それ得意かも。','いける。','負けてない。','本気出す。','遊んだので満足。','楽しい判定。','次なにする？','それもう一回。','ちょっと待って今のなし。','勝ったことにする。','われわれタイム。','しょもしょも継続。'],
pat:['はすはすされてる。','てぇてぇ判定。','もっと。','そこ。','かわいいって言え。','よしよしされた。','悪くない。','もうちょい。','そこ正解。','なでられている。','甘やかし確認。','ふふ。','へへ。','それ好き。','手を止めるな。','かわいいを追加で。','なで継続希望。','満足してない顔。','ぎゅも可。','てぇてぇ。'],
sleep:['オフトゥンいく。','ねう。','もうむり。','おやすみ。','すや…','今日はここまで。','まぶたが限界。','オフトゥンしか勝たん。','横になる。','寝る体勢。','もう動かん。','おやすみ判定。','すやすやする。','眠気に負けた。'],
wake:['おはよ。','起きた。','まだねむい。','おけけ、起きる。','何時？','もう朝？','起こされた。','あと5分。','むり、まだねる。','目は開いた。','たぶん起きた。','おは。'],
teach:['覚えた。たぶん。','それ言えばいいの？','おけけ。覚える。','復唱します。','またそれ？','はいはい覚えた。','脳に入れた。','くちぐせ候補。','言わされてる。','そのうち使う。','たぶん使う。','覚えさせられた。']
};
const CSS=`
#g11{width:min(1180px,calc(100vw - 32px));max-width:none;position:relative;left:50%;transform:translateX(-50%);margin:0 auto;color:#111}.g11w{overflow:hidden;border:1px solid #111;border-radius:10px;background:#f4f4f4;box-shadow:4px 4px 0 rgba(0,0,0,.4)}
.g11top{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:14px;padding:12px 16px;border-bottom:1px solid #111;background:#fff}.g11id{display:flex;align-items:center;gap:11px}.g11logo{display:grid;place-items:center;width:46px;height:46px;border:1px solid #111;border-radius:50%;background:#f1f1f1;font-size:23px}.g11title b{font-size:20px;font-weight:800}.g11title span{display:block;margin-top:3px;color:#666;font-size:10px}.g11meta{display:flex;align-items:center;gap:8px;align-self:center}.g11chip,.g11share{height:38px;padding:0 12px;border:1px solid #111;border-radius:9px;background:#fff;color:#111;font:700 10px 'Noto Sans JP',sans-serif;box-shadow:2px 2px 0 rgba(0,0,0,.25)}
.g11body{padding:14px}.g11grid{display:grid;grid-template-columns:minmax(0,2.9fr) minmax(285px,.8fr);grid-template-rows:auto auto;gap:14px;align-items:start}.g11card,.g11room,.g11dock{border:1px solid #111;border-radius:10px;background:#fff;box-shadow:3px 3px 0 rgba(0,0,0,.24)}.g11left{grid-column:1;grid-row:1;min-width:0;padding:16px}.g11right{grid-column:2;grid-row:1;display:grid;gap:14px;min-width:0}.g11dock{grid-column:1/-1;grid-row:2;padding:12px}.g11name{display:flex;justify-content:space-between;align-items:center;gap:10px}.g11name strong{font-size:26px}.g11stage{padding:5px 8px;border:1px solid #111;border-radius:999px;font-size:9px;font-weight:800;background:#fff}
.g11room{position:relative;min-height:420px;margin:12px 0;overflow:hidden;background:linear-gradient(#fff0f4 0 53%,#f2d1b2 53%);box-shadow:none}.g11room[data-t="も"]{background:linear-gradient(#eef7ff 0 53%,#f2d1b2 53%)}.g11room.night{background:linear-gradient(#d8dbea 0 53%,#c8aa8b 53%)}.g11room:before{content:'';position:absolute;left:7%;top:10%;width:35%;height:31%;border:5px solid #9b7a64;border-radius:5px;background:#9bd8ff}.g11room.night:before{background:#4e628d}.g11room:after{content:'';position:absolute;left:24%;right:17%;bottom:6%;height:18%;border-radius:50%;background:repeating-linear-gradient(45deg,#f8e3e6 0 18px,#efcfd5 18px 36px)}.g11bed{position:absolute;left:5%;bottom:12%;width:30%;height:16%;border:1px solid #111;border-radius:45% 45% 18% 18%;background:#f7bdc9}.g11shelf{position:absolute;right:5%;bottom:16%;width:20%;height:31%;border:4px solid #9b6a4b;background:#d5a27d}.g11note{position:absolute;right:3%;top:4%;z-index:5;max-width:220px;padding:8px 10px;border:1px solid #111;border-radius:7px;background:#fff;box-shadow:2px 2px 0 rgba(0,0,0,.2);font-size:10px;font-weight:800;line-height:1.45}.g11speech{position:absolute;left:50%;bottom:62%;z-index:8;max-width:330px;transform:translateX(-50%);padding:8px 11px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:2px 2px 0 rgba(0,0,0,.2);font-size:11px;font-weight:800;text-align:center}.g11petbox{position:absolute;left:50%;bottom:9%;z-index:6;transform:translateX(-50%) scale(1.22)}
.g11pet{--p:#ffe6a6;--d:#111;position:relative;width:150px;height:170px;transition:.2s}.g11pet[data-t="み"]{--p:#ffdce8}.g11bodyp{position:absolute;left:50%;bottom:12px;width:136px;height:128px;transform:translateX(-50%);border:3px solid var(--d);border-radius:46%;background:var(--p)}.g11ear{position:absolute;top:17px;width:47px;height:58px;border:3px solid var(--d);background:var(--p)}.g11ear.l{left:18px;border-radius:65% 25% 20% 40%;transform:rotate(-14deg)}.g11ear.r{right:18px;border-radius:25% 65% 40% 20%;transform:rotate(14deg)}.g11eyes{position:absolute;left:50%;top:47%;z-index:3;display:flex;gap:42px;transform:translateX(-50%)}.g11eyes i{width:16px;height:21px;border-radius:45%;background:var(--d);transition:.18s}.g11mouth{position:absolute;left:50%;top:58%;z-index:3;width:25px;height:10px;transform:translateX(-50%);border-bottom:3px solid var(--d);border-radius:0 0 55% 55%}.g11pet.sleeping .g11eyes i{height:4px;margin-top:9px;border-radius:999px}.g11pet.sleeping .g11mouth{width:16px;height:4px;border-bottom-width:2px}.g11pet.egg .g11ear,.g11pet.egg .g11eyes,.g11pet.egg .g11mouth{display:none}.g11pet.egg .g11bodyp{height:158px;border-radius:50% 50% 44% 44%/58% 58% 42% 42%;background:linear-gradient(135deg,#fff,var(--p))}.g11poop{position:absolute;bottom:14%;z-index:7;font-size:24px}.p1{left:31%}.p2{right:28%}
.g11fx{position:absolute;inset:0;z-index:15;pointer-events:none;overflow:hidden}.fx-item{position:absolute;left:50%;top:55%;font-size:34px;transform:translate(-50%,-50%);animation:fxPop .8s ease forwards}.fx-feed{animation:fxFeed .75s ease forwards}.fx-bath{font-size:24px;animation:fxBubble 1s ease forwards}.fx-heart{color:#e67ca0;animation:fxHeart .9s ease forwards}.fx-play{animation:fxSpin .8s ease forwards}.fx-flush{font-size:52px;animation:fxFlush .9s ease forwards}.g11pet.anim-bounce{animation:petBounce .55s ease}.g11pet.anim-wiggle{animation:petWiggle .5s ease}.g11pet.anim-squish{animation:petSquish .5s ease}.g11pet.anim-doze{animation:petDoze .7s ease}.g11pet.anim-clean{animation:petClean .6s ease}
@keyframes petBounce{0%,100%{transform:translateY(0)}45%{transform:translateY(-22px) scale(1.04)}}@keyframes petWiggle{0%,100%{transform:rotate(0)}25%{transform:rotate(-7deg)}75%{transform:rotate(7deg)}}@keyframes petSquish{50%{transform:scale(1.08,.92)}}@keyframes petDoze{50%{transform:translateY(6px) scale(.98)}}@keyframes petClean{50%{filter:brightness(1.18);transform:rotate(3deg)}}@keyframes fxPop{0%{opacity:0;transform:translate(-50%,-20%) scale(.5)}40%{opacity:1}100%{opacity:0;transform:translate(-50%,-130%) scale(1.15)}}@keyframes fxFeed{0%{opacity:0;transform:translate(-180px,-120px) rotate(-20deg)}30%{opacity:1}100%{opacity:0;transform:translate(-10px,70px) scale(.5)}}@keyframes fxBubble{0%{opacity:0;transform:translate(-50%,80px) scale(.4)}30%{opacity:1}100%{opacity:0;transform:translate(-50%,-180px) scale(1.3)}}@keyframes fxHeart{0%{opacity:0;transform:translate(-50%,30px) scale(.5)}30%{opacity:1}100%{opacity:0;transform:translate(-50%,-150px) scale(1.3)}}@keyframes fxSpin{0%{opacity:0;transform:translate(-50%,-50%) scale(.5) rotate(0)}30%{opacity:1}100%{opacity:0;transform:translate(-50%,-130%) scale(1.3) rotate(220deg)}}@keyframes fxFlush{0%{opacity:1;transform:translate(-50%,-50%) scale(1)}70%{opacity:1;transform:translate(-50%,40%) scale(.7) rotate(260deg)}100%{opacity:0;transform:translate(-50%,80%) scale(.2) rotate(420deg)}}
.g11ident{padding:9px;border:1px solid #ddd;border-radius:8px;background:#fafafa;font-size:10px;font-weight:700;line-height:1.55}.g11st{display:grid;gap:9px;margin-top:12px}.g11r{display:grid;grid-template-columns:82px 1fr 78px;align-items:center;gap:8px}.g11r b{font-size:10px}.g11bar{height:12px;border:1px solid #111;border-radius:999px;background:#fff;overflow:hidden}.g11bar i{display:block;height:100%;border-radius:999px}.good i{background:#98cfa5}.mid i{background:#e5c66f}.low i{background:#e5a19a}.g11r span{color:#666;font-size:8px;font-weight:700;text-align:right}.g11growth{margin-top:12px;padding:10px;border-top:1px solid #ddd}.g11growhead{display:flex;justify-content:space-between;gap:8px;margin-bottom:6px;font-size:9px;font-weight:800}.g11growbar{height:9px;border:1px solid #111;border-radius:999px;background:#fff;overflow:hidden}.g11growbar i{display:block;height:100%;background:#111}.g11growtext{margin-top:5px;color:#666;font-size:8px}
.g11card{padding:14px}.g11h{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:0 0 9px;font-size:14px}.g11h small{color:#777;font-size:8px}.g11section-label{margin:10px 0 5px;color:#666;font-size:8px;font-weight:800}.g11words{display:flex;flex-wrap:wrap;gap:6px}.g11word{padding:5px 7px;border:1px solid #111;border-radius:999px;background:#fff;font-size:8px;font-weight:800}.g11word.catch{background:#111;color:#fff}.g11word.practice{border-style:dashed}.g11explain{margin:0 0 9px;color:#666;font-size:9px;line-height:1.55}.g11add{width:100%;margin-top:10px;padding:8px;border:1px dashed #999;border-radius:8px;background:#fafafa;font:800 9px 'Noto Sans JP',sans-serif}.g11memo{display:grid;gap:7px}.g11mrow{display:flex;justify-content:space-between;gap:12px;padding-bottom:6px;border-bottom:1px solid #eee;font-size:9px}.g11mrow span{color:#666}.g11mrow b{text-align:right}.g11restart{width:100%;margin-top:10px;padding:8px;border:1px solid #111;border-radius:8px;background:#fff;font:800 9px 'Noto Sans JP',sans-serif}
.g11care{display:grid;grid-template-columns:repeat(6,1fr);gap:9px}.g11care button{position:relative;min-height:100px;padding:10px 6px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:2px 2px 0 rgba(0,0,0,.2);cursor:pointer}.g11care button.rec{background:#111;color:#fff}.g11care em{position:absolute;right:5px;top:5px;padding:2px 5px;border:1px solid currentColor;border-radius:999px;font:800 6px sans-serif}.g11care i{display:block;font-style:normal;font-size:29px}.g11care b{display:block;margin-top:5px;font-size:11px}.g11care small{display:block;margin-top:3px;color:#777;font-size:7px}.g11care button.rec small{color:#ddd}.g11tools{display:flex;justify-content:flex-end;gap:6px;margin-top:8px}.g11tools button{padding:5px 8px;border:1px solid #111;border-radius:7px;background:#fff;font:700 8px sans-serif}
.g11modal{position:fixed;inset:0;z-index:160;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.28)}.g11modal[hidden]{display:none}.g11dlg{width:min(100%,440px);padding:16px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:4px 4px 0 rgba(0,0,0,.35)}.g11dlg h2{margin:0 0 7px;font-size:18px}.g11dlg p{margin:0 0 12px;color:#666;font-size:10px;line-height:1.6}.g11twords{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;max-height:330px;overflow:auto}.g11twords button,.g11close,.g11danger,.g11cancel{padding:9px;border:1px solid #111;border-radius:8px;background:#fff;font-weight:800}.g11twords button.catch{background:#111;color:#fff}.g11twords button.practice{border-style:dashed}.g11group{grid-column:1/-1;margin-top:7px;padding-top:7px;border-top:1px solid #ddd;color:#666;font-size:9px;font-weight:800}.g11close{width:100%;margin-top:8px}.g11danger{width:100%;background:#111;color:#fff}.g11cancel{width:100%;margin-top:7px}
@media(max-width:980px){.g11grid{grid-template-columns:minmax(0,2fr) minmax(250px,.82fr)}.g11care{grid-template-columns:repeat(3,1fr)}}
@media(max-width:720px){#g11{width:min(100% - 24px,680px);left:50%}.g11top{min-height:64px;padding:10px}.g11title span{display:none}.g11meta{gap:5px}.g11chip,.g11share{height:34px;padding:0 8px;font-size:8px}.g11body{padding:8px}.g11grid{display:flex;flex-direction:column}.g11left{order:1;width:100%;padding:11px}.g11dock{order:2;width:100%;margin-top:0}.g11right{order:3;width:100%}.g11room{min-height:340px}.g11petbox{transform:translateX(-50%) scale(.94)}.g11speech{bottom:61%;max-width:230px}.g11care{grid-template-columns:repeat(3,1fr);gap:6px}.g11care button{min-height:82px;padding:7px 4px}.g11care i{font-size:24px}.g11care b{font-size:9px}.g11care small{font-size:6.5px}.g11r{grid-template-columns:72px 1fr 62px}.g11twords{grid-template-columns:repeat(2,1fr)}}`;
let V=getV(),G=V==='み'?'も':'み',S;
function getV(){try{return localStorage.getItem('warera_chat_perspective')==='も'?'も':'み'}catch(e){return'み'}}
const K=()=>`${P}${V}_${G}`,clamp=v=>Math.max(0,Math.min(100,Number(v)||0)),now=()=>Date.now(),today=()=>new Date().toISOString().slice(0,10);
function fresh(){const t={};TRAITS.forEach(k=>t[k]=0);return{id:K(),version:11,viewer:V,target:G,born:today(),totalCare:0,growthXP:0,traits:t,needs:{hunger:84,sleep:84,mood:80,bond:76,clean:92},learned:{},poop:0,toiletMeter:0,careMistakes:0,lastSpeech:'……おけけ？',lastAction:'',lastTick:now(),sleepUntil:0,updatedAt:now()}}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
async function readDb(){try{const db=await openDb(),x=await new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(K());q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)});db.close();return x}catch(e){return null}}
function readLocal(){try{return JSON.parse(localStorage.getItem(K())||'null')}catch(e){return null}}
async function load(){const[a,b]=await Promise.all([readDb(),Promise.resolve(readLocal())]);if(a&&b)return Number(a.updatedAt||0)>=Number(b.updatedAt||0)?a:b;return a||b||fresh()}
async function save(){S.id=K();S.viewer=V;S.target=G;S.version=11;S.updatedAt=now();try{localStorage.setItem(K(),JSON.stringify(S))}catch(e){}try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(S);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch(e){}}
async function del(){try{localStorage.removeItem(K())}catch(e){}try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).delete(K());q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch(e){}}
function migrate(){S=S||fresh();S.traits=S.traits||{};TRAITS.forEach(k=>S.traits[k]=Number(S.traits[k]||0));S.needs=S.needs||{};for(const[k,v]of Object.entries({hunger:84,sleep:84,mood:80,bond:76,clean:92}))S.needs[k]=clamp(S.needs[k]??v);S.learned=S.learned||{};S.totalCare=Number(S.totalCare||0);S.growthXP=Math.max(Number(S.growthXP||0),Math.min(760,S.totalCare*4));S.poop=Number(S.poop||0);S.toiletMeter=Number(S.toiletMeter||0);S.careMistakes=Number(S.careMistakes||0);S.sleepUntil=Number(S.sleepUntil||0);S.lastTick=Number(S.lastTick||now());S.lastSpeech=S.lastSpeech||'……おけけ？'}
function isAsleep(){return now()<Number(S.sleepUntil||0)}
function decay(){const h=Math.min(72,Math.max(0,(now()-S.lastTick)/36e5));if(h<.02)return;S.needs.hunger=clamp(S.needs.hunger-h*1.5);S.needs.sleep=clamp(S.needs.sleep-h*(isAsleep()?-.8:1));S.needs.mood=clamp(S.needs.mood-h*.5);S.needs.bond=clamp(S.needs.bond-h*.3);S.needs.clean=clamp(S.needs.clean-h*.3);S.toiletMeter+=h*1.8;while(S.toiletMeter>=100&&S.poop<2){S.toiletMeter-=100;S.poop++;S.needs.clean=clamp(S.needs.clean-14)}const l=lv();if(h>=4&&Object.values(l).some(v=>v<15))S.careMistakes++;S.lastTick=now()}
function stage(){return S.growthXP>=820?['adult','おとな',820,820]:S.growthXP>=320?['child','こども',320,820]:S.growthXP>=80?['baby','あかちゃん',80,320]:['egg','たまご',0,80]}
function lv(){return{hunger:clamp(S.needs.hunger),sleep:clamp(S.needs.sleep),mood:clamp((S.needs.mood+S.needs.bond)/2),clean:clamp(S.needs.clean)}}
function stateWord(k,v){const a={hunger:['ぺこぺこ','おなかすいた','まだ平気','おなかいっぱい'],sleep:['かなりねむい','ねむそう','まだ平気','元気いっぱい'],mood:['ごきげんななめ','ちょい退屈','まあまあ','ごきげん'],clean:['よごれてる','そろそろおふろ','まだきれい','ぴかぴか']};return a[k][v<25?0:v<50?1:v<75?2:3]}
function need(){if(isAsleep())return['sleeping','🌙','すやすや寝てる'];if(S.poop>0)return['toilet','🚽','トイレしたみたい'];const l=lv(),[k,v]=Object.entries(l).sort((a,b)=>a[1]-b[1])[0];if(v>=55)return['fine','☀️','ごきげんだよ'];const a={hunger:['🍚','おなかすいてる'],sleep:['🌙','ねむそう'],mood:['🎮','あそびたそう'],clean:['🫧','そろそろおふろ']};return[k,a[k][0],a[k][1]]}
function topTrait(){return TRAITS.slice().sort((a,b)=>S.traits[b]-S.traits[a])[0]||'affection'}
function catchwords(){return Object.entries(S.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1])}
function maybeCatch(line){const c=catchwords();if(!c.length)return line;const [w,n]=c[Math.min(c.length-1,Math.floor(Math.random()*Math.min(4,c.length)))];const chance=Math.min(.78,.10+n*.15);if(Math.random()>chance)return line;return Math.random()<.5?`${line} ${w}`:`${w}。${line}`}
function pick(a){const p=SAY[a]||['おけけ。'];return p[Math.floor(Math.random()*p.length)]}
function pet(){return`<div class="g11pet"><i class="g11ear l"></i><i class="g11ear r"></i><i class="g11bodyp"></i><span class="g11eyes"><i></i><i></i></span><i class="g11mouth"></i></div>`}
function mount(){document.querySelector('.grow-shell')?.setAttribute('style','display:none!important');document.getElementById('g10')?.remove();if(document.getElementById('g11'))return;const st=document.createElement('style');st.textContent=CSS;document.head.append(st);const x=document.createElement('div');x.id='g11';x.innerHTML=`<section class="g11w"><div class="g11top"><div class="g11id"><div class="g11logo">🥚</div><div class="g11title"><b>われわれ育成所</b><span>相手を、勝手に育てる。</span></div></div><div class="g11meta"><span class="g11chip" id="g11v"></span><button class="g11share" id="g11s">画像にする</button></div></div><div class="g11body"><div class="g11grid"><section class="g11card g11left"><div class="g11name"><strong id="g11n"></strong><span class="g11stage" id="g11stage"></span></div><section class="g11room" id="g11room"><div class="g11bed"></div><div class="g11shelf"></div><div class="g11note" id="g11note"></div><div class="g11speech" id="g11speech"></div><span class="g11poop p1" id="g11p1" hidden>💩</span><span class="g11poop p2" id="g11p2" hidden>💩</span><div class="g11petbox" id="g11pet">${pet()}</div><div class="g11fx" id="g11fx"></div></section><p class="g11ident" id="g11ident"></p><div id="g11status"></div><div class="g11growth" id="g11growth"></div></section><aside class="g11right"><section class="g11card"><h2 class="g11h">🗣 ことば <small id="g11wc"></small></h2><p class="g11explain">教えたことばは返事に混ざる。3回教えると「くちぐせ」になって、さらに出やすくなるよ。</p><div id="g11words"></div><button class="g11add" id="g11teach">＋ ことばを教える</button></section><section class="g11card"><h2 class="g11h">この子の育ちメモ</h2><div class="g11memo" id="g11memo"></div><button class="g11restart" id="g11restart">この子とお別れする</button></section></aside><section class="g11dock"><div class="g11care" id="g11care"></div><div class="g11tools"><button id="g11back">バックアップ</button></div></section></div></div></section><div class="g11modal" id="g11wordmodal" hidden><div class="g11dlg"><h2>ことばを教える</h2><p>同じことばを3回教えると「くちぐせ」になるよ。</p><div class="g11twords" id="g11tw"></div><button class="g11close" id="g11wclose">やめとく</button></div></div><div class="g11modal" id="g11resetmodal" hidden><div class="g11dlg" id="g11resetbox"></div></div>`;document.querySelector('.conversation-shell')?.append(x);wire()}
const $=id=>document.getElementById(id);
function renderPet(){for(const p of document.querySelectorAll('.g11pet')){p.dataset.t=G;p.classList.toggle('egg',stage()[0]==='egg');p.classList.toggle('sleeping',isAsleep())}}
function fx(type){const box=$('g11fx'),pet=$('g11pet')?.querySelector('.g11pet');if(!box||!pet)return;const cfg={feed:['🍙','fx-item fx-feed','anim-squish'],bath:['🫧','fx-item fx-bath','anim-clean'],toilet:['🌀','fx-item fx-flush','anim-wiggle'],play:['✨','fx-item fx-play','anim-bounce'],pat:['💗','fx-item fx-heart','anim-squish'],sleep:['💤','fx-item','anim-doze'],wake:['☀️','fx-item','anim-bounce'],teach:['💬','fx-item','anim-wiggle'],egg:['✨','fx-item','anim-wiggle']}[type];if(!cfg)return;box.innerHTML=`<span class="${cfg[1]}">${cfg[0]}</span>`;pet.classList.add(cfg[2]);setTimeout(()=>{box.innerHTML='';pet.classList.remove(cfg[2])},1000)}
function render(){decay();const d=new Date(),L=lv(),ST=stage(),Q=need(),age=Math.max(0,Math.floor((new Date()-new Date((S.born||today())+'T00:00:00'))/864e5));$('g11v').textContent=`表示：${V}目線`;$('g11room').dataset.t=G;$('g11room').classList.toggle('night',d.getHours()<6||d.getHours()>=18);$('g11n').textContent=N[G];$('g11stage').textContent=`${age}日目・${ST[1]}`;const tt=topTrait();$('g11ident').textContent=`${N[G]}成分 × ${N[V]}育ち。いまは「${TM[tt]}」がいちばん濃い。`;
if(ST[0]==='egg')$('g11status').innerHTML=`<div class="g11st"><b>たまごのようす</b><small>${S.growthXP<28?'まだ静か。':S.growthXP<58?'たまにコトコトする。':'そろそろ出てきそう。'}</small></div>`;else $('g11status').innerHTML=`<div class="g11st">${Object.entries({hunger:['🍚','満腹'],sleep:['🌙','元気'],mood:['✨','ごきげん'],clean:['🫧','きれい']}).map(([k,m])=>{const v=Math.round(L[k]),c=v<35?'low':v<70?'mid':'good';return`<div class="g11r ${c}"><b>${m[0]} ${m[1]}</b><div class="g11bar"><i style="width:${v}%"></i></div><span>${stateWord(k,v)}</span></div>`}).join('')}</div>`;
const start=ST[2],goal=ST[3],pct=ST[0]==='adult'?100:Math.max(0,Math.min(100,((S.growthXP-start)/(goal-start))*100));$('g11growth').innerHTML=ST[0]==='adult'?`<div class="g11growhead"><span>育ちポイント</span><b>${Math.round(S.growthXP)} pt</b></div><div class="g11growtext">おとなになった。</div>`:`<div class="g11growhead"><span>育ちポイント</span><b>${Math.round(S.growthXP)} / ${goal} pt</b></div><div class="g11growbar"><i style="width:${pct}%"></i></div><div class="g11growtext">あと ${Math.max(0,Math.ceil(goal-S.growthXP))} pt くらいで「${ST[0]==='egg'?'あかちゃん':ST[0]==='baby'?'こども':'おとな'}」へ。</div>`;
$('g11note').innerHTML=`いまのようす<br>${Q[1]} ${Q[2]}`;$('g11speech').textContent=isAsleep()?'すや…':(S.lastSpeech||'おけけ。');$('g11p1').hidden=S.poop<1;$('g11p2').hidden=S.poop<2;renderPet();learned();memo();care(ST,Q);save()}
function learned(){const a=catchwords(),habit=a.filter(([,n])=>n>=3),practice=a.filter(([,n])=>n<3);$('g11wc').textContent=`くちぐせ ${habit.length}こ`;let h='';if(habit.length)h+=`<div class="g11section-label">くちぐせ</div><div class="g11words">${habit.slice(0,8).map(([w])=>`<span class="g11word catch">${w}</span>`).join('')}</div>`;if(practice.length)h+=`<div class="g11section-label">練習中</div><div class="g11words">${practice.slice(0,8).map(([w,n])=>`<span class="g11word practice">${w}・あと${3-n}回</span>`).join('')}</div>`;if(!a.length)h='<span style="font-size:9px;color:#777">まだことばを教えていないよ。</span>';$('g11words').innerHTML=h;$('g11teach').style.display=stage()[0]==='egg'?'none':'block'}
function memo(){const c=catchwords().filter(([,n])=>n>=3).map(([w])=>w),ST=stage(),goal=ST[3];$('g11memo').innerHTML=`<div class="g11mrow"><span>お世話した</span><b>${S.totalCare}回</b></div><div class="g11mrow"><span>いちばん濃い育ち</span><b>${TM[topTrait()]}</b></div><div class="g11mrow"><span>くちぐせ</span><b>${c.length?c.slice(0,3).join('・'):'まだなし'}</b></div><div class="g11mrow"><span>お世話ミス</span><b>${S.careMistakes}回</b></div><div class="g11mrow"><span>育ちポイント</span><b>${Math.round(S.growthXP)}${ST[0]==='adult'?' pt':` / ${goal} pt`}</b></div>`}
function care(ST,Q){if(ST[0]==='egg'){const d={warm:['🫶','あたためる','ぬくぬくする'],call:['📣','名前を呼ぶ',`${N[G]}って呼ぶ`],tap:['👉','コツコツ','そっとノック'],hum:['🎵','うたう','適当に歌う'],listen:['👂','ようすを見る','中をうかがう'],word:['🌀','われわれ語','聞かせておく']};$('g11care').innerHTML=Object.entries(d).map(([k,v])=>`<button data-e="${k}"><i>${v[0]}</i><b>${v[1]}</b><small>${v[2]}</small></button>`).join('');return}const d={feed:['🍴','ごはん','たべものをあげる'],bath:['🛁','おふろ','からだをきれいに'],toilet:['🚽','トイレ','でたら片づける'],play:['🎮','あそぶ','いっしょにあそぶ'],pat:['💗','なでる','ちょっと甘やかす'],sleep:[isAsleep()?'☀️':'🌙',isAsleep()?'起こす':'ねる',isAsleep()?'そろそろ起きる':'オフトゥンへ']},r={hunger:'feed',sleep:'sleep',mood:'play',clean:'bath',toilet:'toilet',sleeping:'sleep'}[Q[0]];$('g11care').innerHTML=Object.entries(d).map(([k,v])=>`<button class="${r===k?'rec':''}" data-a="${k}">${r===k?'<em>いま</em>':''}<i>${v[0]}</i><b>${v[1]}</b><small>${v[2]}</small></button>`).join('')}
function eggReact(a){const p={warm:['……ぬく。','……あったか。','……コト。','……ぽか。'],call:[`……${N[G]}？`,'……よんだ？','……いる。','……なに。'],tap:['……コト。','……コツ。','……やめないで。','……もういっかい。'],hum:['……ふんふん。','……なにそれ。','……♪','……しってる？'],listen:['……おけけ。','……いる。','……コトコト。','……しずか。'],word:['……われわれ……？','……おけけ……？','……覚えたかも。','……もういっかい。']};const q=p[a]||['……'];return q[Math.floor(Math.random()*q.length)]}
function reward(a){const L=lv(),proper={feed:L.hunger<65,bath:L.clean<65,toilet:S.poop>0,play:L.mood<70,pat:S.needs.bond<70,sleep:L.sleep<65}[a],repeat=S.lastAction===a;return(proper?10:5)-(repeat?3:0)}
async function act(a){const wasSleep=isAsleep();if(a!=='sleep'&&wasSleep){S.sleepUntil=0;S.lastSpeech=pick('wake')}const n=S.needs;if(a==='feed'){if(n.hunger>92){S.lastSpeech='まだ入ると思ってる？';S.careMistakes++;}else{n.hunger+=34;n.mood+=5;S.toiletMeter+=32;S.traits.food+=1.7;S.lastSpeech=maybeCatch(pick('feed'))}}if(a==='bath'){n.clean+=52;S.traits.routine+=.6;S.lastSpeech=maybeCatch(pick('bath'))}if(a==='toilet'){if(S.poop>0){S.poop=0;n.clean+=18;S.lastSpeech=maybeCatch(pick('toilet'))}else S.lastSpeech='まだでない。'}if(a==='play'){if(n.sleep<20)S.lastSpeech='ねむい。いまむり。';else{n.mood+=34;n.bond+=10;n.hunger-=7;n.sleep-=8;S.traits.playful+=1.8;S.lastSpeech=maybeCatch(pick('play'))}}if(a==='pat'){n.bond+=31;n.mood+=12;S.traits.affection+=1.7;S.lastSpeech=maybeCatch(pick('pat'))}if(a==='sleep'){if(wasSleep){S.sleepUntil=0;S.lastSpeech=pick('wake');a='wake'}else if(n.sleep>92)S.lastSpeech='まだねない。';else{S.sleepUntil=now()+90*60*1000;n.sleep+=45;S.traits.routine+=1.5;S.lastSpeech=pick('sleep')}}for(const k in n)n[k]=clamp(n[k]);S.totalCare++;S.growthXP+=Math.max(2,reward(a==='wake'?'sleep':a));S.lastAction=a;await save();render();fx(a)}
async function egg(a){S.totalCare++;S.growthXP+=S.lastAction===a?5:8;if(['warm','call'].includes(a))S.traits.affection++;if(a==='tap')S.traits.playful+=.7;if(a==='word')S.traits.weird++;S.lastSpeech=eggReact(a);S.lastAction=a;await save();render();fx('egg')}
function teachOpen(){const known=new Map(catchwords()),groups=[['練習中',WORDS.filter(w=>(known.get(w)||0)>0&&(known.get(w)||0)<3)],['まだ教えてない',WORDS.filter(w=>!known.get(w))],['もう、くちぐせ',WORDS.filter(w=>(known.get(w)||0)>=3)]];$('g11tw').innerHTML=groups.map(([label,arr])=>arr.length?`<div class="g11group">${label}</div>${arr.map(w=>{const n=known.get(w)||0;return`<button class="${n>=3?'catch':n?'practice':''}" data-w="${w}">${w}${n&&n<3?`<small> あと${3-n}回</small>`:''}</button>`}).join('')}`:'').join('');$('g11wordmodal').hidden=false}
function resetAsk(step=1){$('g11resetmodal').hidden=false;$('g11resetbox').innerHTML=step===1?`<h2>${N[G]}とお別れする？</h2><p>今の育ち方・覚えたことば・お世話回数は全部なくなるよ。</p><button class="g11danger" id="g11resetnext">お別れする</button><button class="g11cancel" id="g11resetcancel">やっぱりやめる</button>`:`<h2>本当にお別れする？</h2><p>この操作は元に戻せないよ。新しいたまごから育て直すことになる。</p><button class="g11danger" id="g11resetgo">本当に育て直す</button><button class="g11cancel" id="g11resetcancel">やめる</button>`;const c=$('g11resetcancel');if(c)c.onclick=()=>{$('g11resetmodal').hidden=true};const n=$('g11resetnext');if(n)n.onclick=()=>resetAsk(2);const g=$('g11resetgo');if(g)g.onclick=async()=>{await del();S=fresh();await save();$('g11resetmodal').hidden=true;render()}}
function wire(){$('g11care').onclick=e=>{const b=e.target.closest('[data-a],[data-e]');if(b)b.dataset.a?act(b.dataset.a):egg(b.dataset.e)};$('g11teach').onclick=teachOpen;$('g11tw').onclick=async e=>{const b=e.target.closest('[data-w]');if(!b)return;const w=b.dataset.w;S.learned[w]=(S.learned[w]||0)+1;S.traits.weird+=1.1;S.totalCare++;S.growthXP+=5;S.lastSpeech=maybeCatch(`${w}。……${w}。`);$('g11wordmodal').hidden=true;await save();render();fx('teach')};$('g11wclose').onclick=()=>{$('g11wordmodal').hidden=true};$('g11restart').onclick=()=>resetAsk(1);$('g11back').onclick=()=>{const b=new Blob([JSON.stringify({app:'warera-grow',version:11,state:S},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`warera-grow-${V}-${G}.json`;a.click()};$('g11s').onclick=()=>document.getElementById('shareBtn')?.click()}
async function boot(){V=getV();G=V==='み'?'も':'み';S=await load();migrate();mount();render()}
setTimeout(boot,0);let seen=V;setInterval(async()=>{const v=getV();if(v!==seen){seen=v;document.getElementById('g11')?.remove();await boot()}else if(S)render()},60000);
})();