(()=>{
if(!/\/grow\/?$/.test(location.pathname))return;
const PREFIX='warera_grow_v1_',DB='warera-grow',STORE='pets';
const viewer=()=>{try{return localStorage.getItem('warera_chat_perspective')==='も'?'も':'み'}catch(e){return'み'}};
const key=()=>{const v=viewer(),t=v==='み'?'も':'み';return`${PREFIX}${v}_${t}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'null')}catch(e){return null}};
const writeLocal=s=>{try{localStorage.setItem(key(),JSON.stringify(s))}catch(e){}};
function putDb(s){return new Promise(resolve=>{try{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};r.onerror=()=>resolve();r.onsuccess=()=>{const db=r.result;try{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(s);q.onsuccess=q.onerror=()=>{db.close();resolve()}}catch(e){db.close();resolve()}}}catch(e){resolve()}})}
const traitMeta={affection:['💗','甘やかされ気味'],playful:['🎮','ちょっかい慣れ'],food:['🍙','ごはん好き'],routine:['🛏️','よく寝かされる'],weird:['🌀','われわれ語多め'],independent:['🌱','ひとりでも平気'],night:['🌙','夜ふかし育ち']};
const needMeta={hunger:['🍚','おなか','ごはん'],sleep:['💤','ねむさ','ねかせる'],mood:['🎲','ひま','あそぶ'],bond:['💗','かまって','なでる・ぎゅ'],clean:['🫧','よごれ','おふろ']};
const buttonNames={feed:'ごはんをあげる',snack:'おやつをあげる',sleep:'ねかせる',wash:'おふろに入れる',teach:'ことばを教える'};
function css(){if(document.getElementById('growUxV5Style'))return;const s=document.createElement('style');s.id='growUxV5Style';s.textContent=`#speechNote{display:none!important}.need{padding:6px!important;border:1px solid #ddd;border-radius:8px;background:#fafafa}.need-care{display:block;margin-top:4px;color:#777;font-size:7px;line-height:1.2}.needs-help{margin:0 0 9px;color:#777;font-size:8px;line-height:1.45}.trait-summary{margin:0 0 10px;padding:8px 9px;border-left:3px solid #111;background:#f7f7f7;font-size:10px;font-weight:700;line-height:1.55}.teach-help{margin:3px 0 8px;color:#777;font-size:8px;line-height:1.45}@media(max-width:580px){.needs{grid-template-columns:repeat(3,minmax(0,1fr))!important}.need-head{font-size:8px!important}}`;document.head.append(s)}
function stateView(s){if(!s?.needs)return null;const inv={};for(const k of Object.keys(needMeta))inv[k]=Math.max(0,Math.min(100,100-Number(s.needs[k]??80)));return inv}
function ensureNeedHelp(){const n=document.getElementById('needs');if(!n)return null;let p=document.getElementById('needsHelpV5');if(!p){p=document.createElement('p');p.id='needsHelpV5';p.className='needs-help';n.insertAdjacentElement('afterend',p)}return p}
function renderNeeds(){const n=document.getElementById('needs'),s=read(),stage=document.getElementById('stageLabel')?.textContent?.trim();if(!n||!s)return;if(stage==='たまご'){n.style.display='none';const h=ensureNeedHelp();if(h)h.textContent='孵化すると、おなか・ねむさ・ひま・かまって・よごれが出てくるよ。';return}n.style.display='grid';const v=stateView(s);n.replaceChildren();for(const [k,[icon,label,care]] of Object.entries(needMeta)){const x=Math.round(v[k]),d=document.createElement('div');d.className='need';d.innerHTML=`<div class="need-head"><span>${icon} ${label}</span><span>${x}</span></div><div class="meter"><i style="width:${x}%"></i></div><small class="need-care">${x>=52?'→ '+care:'まだ平気'}</small>`;n.append(d)}const h=ensureNeedHelp();if(h)h.textContent='バーが伸びたら、そのお世話どき。お世話するとちゃんと下がるよ。'}
function rewriteStateLabel(){const el=document.getElementById('stateLabel'),s=read();if(!el||!s||document.getElementById('stageLabel')?.textContent.trim()==='たまご')return;const v=stateView(s),[k,x]=Object.entries(v).sort((a,b)=>b[1]-a[1])[0];if(x<52){el.textContent='おけけ。通常運転';return}const mild={hunger:'🍚 おなかすいた',sleep:'💤 ねむそう',mood:'🎲 ひまそう',bond:'💗 かまってほしそう',clean:'🫧 そろそろおふろ'},hard={hunger:'🍚 かなりおなかすいた',sleep:'💤 かなりねむい',mood:'🎲 ひまが限界',bond:'💗 だいぶかまってほしい',clean:'🫧 だいぶよごれてる'};el.textContent=(x>=76?hard:mild)[k]}
function rewriteActions(){document.querySelectorAll('#actionGrid [data-action]').forEach(b=>{const a=b.dataset.action,n=buttonNames[a];if(!n)return;const l=b.querySelector('.label');if(l)l.textContent=n});const h=document.getElementById('actionHint');if(h)h.textContent=document.getElementById('stageLabel')?.textContent.trim()==='たまご'?'たまごの時だけのお世話だよ':'いまの様子で、できるお世話が少し変わるよ'}
function teachHelp(){const p=document.getElementById('teachPanel');if(!p)return;const b=p.querySelector('b');if(b)b.textContent='ことばを1つ教える';let h=p.querySelector('.teach-help');if(!h){h=document.createElement('p');h.className='teach-help';b?.insertAdjacentElement('afterend',h)}h.textContent='ログに出てくることばから選ぶよ。覚えるほど、返事や口ぐせに混ざりやすくなる。'}
function learnedWord(s){const a=Object.entries(s?.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);if(!a.length)return'';const pool=[];for(const [w,n] of a)for(let i=0;i<Math.min(4,n);i++)pool.push(w);return pool[(Number(s.totalCare||0)+pool.length)%pool.length]||a[0][0]}
async function mixLearned(action){if(action==='teach')return;await new Promise(r=>setTimeout(r,70));const s=read(),w=learnedWord(s),sp=document.getElementById('speech');if(!s||!w||!sp)return;if((Number(s.totalCare||0)+action.length)%4>1)return;const base=sp.firstChild?.nodeValue?.trim()||sp.textContent.trim();if(!base||base.includes(w))return;const text=(Number(s.totalCare||0)%2?`${w}。${base}`:`${base} ${w}`);sp.firstChild?sp.firstChild.nodeValue=text:sp.textContent=text;s.lastSpeech=text;writeLocal(s);await putDb(s)}
function personality(){const panels=[...document.querySelectorAll('.mini-panel')],p=panels.find(x=>x.querySelector('h2')?.textContent.trim()==='この個体のらしさ');const s=read();if(!p||!s)return;let sum=p.querySelector('.trait-summary');if(!sum){sum=document.createElement('p');sum.className='trait-summary';p.querySelector('h2')?.insertAdjacentElement('afterend',sum)}const groups=p.querySelectorAll('.trait-group');if(groups[0]?.querySelector('b'))groups[0].querySelector('b').textContent='本人っぽさ';if(groups[1]?.querySelector('b'))groups[1].querySelector('b').textContent='育て方のクセ';const innate=[...p.querySelectorAll('#innateTags .trait-tag')].map(x=>x.textContent.replace(/^\S+\s*/,'' )).slice(0,2);const ranked=Object.entries(s.traits||{}).sort((a,b)=>Number(b[1])-Number(a[1])).filter(([,v])=>Number(v)>1);const grow=ranked[0]?traitMeta[ranked[0][0]]?.[1]:'まだ育て方のクセなし';sum.textContent=`本人っぽさは「${innate.join('・')||'まだ不明'}」寄り。いまの育て方では「${grow}」がいちばん濃い。`;const box=document.getElementById('traitTags');if(box){box.replaceChildren();if(!ranked.length){const t=document.createElement('span');t.className='trait-tag';t.textContent='まだ育て方のクセは薄い';box.append(t)}for(const [k,v] of ranked.slice(0,4)){const m=traitMeta[k];if(!m)continue;const t=document.createElement('span');t.className='trait-tag';const level=v>=14?'かなり':v>=7?'強め':'少し';t.textContent=`${m[0]} ${m[1]}・${level}`;box.append(t)}}const l=document.getElementById('learnedLine'),learned=Object.entries(s.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).slice(0,5);if(l)l.textContent=learned.length?`覚えたことば：${learned.map(([w,n])=>`${w}×${n}`).join(' / ')}。返事や口ぐせに出やすくなる。`:'まだことばは覚えてない。教えたことばは、返事や口ぐせに混ざっていくよ。'}
function removeGrowthLog(){document.querySelectorAll('.mini-panel h2').forEach(h=>{if(h.textContent.trim()==='成長記録')h.closest('.mini-panel')?.remove()})}
function textCleanup(){document.querySelectorAll('.grow-shell *').forEach(el=>{if(el.children.length===0&&el.textContent.includes('ごあん'))el.textContent=el.textContent.replaceAll('ごあん','ごはん')})}
async function migrateEggOnce(){const s=read();if(!s||Number(s.totalCare||0)<9||document.getElementById('stageLabel')?.textContent.trim()!=='たまご'||sessionStorage.getItem('growEggMigratedV5'))return;sessionStorage.setItem('growEggMigratedV5','1');s.growthXP=Math.max(70,Number(s.growthXP||0));if(!s.born){const d=new Date();d.setDate(d.getDate()-1);s.born=d.toISOString().slice(0,10)}else{const d=new Date(s.born+'T12:00:00');if((Date.now()-d.getTime())<86400000){d.setDate(d.getDate()-1);s.born=d.toISOString().slice(0,10)}}writeLocal(s);await putDb(s);location.reload()}
let scheduled=false;function tidy(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;css();removeGrowthLog();renderNeeds();rewriteStateLabel();rewriteActions();teachHelp();personality();textCleanup();migrateEggOnce()},0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tidy,{once:true});else tidy();new MutationObserver(tidy).observe(document.documentElement,{childList:true,subtree:true,characterData:true});document.addEventListener('click',e=>{const b=e.target.closest('#actionGrid [data-action]');if(b)mixLearned(b.dataset.action)},true);setInterval(tidy,1500);
})();