(()=>{
if(!/\/grow\/?$/.test(location.pathname))return;
const P='warera_grow_v1_',N={み:'みちゃこ',も:'もっち'};
const TRAITS=['affection','playful','food','routine','weird','independent','night'];
const TM={affection:'甘やかされ育ち',playful:'あそび好き',food:'ごはん好き',routine:'生活しっかり',weird:'われわれ語多め',independent:'ひとりでも平気',night:'夜ふかし育ち'};
const WORDS=['われわれ','しょもしょも','おけけ','オフトゥン','てぇてぇ','はすはす','ガラスープ','かわいい','好き','ねむい','ごはん','だん！'];
const CSS=`
#g8{width:min(1120px,calc(100vw - 32px));max-width:none;position:relative;left:50%;transform:translateX(-50%);margin:0 auto;color:#111}
.g8w{background:transparent}.g8top{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px;padding:12px 14px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:4px 4px 0 rgba(0,0,0,.35)}
.g8id{display:flex;gap:10px;align-items:center}.g8logo{display:grid;place-items:center;width:44px;height:44px;flex:0 0 44px;border:1px solid #111;border-radius:50%;background:#f1f1f1;font-size:22px}.g8title b{font-size:20px;font-weight:800;letter-spacing:-.02em}.g8title span{display:block;margin-top:2px;color:#666;font-size:10px}.g8meta{display:flex;gap:7px;align-items:center}.g8chip,.g8share{min-height:36px;padding:0 10px;border:1px solid #111;border-radius:10px;background:#fff;color:#222;font:700 10px 'Noto Sans JP',sans-serif;box-shadow:2px 2px 0 rgba(0,0,0,.25)}
.g8body{padding:0}.g8grid{display:grid;grid-template-columns:minmax(0,2.25fr) minmax(270px,.75fr);gap:14px;align-items:start}.g8left,.g8card{border:1px solid #111;border-radius:10px;background:#fff;box-shadow:4px 4px 0 rgba(0,0,0,.32)}.g8left{min-width:0;padding:16px}.g8left-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.g8name{font-size:25px;font-weight:800;letter-spacing:-.03em}.g8stage{padding:5px 8px;border:1px solid #111;border-radius:999px;background:#fff;font-size:9px;font-weight:800}
.g8room{position:relative;min-height:390px;margin:13px 0 12px;overflow:hidden;border:1px solid #111;border-radius:10px;background:linear-gradient(#f7dfe6 0 55%,#e7c29a 55%);box-shadow:2px 2px 0 rgba(0,0,0,.15)}#g8[data-target="み"] .g8room{background:linear-gradient(#f7e6ed 0 55%,#ead2b6 55%)}#g8[data-target="も"] .g8room{background:linear-gradient(#e7f2fa 0 55%,#ead2b6 55%)}.g8room.night{filter:saturate(.72) brightness(.78)}
.g8window{position:absolute;left:6%;top:8%;width:34%;height:34%;border:5px solid #111;border-radius:8px;background:#a7dcff}.night .g8window{background:#596582}.g8window:before,.g8window:after{content:'';position:absolute;background:#111}.g8window:before{left:50%;top:0;bottom:0;width:3px}.g8window:after{left:0;right:0;top:50%;height:3px}.g8bed{position:absolute;left:5%;bottom:12%;width:31%;height:16%;border:2px solid #111;border-radius:45% 45% 18% 18%;background:#f6bfc9}.g8shelf{position:absolute;right:5%;bottom:14%;width:22%;height:31%;border:3px solid #111;background:#d7a173}.g8rug{position:absolute;left:25%;right:22%;bottom:5%;height:18%;border:1px solid #111;border-radius:50%;background:repeating-linear-gradient(45deg,#f8eeee 0 16px,#f0d7dc 16px 32px)}
.g8note{position:absolute;right:4%;top:5%;z-index:5;max-width:210px;padding:8px 10px;border:1px solid #111;border-radius:8px;background:#fff;transform:rotate(-2deg);font-size:10px;font-weight:800;line-height:1.45;box-shadow:2px 2px 0 rgba(0,0,0,.2)}.g8speech{position:absolute;left:50%;bottom:61%;z-index:8;max-width:290px;transform:translateX(-50%);padding:8px 11px;border:1px solid #111;border-radius:10px;background:#fff;font-size:11px;font-weight:800;text-align:center;box-shadow:2px 2px 0 rgba(0,0,0,.2)}
.g8petbox{position:absolute;left:50%;bottom:9%;z-index:6;transform:translateX(-50%) scale(1.12)}.g8pet{--p:#ffe7a2;--d:#111;position:relative;width:150px;height:170px}.g8pet[data-t="み"]{--p:#f7d6e2}.g8pet[data-t="も"]{--p:#dbeefa}.g8bodyp{position:absolute;left:50%;bottom:12px;width:136px;height:128px;transform:translateX(-50%);border:3px solid var(--d);border-radius:46%;background:var(--p)}.g8ear{position:absolute;top:17px;width:47px;height:58px;border:3px solid var(--d);background:var(--p)}.g8ear.l{left:18px;border-radius:65% 25% 20% 40%;transform:rotate(-14deg)}.g8ear.r{right:18px;border-radius:25% 65% 40% 20%;transform:rotate(14deg)}.g8eyes{position:absolute;left:50%;top:47%;z-index:3;display:flex;gap:42px;transform:translateX(-50%)}.g8eyes i{width:16px;height:21px;border-radius:45%;background:#111}.g8mouth{position:absolute;left:50%;top:58%;z-index:3;width:25px;height:10px;transform:translateX(-50%);border-bottom:3px solid #111;border-radius:0 0 55% 55%}.egg .g8ear,.egg .g8eyes,.egg .g8mouth{display:none}.egg .g8bodyp{height:158px;border-radius:50% 50% 44% 44%/58% 58% 42% 42%;background:linear-gradient(135deg,#fff,var(--p))}.g8poop{position:absolute;bottom:14%;z-index:7;font-size:23px}.p1{left:31%}.p2{right:28%}
.g8care-wrap{margin:0 0 14px;padding:12px;border:1px solid #111;border-radius:10px;background:#f8f8f8}.g8care-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.g8care-title b{font-size:12px}.g8care-title span{color:#777;font-size:9px}.g8care{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.g8care button{position:relative;min-height:90px;padding:9px 5px;border:1px solid #111;border-radius:10px;background:#fff;cursor:pointer;box-shadow:2px 2px 0 rgba(0,0,0,.2)}.g8care button:hover{transform:translate(1px,1px);box-shadow:1px 1px 0 rgba(0,0,0,.2)}.g8care button.rec{background:#111;color:#fff}.g8care em{position:absolute;right:5px;top:5px;padding:2px 5px;border-radius:999px;background:#fff;color:#111;font:800 7px sans-serif}.g8care i{display:block;font-style:normal;font-size:27px}.g8care b{display:block;margin-top:5px;font-size:11px}.g8care small{display:block;margin-top:3px;color:#777;font-size:7px;line-height:1.35}.g8care button.rec small{color:#ddd}
.g8ident{padding:9px 10px;border:1px solid #111;border-radius:9px;background:#fff;font-size:10px;font-weight:700;line-height:1.55}.g8st{display:grid;gap:10px;margin-top:12px}.g8r{display:grid;grid-template-columns:82px 1fr 76px;align-items:center;gap:8px}.g8r b{font-size:10px}.g8bar{height:13px;border:1px solid #111;border-radius:999px;background:#fff;overflow:hidden}.g8bar i{display:block;height:100%;border-radius:999px}.good i{background:#8fcf9e}.mid i{background:#e3c86f}.low i{background:#e7a09a}.g8r span{color:#666;font-size:8px;font-weight:700;text-align:right}
.g8right{display:grid;gap:12px;align-content:start}.g8card{padding:14px}.g8h{display:flex;justify-content:space-between;align-items:center;margin:0 0 9px;font-size:14px;font-weight:800}.g8h small{color:#777;font-size:8px}.g8n{display:grid;grid-template-columns:28px 1fr;gap:8px;align-items:start;padding:8px 0;border-bottom:1px solid #e4e4e4}.g8n:last-child{border-bottom:0}.g8n i{font-style:normal;font-size:18px}.g8n b{display:block;font-size:10px}.g8n span{display:block;margin-top:2px;color:#777;font-size:8px;line-height:1.45}.g8empty{padding:8px 0;color:#777;font-size:9px;line-height:1.55}
.g8words{display:flex;flex-wrap:wrap;gap:6px}.g8word{padding:5px 7px;border:1px solid #111;border-radius:999px;background:#fff;font-size:8px;font-weight:800}.g8word.habit{background:#111;color:#fff}.g8word small{font-size:7px;opacity:.75}.g8word-help{margin:0 0 8px;color:#666;font-size:8px;line-height:1.55}.g8add{width:100%;margin-top:8px;padding:8px;border:1px dashed #777;border-radius:8px;background:#fff;font:800 9px 'Noto Sans JP',sans-serif}.g8memo{display:grid;gap:7px}.g8memo-row{display:flex;justify-content:space-between;gap:8px;padding:5px 0;border-bottom:1px solid #eee;font-size:9px}.g8memo-row:last-child{border-bottom:0}.g8memo-row span{color:#777}.g8memo-row b{text-align:right}.g8tools{display:flex;gap:7px;margin-top:10px}.g8tools button{flex:1;padding:7px 8px;border:1px solid #111;border-radius:8px;background:#fff;font:700 8px 'Noto Sans JP',sans-serif}.g8tools .danger{color:#8a3333}
.g8modal{position:fixed;inset:0;z-index:160;display:grid;place-items:center;padding:20px;background:rgba(244,244,244,.9)}.g8modal[hidden]{display:none}.g8dlg{width:min(100%,380px);padding:18px;border:1px solid #111;border-radius:10px;background:#fff;box-shadow:4px 4px 0 rgba(0,0,0,.35)}.g8dlg h2{margin:0 0 7px;font-size:20px}.g8dlg p{margin:0 0 12px;color:#666;font-size:11px;line-height:1.65}.g8twords{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.g8twords button,.g8dlg-actions button{padding:9px;border:1px solid #111;border-radius:8px;background:#fff;font-weight:800}.g8dlg-actions{display:grid;gap:7px;margin-top:10px}.g8dlg-actions .primary{background:#111;color:#fff}.g8dlg-actions .danger{background:#8a3333;color:#fff;border-color:#8a3333}
@media(max-width:900px){.g8grid{grid-template-columns:minmax(0,1.8fr) minmax(250px,.8fr)}.g8care{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:720px){#g8{width:min(100% - 24px,680px)}.g8top{padding:10px}.g8title span,.clock{display:none}.g8meta{gap:4px}.g8chip,.g8share{padding:0 7px;min-height:33px;font-size:8px}.g8grid{display:flex;flex-direction:column}.g8left{order:1;width:100%;padding:11px}.g8room{min-height:330px;margin-bottom:8px}.g8petbox{transform:translateX(-50%) scale(.92)}.g8speech{bottom:61%;max-width:230px}.g8care-wrap{margin:0 0 11px;padding:9px}.g8care{grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.g8care button{min-height:82px;padding:7px 4px}.g8care i{font-size:24px}.g8care b{font-size:10px}.g8right{order:2;width:100%}.g8r{grid-template-columns:72px 1fr 64px}.g8twords{grid-template-columns:repeat(2,1fr)}}`;
let V=getV(),G=V==='み'?'も':'み',S;
function getV(){try{return localStorage.getItem('warera_chat_perspective')==='も'?'も':'み'}catch(e){return'み'}}
const K=()=>`${P}${V}_${G}`,clamp=v=>Math.max(0,Math.min(100,Number(v)||0)),now=()=>Date.now();
function read(){try{return JSON.parse(localStorage.getItem(K())||'null')}catch(e){return null}}
function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open('warera-grow',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('pets'))db.createObjectStore('pets',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}
function syncDb(){openDb().then(db=>{const q=db.transaction('pets','readwrite').objectStore('pets').put(S);q.onsuccess=q.onerror=()=>db.close()}).catch(()=>{})}
async function deleteDbKey(){try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction('pets','readwrite').objectStore('pets').delete(K());q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch(e){}}
function init(){S=read()||{born:new Date().toISOString().slice(0,10),totalCare:0,growthXP:0,traits:{},needs:{hunger:84,sleep:85,mood:80,bond:76,clean:92},learned:{},lastSpeech:'……おけけ？',lastTick:now(),poop:0,toiletMeter:0,careMisses:0,criticalFlags:{}};S.version=9;S.traits=S.traits||{};TRAITS.forEach(k=>S.traits[k]=Number(S.traits[k]||0));S.needs=S.needs||{};for(const[k,v]of Object.entries({hunger:84,sleep:85,mood:80,bond:76,clean:92}))S.needs[k]=clamp(S.needs[k]??v);S.learned=S.learned||{};S.totalCare=Number(S.totalCare||0);S.growthXP=Math.max(Number(S.growthXP||0),Math.min(760,S.totalCare*4));S.poop=Number(S.poop||0);S.toiletMeter=Number(S.toiletMeter||0);S.careMisses=Number(S.careMisses||0);S.criticalFlags=S.criticalFlags||{};S.lastTick=Number(S.lastTick||now());save()}
function save(){S.id=K();S.viewer=V;S.target=G;S.updatedAt=now();try{localStorage.setItem(K(),JSON.stringify(S))}catch(e){}syncDb()}
function stage(){return S.growthXP>=820?['adult','おとな']:S.growthXP>=320?['child','こども']:S.growthXP>=80?['baby','あかちゃん']:['egg','たまご']}
function lv(){return{hunger:clamp(S.needs.hunger),sleep:clamp(S.needs.sleep),mood:clamp((S.needs.mood+S.needs.bond)/2),clean:clamp(S.needs.clean)}}
function updateMisses(){if(stage()[0]==='egg')return;const L=lv();for(const[k,v]of Object.entries(L)){if(v<18&&!S.criticalFlags[k]){S.criticalFlags[k]=1;S.careMisses++}else if(v>48){S.criticalFlags[k]=0}}}
function decay(){const h=Math.min(72,Math.max(0,(now()-S.lastTick)/36e5));if(h<.02)return;S.needs.hunger=clamp(S.needs.hunger-h*2.5);S.needs.sleep=clamp(S.needs.sleep-h*1.7);S.needs.mood=clamp(S.needs.mood-h*.95);S.needs.bond=clamp(S.needs.bond-h*.35);S.needs.clean=clamp(S.needs.clean-h*.5);S.toiletMeter+=h*2.2;while(S.toiletMeter>=100&&S.poop<2){S.toiletMeter-=100;S.poop++;S.needs.clean=clamp(S.needs.clean-15)}S.lastTick=now();updateMisses()}
function w(k,v){const a={hunger:['ぺこぺこ','おなかすいた','まだ平気','おなかいっぱい'],sleep:['かなりねむい','ねむそう','まだ平気','元気いっぱい'],mood:['ごきげんななめ','ちょい退屈','まあまあ','ごきげん'],clean:['よごれてる','そろそろおふろ','まだきれい','ぴかぴか']};return a[k][v<25?0:v<50?1:v<75?2:3]}
function need(){if(S.poop>0)return['toilet','🚽','トイレしたみたい'];const L=lv(),[k,v]=Object.entries(L).sort((a,b)=>a[1]-b[1])[0];if(v>=58)return['fine','○','いまは落ち着いてる'];const a={hunger:['🍚','おなかすいてる'],sleep:['🌙','ねむそう'],mood:['🎮','あそびたそう'],clean:['🫧','そろそろおふろ']};return[k,a[k][0],a[k][1]]}
function pet(){return`<div class="g8pet"><i class="g8ear l"></i><i class="g8ear r"></i><i class="g8bodyp"></i><span class="g8eyes"><i></i><i></i></span><i class="g8mouth"></i></div>`}
function strongestTrait(){return TRAITS.slice().sort((a,b)=>(S.traits[b]||0)-(S.traits[a]||0))[0]||'affection'}
function nextGrowth(){const x=S.growthXP;if(x<80)return`${Math.max(0,80-x)}ptで孵化`;if(x<320)return`${Math.max(0,320-x)}ptでこども`;if(x<820)return`${Math.max(0,820-x)}ptでおとな`;return'おとなになった'}
function habitWord(){return Object.entries(S.learned||{}).filter(([,n])=>n>=3).sort((a,b)=>b[1]-a[1])[0]?.[0]||''}
function mixLearned(base){const a=Object.entries(S.learned||{}).filter(([,n])=>n>0);if(!a.length)return base;const total=a.reduce((s,[,n])=>s+Math.min(5,n),0),chance=a.some(([,n])=>n>=3)?.58:.28;if(Math.random()>chance)return base;let r=Math.random()*total,word=a[0][0];for(const[w,n]of a){r-=Math.min(5,n);if(r<=0){word=w;break}}return Math.random()<.35?`${word}。`: `${base} ${word}。`}
function mount(){document.querySelector('.grow-shell')?.setAttribute('style','display:none!important');if(document.getElementById('g8'))return;const st=document.createElement('style');st.textContent=CSS;document.head.append(st);const x=document.createElement('div');x.id='g8';x.innerHTML=`<section class="g8w"><div class="g8top"><div class="g8id"><div class="g8logo">🥚</div><div class="g8title"><b>われわれ育成所</b><span>相手を、勝手に育てる。</span></div></div><div class="g8meta"><span class="g8chip" id="g8v"></span><span class="g8chip clock" id="g8c"></span><button class="g8share" id="g8s">画像にする</button></div></div><div class="g8body"><div class="g8grid"><section class="g8left"><div class="g8left-head"><div class="g8name" id="g8n"></div><span class="g8stage" id="g8stage"></span></div><div class="g8room" id="g8room"><div class="g8window"></div><div class="g8bed"></div><div class="g8shelf"></div><div class="g8rug"></div><div class="g8note" id="g8note"></div><div class="g8speech" id="g8speech"></div><span class="g8poop p1" id="g8p1" hidden>💩</span><span class="g8poop p2" id="g8p2" hidden>💩</span><div class="g8petbox" id="g8pet">${pet()}</div></div><div class="g8care-wrap"><div class="g8care-title"><b>お世話する</b><span id="g8careHint"></span></div><div class="g8care" id="g8care"></div></div><p class="g8ident" id="g8ident"></p><div id="g8status"></div></section><aside class="g8right"><section class="g8card"><h2 class="g8h">いまのようす <small>お世話の目安</small></h2><div id="g8notices"></div></section><section class="g8card"><h2 class="g8h">おぼえたことば <small id="g8wc"></small></h2><p class="g8word-help">3回教えると「くちぐせ」。お世話したときの返事に混ざりやすくなる。</p><div class="g8words" id="g8words"></div><button class="g8add" id="g8teach">＋ ことばを教える</button></section><section class="g8card"><h2 class="g8h">育ちメモ <small>この個体</small></h2><div class="g8memo" id="g8memo"></div><div class="g8tools"><button id="g8back">バックアップ</button><button class="danger" id="g8reset">育て直す</button></div></section></aside></div></div></section><div class="g8modal" id="g8modal" hidden><div class="g8dlg" id="g8dlg"></div></div>`;document.querySelector('.conversation-shell')?.append(x);wire()}
function dom(id){return document.getElementById(id)}
function renderPet(){for(const p of dom('g8pet').querySelectorAll('.g8pet')){p.dataset.t=G;p.classList.toggle('egg',stage()[0]==='egg')}}
function render(){decay();const d=new Date(),L=lv(),ST=stage(),Q=need(),age=Math.max(0,Math.floor((new Date()-new Date((S.born||new Date().toISOString().slice(0,10))+'T00:00:00'))/864e5));dom('g8').dataset.target=G;dom('g8v').textContent=`表示：${V}目線`;dom('g8c').textContent=`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;dom('g8room').classList.toggle('night',d.getHours()<6||d.getHours()>=18);dom('g8n').textContent=N[G];dom('g8stage').textContent=`${age}日目・${ST[1]}`;const tr=strongestTrait();dom('g8ident').textContent=`${N[G]}成分 × ${N[V]}育ち。いまは「${TM[tr]}」がいちばん濃い。`;if(ST[0]==='egg'){const p=Math.min(5,Math.ceil(S.growthXP/16));dom('g8status').innerHTML=`<div class="g8st"><b>たまごのようす</b><div>${'●'.repeat(p)}${'○'.repeat(5-p)}</div><small>${S.growthXP<28?'まだ静か。':S.growthXP<58?'たまにコトコトする。':'そろそろ出てきそう。'}</small></div>`}else dom('g8status').innerHTML=`<div class="g8st">${Object.entries({hunger:['🍚','満腹'],sleep:['🌙','元気'],mood:['✨','ごきげん'],clean:['🫧','きれい']}).map(([k,m])=>{const v=Math.round(L[k]),c=v<35?'low':v<70?'mid':'good';return`<div class="g8r ${c}"><b>${m[0]} ${m[1]}</b><div class="g8bar"><i style="width:${v}%"></i></div><span>${w(k,v)}</span></div>`}).join('')}</div>`;dom('g8note').innerHTML=`いまのようす<br>${Q[1]} ${Q[2]}`;dom('g8speech').textContent=S.lastSpeech||'おけけ。';dom('g8p1').hidden=S.poop<1;dom('g8p2').hidden=S.poop<2;renderPet();notices(ST,L);learned();memo();care(ST,Q);save()}
function notices(ST,L){const a=[];if(ST[0]==='egg'){a.push(['🥚',S.growthXP>=58?'そろそろ生まれそう':'たまにコトコトする','今はたまご用のお世話だけできる'])}else{if(S.poop>0)a.push(['🚽','トイレしたみたい','トイレで片づける']);if(L.hunger<55)a.push(['🍚',w('hunger',L.hunger),'ごはんをあげる']);if(L.sleep<55)a.push(['🌙',w('sleep',L.sleep),'ねかせる']);if(L.mood<55)a.push(['✨',w('mood',L.mood),'あそぶ・なでる']);if(L.clean<55)a.push(['🫧',w('clean',L.clean),'おふろに入れる']);if(!a.length)a.push(['○','いまは落ち着いてる','急いでお世話しなくても大丈夫そう'])}dom('g8notices').innerHTML=a.slice(0,4).map(x=>`<div class="g8n"><i>${x[0]}</i><div><b>${x[1]}</b><span>${x[2]}</span></div></div>`).join('')}
function learned(){const a=Object.entries(S.learned||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);dom('g8wc').textContent=`${a.length}こ`;dom('g8words').innerHTML=a.length?a.slice(0,10).map(([word,n])=>`<span class="g8word ${n>=3?'habit':''}">${word} <small>${n>=3?'くちぐせ':`${n}/3`}</small></span>`).join(''):'<div class="g8empty">まだ覚えてない。教えると返事に少しずつ混ざるようになる。</div>';dom('g8teach').style.display=stage()[0]==='egg'?'none':'block'}
function memo(){const tr=strongestTrait(),hw=habitWord();dom('g8memo').innerHTML=`<div class="g8memo-row"><span>お世話した</span><b>${S.totalCare}回</b></div><div class="g8memo-row"><span>育ち方</span><b>${TM[tr]}</b></div><div class="g8memo-row"><span>くちぐせ</span><b>${hw||'まだなし'}</b></div><div class="g8memo-row"><span>お世話ミス</span><b>${S.careMisses}回</b></div><div class="g8memo-row"><span>次の成長</span><b>${nextGrowth()}</b></div>`}
function care(ST,Q){dom('g8careHint').textContent=ST[0]==='egg'?'たまごの時だけのお世話':Q[0]==='fine'?'いまは好きにかまってよし':'必要なお世話を黒で表示';if(ST[0]==='egg'){const d={warm:['🫶','あたためる','ぬくぬくする'],call:['📣','名前を呼ぶ',`${N[G]}って呼ぶ`],tap:['👉','コツコツ','そっとノック'],hum:['🎵','うたう','適当に歌う'],listen:['👂','ようすを見る','中をうかがう'],word:['🌀','われわれ語','聞かせておく']};dom('g8care').innerHTML=Object.entries(d).map(([k,v])=>`<button data-e="${k}"><i>${v[0]}</i><b>${v[1]}</b><small>${v[2]}</small></button>`).join('');return}const d={feed:['🍴','ごはん','満腹を回復'],bath:['🛁','おふろ','きれいを回復'],toilet:['🚽','トイレ','出たら片づける'],play:['🎮','あそぶ','ごきげんUP'],pat:['💗','なでる','ちょっと甘やかす'],sleep:['🌙','ねる','元気を回復']},r={hunger:'feed',sleep:'sleep',mood:'play',clean:'bath',toilet:'toilet'}[Q[0]];dom('g8care').innerHTML=Object.entries(d).map(([k,v])=>`<button class="${r===k?'rec':''}" data-a="${k}">${r===k?'<em>いま</em>':''}<i>${v[0]}</i><b>${v[1]}</b><small>${v[2]}</small></button>`).join('')}
function react(a,word=''){if(stage()[0]==='egg')return({warm:'……ぬく。',call:`……${N[G]}？`,tap:'……コト。',hum:'……ふんふん。',listen:'……おけけ。',word:'……われわれ……？'}[a]||'……');const map={feed:['ごはん、だん！','おけけ。これは食べる。'],bath:['カラダ・アラウ。','ぴかぴか、だん！'],toilet:S.poop?['でた。見なかったことにして。']:['まだでない。'],play:['しょもしょもしようず。','もっかい。'],pat:['はすはすされてる。','てぇてぇ判定。'],sleep:['オフトゥンいく。','ねう。'],teach:[`${word}。……${word}。`]};const base=(map[a]||['おけけ。'])[S.totalCare%(map[a]||['x']).length];return a==='teach'?base:mixLearned(base)}
function actionEffect(a){const L=lv(),needMap={feed:['hunger',L.hunger],sleep:['sleep',L.sleep],play:['mood',L.mood],pat:['mood',L.mood],bath:['clean',L.clean],toilet:['toilet',S.poop?0:100]},pair=needMap[a]||['x',60],needed=pair[1]<55||a==='toilet'&&S.poop>0,tooMuch=pair[1]>90&&a!=='toilet',same=S.lastAction===a;let xp=needed?8:4;if(tooMuch)xp=1;if(same)xp=Math.max(1,Math.round(xp*.45));return xp}
function act(a){const n=S.needs,xp=actionEffect(a);if(a==='feed'){n.hunger+=30;n.mood+=3;S.toiletMeter+=36;S.traits.food+=1.4;if(n.hunger>96)n.mood-=3}if(a==='bath'){n.clean+=46;S.traits.routine+=.5}if(a==='toilet'){if(S.poop>0){S.poop=0;n.clean+=16}else{S.lastSpeech=react('toilet');render();return}}if(a==='play'){if(n.sleep<22){n.mood+=10;n.sleep-=4;S.lastSpeech='ねむいって。'}else{n.mood+=29;n.bond+=8;n.hunger-=7;n.sleep-=9;S.traits.playful+=1.6}}if(a==='pat'){n.bond+=24;n.mood+=13;S.traits.affection+=1.5}if(a==='sleep'){if(n.sleep>92){S.lastSpeech='まだねない。';render();return}n.sleep+=42;n.hunger-=5;n.mood+=3;S.traits.routine+=1.3}for(const k in n)n[k]=clamp(n[k]);S.totalCare++;S.growthXP+=xp;S.lastAction=a;if(!S.lastSpeech||a!=='play'||n.sleep>=22)S.lastSpeech=react(a);render()}
function egg(a){S.totalCare++;S.growthXP+=S.lastAction===a?4:8;if(['warm','call'].includes(a))S.traits.affection++;if(a==='tap')S.traits.playful+=.7;if(a==='word')S.traits.weird++;S.lastAction=a;S.lastSpeech=react(a);render()}
function showTeach(){const a=[0,2,4,6,8,10].map(i=>WORDS[(S.totalCare+i)%WORDS.length]);dom('g8dlg').innerHTML=`<h2>ことばを教える</h2><p>同じことばを3回教えると「くちぐせ」になって、返事にかなり混ざりやすくなる。</p><div class="g8twords">${a.map(w=>`<button data-w="${w}">${w}<br><small>${S.learned[w]||0}/3</small></button>`).join('')}</div><div class="g8dlg-actions"><button data-close>やめとく</button></div>`;dom('g8modal').hidden=false}
function showReset(step=1){if(step===1)dom('g8dlg').innerHTML=`<h2>${N[G]}とお別れする？</h2><p>この端末で育てた${N[G]}をリセットして、たまごから育て直せるよ。今の育ち方・覚えたことば・お世話回数は消える。</p><div class="g8dlg-actions"><button data-close>まだ一緒にいる</button><button class="danger" data-reset-next>お別れする</button></div>`;else dom('g8dlg').innerHTML=`<h2>本当にお別れする？</h2><p>この操作は元に戻せないよ。残しておきたいなら、先にバックアップしてね。</p><div class="g8dlg-actions"><button data-close>やっぱりやめる</button><button class="danger" data-reset-final>本当にお別れする</button></div>`;dom('g8modal').hidden=false}
async function resetPet(){try{localStorage.removeItem(K())}catch(e){}await deleteDbKey();dom('g8modal').hidden=true;location.reload()}
function wire(){dom('g8care').onclick=e=>{const b=e.target.closest('[data-a],[data-e]');if(b)b.dataset.a?act(b.dataset.a):egg(b.dataset.e)};dom('g8teach').onclick=showTeach;dom('g8modal').onclick=e=>{const w=e.target.closest('[data-w]'),close=e.target.closest('[data-close]'),next=e.target.closest('[data-reset-next]'),final=e.target.closest('[data-reset-final]');if(w){const word=w.dataset.w;S.learned[word]=(S.learned[word]||0)+1;S.traits.weird+=.8;S.totalCare++;S.growthXP+=3;S.lastSpeech=react('teach',word);dom('g8modal').hidden=true;render()}else if(close||e.target===dom('g8modal'))dom('g8modal').hidden=true;else if(next)showReset(2);else if(final)resetPet()};dom('g8back').onclick=()=>{const b=new Blob([JSON.stringify({app:'warera-grow',version:9,state:S},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`warera-grow-${V}-${G}.json`;a.click()};dom('g8reset').onclick=()=>showReset(1);dom('g8s').onclick=()=>document.getElementById('shareBtn')?.click()}
function boot(){V=getV();G=V==='み'?'も':'み';init();mount();render()}
setTimeout(boot,0);let seen=V;setInterval(()=>{const v=getV();if(v!==seen){seen=v;location.reload()}else if(S)render()},60000);
})();