(async()=>{
wireLock('../');
const rows=await WareraData.memories('../');
const dateInput=document.getElementById('dateInput'),dateLabel=document.getElementById('dateLabel'),dateBtn=document.getElementById('dateBtn'),randomBtn=document.getElementById('randomBtn'),shareBrain=document.getElementById('shareBrain'),miHead=document.getElementById('miHead'),moHead=document.getElementById('moHead'),miBreak=document.getElementById('miBreak'),moBreak=document.getElementById('moBreak'),summary=document.getElementById('summary');
let currentDate='',currentMi=[],currentMo=[];
const themes=[
['かわいい',/かわい|可愛/g,'#ffd9e4'],['好き',/好き|すき|しゅき|大好き|だいすき/g,'#ffd9e4'],['会いたい',/会いた|あいたい|会いて/g,'#ffd9e4'],['さみしい',/寂し|さみし|さびし/g,'#eadcff'],['うれしい',/嬉|うれし|やった|最高|よかった|よかた/g,'#ffe6ad'],['かなしい',/悲|かなしい|泣|つら|へこ/g,'#dce8ff'],['怒り',/むかつ|ムカつ|腹立|怒|キレ/g,'#ffd8c7'],['笑い',/www|笑|草|わろ|ワロ/g,'#fff0b8'],['眠い',/眠|ねむ|寝たい|おやす|寝る|寝よ/g,'#e6dcff'],['起きた',/おはよ|起きた|起床|目覚/g,'#fff0b8'],['疲れ',/疲|つかれ|しんど|だる|限界/g,'#e5e5e5'],['仕事',/仕事|会社|会議|案件|残業|業務|出勤|退勤|勤務|職場/g,'#dce8ff'],['休み',/休み|休日|有休|休暇|休む/g,'#d8f1e3'],['帰る',/帰る|帰宅|かえる|退勤/g,'#d8f1e3'],['移動',/電車|駅|バス|歩い|移動|タクシー|新幹線/g,'#d8eef2'],['天気',/雨|晴れ|天気|暑い|寒い|湿気|台風/g,'#d8eef2'],['ごはん',/ごはん|ご飯|飯|食べ|たべ|お腹|おなか|腹減/g,'#ffe0b8'],['お菓子',/お菓子|チョコ|アイス|ケーキ|プリン|クッキー/g,'#ffe0cf'],['飲み物',/コーヒー|珈琲|お茶|水|ジュース|カフェラテ/g,'#d8eef2'],['お酒',/酒|ビール|ワイン|酔っ|飲み会/g,'#eadcff'],['ガラスープ',/ガラスープ|鶏ガラ/g,'#ffe0b8'],['風呂',/風呂|おふろ|シャワー|カラダ.?アラウ/g,'#d8eef2'],['通話',/通話|電話|でんわ|声聞|話したい/g,'#dce8ff'],['ゲーム',/ゲーム|パワプロ|育成|サクセス|Switch|PS5|プレステ/g,'#d8f1e3'],['動画',/YouTube|動画|ショート|TikTok|配信/g,'#ffd8c7'],['写真',/写真|画像|スクショ|撮った|撮影/g,'#ffe0cf'],['買い物',/買う|買った|買い物|ほしい|欲しい|届い|注文/g,'#ffe6ad'],['服',/服|コーデ|着る|着た|靴|バッグ/g,'#ffe0cf'],['美容',/髪|美容|ネイル|化粧|メイク|眉/g,'#ffd9e4'],['体調',/痛い|体調|頭痛|腹痛|熱|具合|病院|薬/g,'#e5e5e5'],['お金',/円|給料|給与|お金|高い|安い|値段|予算/g,'#ffe6ad'],['予定',/予定|明日|今日|あとで|何時|集合|予約/g,'#d8f1e3'],['誕生日',/誕生日|プレゼント|お祝い/g,'#ffd9e4'],['猫',/猫|ねこ|ニャ/g,'#ffe0b8'],['われわれ',/われわれ/g,'#e5e5e5'],['しょもしょも',/しょもしょも/g,'#e5e5e5'],['おけけ',/おけけ|おけおけおけけ/g,'#e5e5e5'],['オフトゥン',/オフトゥン/g,'#e6dcff'],['ちっち',/ちっち/g,'#e5e5e5'],['てぇてぇ',/てぇてぇ/g,'#ffd9e4'],['はすはす',/はすはす/g,'#ffd9e4'],['だん！',/だん[！!]/g,'#ffe6ad'],['ぱっちくん',/ぱっちくん/g,'#d8f1e3'],['ありがとう',/ありがと|サンキュ|感謝/g,'#ffd9e4'],['ごめん',/ごめん|すまん|申し訳/g,'#e5e5e5'],['待って',/待って|まって|待つ|待ち/g,'#ffe6ad'],['やだ',/やだ|嫌だ|いやだ/g,'#ffd8c7'],['ほんと',/ほんと|本当|まじ|マジ/g,'#e5e5e5'],['なるほど',/なるほど|たしかに|確かに/g,'#e5e5e5']
];
const grouped=new Map();for(const r of rows){if(!grouped.has(r.date))grouped.set(r.date,{み:[],も:[]});for(const l of (r.lines||[])){if(l.who==='み'||l.who==='も')grouped.get(r.date)[l.who].push(String(l.text||''))}}
const dates=[...grouped.keys()].sort();dateInput.min=dates[0]||'';dateInput.max=dates.at(-1)||'';document.getElementById('sourceCount').textContent=dates.length?`${dates.length}日分から`:'保存ログから';
function countThemes(lines){const joined=lines.join('\n'),out=[];for(const [label,re,color] of themes){re.lastIndex=0;const hits=joined.match(re);const count=hits?hits.length:0;if(count)out.push({label,count,color})}out.sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,'ja'));const top=out.slice(0,10),total=top.reduce((s,x)=>s+x.count,0);return top.map(x=>({...x,pct:total?Math.round(x.count/total*100):0}))}
function sizeFor(item,max,i){const ratio=max?item.count/max:0;return Math.round(10+ratio*10+(i===0?2:0))}
function paint(head,box,data){head.replaceChildren();box.replaceChildren();if(!data.length){const e=document.createElement('div');e.className='empty-brain';e.textContent='今日は静か';head.append(e);return}const max=data[0].count;data.forEach((x,i)=>{const w=document.createElement('span');w.className='brain-word';w.textContent=x.label;w.style.fontSize=sizeFor(x,max,i)+'px';w.style.background=x.color;w.style.opacity=String(Math.max(.66,1-i*.035));head.append(w);const row=document.createElement('div');row.className='break-row';row.innerHTML=`<span>${esc(x.label)}</span><b>${x.pct}%</b>`;box.append(row)})}
function setDate(d){if(!grouped.has(d))return;dateInput.value=d;dateLabel.textContent=d.replaceAll('-','/');const data=grouped.get(d),mi=countThemes(data.み),mo=countThemes(data.も);currentDate=d;currentMi=mi;currentMo=mo;paint(miHead,miBreak,mi);paint(moHead,moBreak,mo);const a=mi[0]?.label||'静か',b=mo[0]?.label||'静か';summary.textContent=a===b?`今日のわれわれ脳：ふたりとも「${a}」が強め。`:`今日のわれわれ脳：みは「${a}」、もは「${b}」が強め。`;const u=new URL(location.href);u.searchParams.set('date',d);history.replaceState(null,'',u)}
function rr(ctx,x,y,w,h,r){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function drawBrainPanel(ctx,x,title,data){const panelY=155,panelW=505,panelH=860;ctx.fillStyle='#fff';rr(ctx,x,panelY,panelW,panelH,26);ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=2;rr(ctx,x,panelY,panelW,panelH,26);ctx.stroke();ctx.fillStyle='#111';ctx.font='800 34px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.textAlign='center';ctx.fillText(title,x+panelW/2,panelY+58);const hx=x+42,hy=panelY+92,hw=421,hh=455;ctx.fillStyle='#fff';rr(ctx,hx,hy,hw,hh,155);ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=3;rr(ctx,hx,hy,hw,hh,155);ctx.stroke();if(!data.length){ctx.fillStyle='#888';ctx.font='700 28px sans-serif';ctx.fillText('今日は静か',x+panelW/2,hy+hh/2);return}const spots=[[.50,.22],[.28,.36],[.70,.38],[.44,.52],[.23,.59],[.73,.61],[.50,.70],[.29,.78],[.70,.79],[.49,.87]],maxPct=Math.max(...data.slice(0,10).map(v=>v.pct),1);data.slice(0,10).forEach((v,i)=>{const [rx,ry]=spots[i],ratio=v.pct/maxPct,fontSize=Math.round(17+Math.pow(ratio,.72)*27+(i===0?6:0)),px=hx+rx*hw,py=hy+ry*hh;ctx.font=`900 ${fontSize}px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';const tw=ctx.measureText(v.label).width,padX=10,padY=6;ctx.fillStyle=v.color||'#eee';rr(ctx,px-tw/2-padX,py-fontSize*.62-padY,tw+padX*2,fontSize*1.24+padY*2,10);ctx.fill();ctx.fillStyle='#111';ctx.fillText(v.label,px,py)});ctx.textBaseline='alphabetic';ctx.textAlign='left';ctx.font='700 22px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';data.slice(0,6).forEach((v,i)=>{const y=panelY+600+i*40;ctx.fillStyle=v.color||'#eee';ctx.fillRect(x+45,y-18,16,16);ctx.fillStyle='#222';ctx.fillText(v.label,x+74,y);ctx.textAlign='right';ctx.font='800 22px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.fillText(`${v.pct}%`,x+panelW-45,y);ctx.textAlign='left';ctx.font='700 22px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif'})}
async function brainBlob(){if(!currentDate)throw new Error('日付がありません');const W=1120,H=1080,canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');ctx.fillStyle='#f4f4f4';ctx.fillRect(0,0,W,H);ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='900 46px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.fillText('われわれ脳内メーカー',W/2,66);ctx.font='700 28px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.fillStyle='#555';ctx.fillText(fmtDate(currentDate),W/2,112);drawBrainPanel(ctx,40,'みの脳内',currentMi);drawBrainPanel(ctx,575,'もの脳内',currentMo);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('PNG作成に失敗')),'image/png'))}
function notify(msg){document.querySelector('.brain-share-toast')?.remove();const t=document.createElement('div');t.className='brain-share-toast';t.textContent=msg;Object.assign(t.style,{position:'fixed',left:'50%',bottom:'28px',transform:'translateX(-50%)',zIndex:100,background:'#111',color:'#fff',padding:'10px 14px',borderRadius:'999px',fontSize:'12px',fontWeight:'700'});document.body.append(t);setTimeout(()=>t.remove(),1800)}
async function shareBrainImage(){const blob=await brainBlob(),name=`warera-brain-${currentDate}.png`,file=new File([blob],name,{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});return}catch(e){if(e?.name==='AbortError')return}}if(navigator.clipboard&&window.ClipboardItem){try{await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);notify('画像をコピーしたよ');return}catch(e){}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();const u=a.href;a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);notify('画像を保存したよ')}
function openPicker(){if(typeof dateInput.showPicker==='function'){try{dateInput.showPicker();return}catch(e){}}dateInput.focus();dateInput.click()}
dateBtn.addEventListener('click',e=>{e.preventDefault();openPicker()});dateBtn.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPicker()}});dateInput.addEventListener('change',()=>setDate(dateInput.value));randomBtn.onclick=()=>setDate(dates[Math.floor(Math.random()*dates.length)]);shareBrain.onclick=async()=>{shareBrain.disabled=true;try{await shareBrainImage()}finally{shareBrain.disabled=false}};
const pd=new URLSearchParams(location.search).get('date');setDate(pd&&grouped.has(pd)?pd:dates[Math.floor(Math.random()*dates.length)]);
})();
