(async()=>{wireLock('../');const [core,memories,quizScenePack,analytics]=await Promise.all([WareraData.core('../'),WareraData.memories('../'),WareraData.quizScenePack('../'),WareraData.expandedAnalytics('../')]);const quizScenes=quizScenePack.scenes||[],anniversaries=analytics.anniversaries||core.anniversaries||[];const grouped=new Map();memories.forEach(x=>{if(!grouped.has(x.date))grouped.set(x.date,[]);grouped.get(x.date).push(x)});const quizById=new Map(quizScenes.map(x=>[String(x.id),x])),dates=[...grouped.keys()].sort();const picker=document.getElementById('pickDate'),pickerLabel=document.getElementById('pickDateLabel'),dateControl=document.getElementById('dateControl'),title=document.getElementById('dayTitle'),meta=document.getElementById('dayMeta'),scene=document.getElementById('dayScene'),nav=document.getElementById('sceneNav'),search=document.getElementById('logSearch'),searchBtn=document.getElementById('searchBtn'),searchNote=document.getElementById('searchNote'),anniversaryNote=document.getElementById('anniversaryNote');picker.min=dates[0]||'';picker.max=dates.at(-1)||'';let current=null,currentSceneId=null;
function openDatePicker(){if(typeof picker.showPicker==='function'){try{picker.showPicker();return}catch(e){}}picker.focus();picker.click()}
dateControl.addEventListener('click',e=>{if(e.target===picker){if(typeof picker.showPicker==='function'){try{picker.showPicker()}catch(err){}}return}e.preventDefault();openDatePicker()});dateControl.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDatePicker()}});
function setPickerValue(v){picker.value=v||'';pickerLabel.textContent=v?String(v).replaceAll('-','/'):'日付を選ぶ'}
const chatNode=WareraUI.chatScene;
function dayPool(date){const all=grouped.get(date)||[],readable=all.filter(WareraData.readableScene);return readable.length?readable:all}
function setUrl(item,around=false,source=''){if(!item)return;const u=new URL(location.href);u.searchParams.set('date',item.date);u.searchParams.set('scene',item.id);if(around)u.searchParams.set('around','1');else u.searchParams.delete('around');if(source)u.searchParams.set('source',source);else u.searchParams.delete('source');history.replaceState(null,'',u)}
function btn(label,cls=''){const b=document.createElement('button');b.className='press-btn '+cls;b.textContent=label;return b}
function sharePayload(item,pool,around=false){if(!around||!pool?.length)return item;const idx=pool.findIndex(x=>String(x.id)===String(item.id));if(idx<0)return item;const lines=[];for(let i=Math.max(0,idx-1);i<=Math.min(pool.length-1,idx+1);i++)lines.push(...(pool[i].lines||[]));return{date:item.date,lines}}
function shareButton(item,pool=null,around=false){const b=btn('画像にする');b.onclick=async()=>{b.disabled=true;try{await WareraShare.shareScene(sharePayload(item,pool,around))}finally{b.disabled=false}};return b}
function showAnniversary(date){const hits=anniversaries.filter(x=>x.date===date);anniversaryNote.classList.toggle('is-show',!!hits.length);anniversaryNote.innerHTML=hits.length?`<b>どうでもいい記念日</b><span class="anniversary-date">${esc(fmtDate(date))}</span><br>${hits.map(x=>esc(x.label||x.title||'記念日')).join('<br>')}`:''}
function renderSingle(item,pool){currentSceneId=item?.id??null;scene.replaceChildren();nav.replaceChildren();if(!item)return;scene.append(chatNode(item));setUrl(item,false);const idx=pool.findIndex(x=>String(x.id)===String(item.id)),another=btn('同じ日の別の会話','primary primary-action');another.onclick=()=>sceneFor(item.date);const around=btn('この会話の前後を見る');around.onclick=()=>renderAround(item,pool);nav.append(another,around,shareButton(item));if(idx>0){const p=btn('← 前の会話');p.onclick=()=>renderSingle(pool[idx-1],pool);nav.append(p)}if(idx>=0&&idx<pool.length-1){const n=btn('次の会話 →');n.onclick=()=>renderSingle(pool[idx+1],pool);nav.append(n)}}
function renderAround(item,pool){currentSceneId=item?.id??null;scene.replaceChildren();nav.replaceChildren();const idx=pool.findIndex(x=>String(x.id)===String(item.id)),from=Math.max(0,idx-1),to=Math.min(pool.length-1,idx+1),wrap=document.createElement('div');wrap.className='around-wrap';for(let i=from;i<=to;i++){const block=document.createElement('section');block.className='around-block'+(i===idx?' is-current':'');const label=document.createElement('div');label.className='around-label';label.textContent=i===idx?'いま見ている会話':i<idx?'少し前の会話':'少しあとの会話';block.append(label,chatNode(pool[i]));wrap.append(block)}scene.append(wrap);setUrl(item,true);const back=btn('この会話だけに戻す','primary primary-action');back.onclick=()=>renderSingle(item,pool);nav.append(back,shareButton(item,pool,true));if(idx>0){const p=btn('← さらに前の会話');p.onclick=()=>renderAround(pool[idx-1],pool);nav.append(p)}if(idx>=0&&idx<pool.length-1){const n=btn('さらに後の会話 →');n.onclick=()=>renderAround(pool[idx+1],pool);nav.append(n)}}
function renderQuizContext(item){current=item.date;currentSceneId=item.id;setPickerValue(item.date);title.textContent=fmtDate(item.date);meta.textContent='検定の前後';searchNote.textContent='検定に出た発言の前後';showAnniversary(item.date);scene.replaceChildren(chatNode(item));nav.replaceChildren();setUrl(item,false,'quiz');const b=btn('同じ日の別の会話','primary primary-action');b.onclick=()=>sceneFor(item.date);nav.append(b,shareButton(item))}
function sceneFor(date,requestedId=null,wantAround=false){current=date;showAnniversary(date);const all=grouped.get(date)||[];if(!all.length){title.textContent='この日のログはまだない';meta.textContent='';scene.innerHTML='<div class="empty">日付を変えるか、ランダムな日をどうぞ。</div>';nav.replaceChildren();return}title.textContent=fmtDate(date);const pool=dayPool(date);let item=requestedId!=null?all.find(x=>String(x.id)===String(requestedId)):null;if(!item){const choices=pool.filter(x=>String(x.id)!==String(currentSceneId)),src=choices.length?choices:pool;item=src[Math.floor(Math.random()*src.length)]}meta.textContent=`${pool.length}会話`;wantAround?renderAround(item,pool):renderSingle(item,pool)}
function loadDate(d,sceneId=null,wantAround=false){setPickerValue(d);currentSceneId=null;searchNote.textContent='';sceneFor(d,sceneId,wantAround)}
picker.onchange=()=>loadDate(picker.value);document.getElementById('randomDay').onclick=()=>loadDate(dates[Math.floor(Math.random()*dates.length)]);document.getElementById('anniversaryBtn').onclick=()=>{const pool=anniversaries.filter(x=>grouped.has(x.date));if(!pool.length){anniversaryNote.classList.add('is-show');anniversaryNote.textContent='記念日が見つからんかった。';return}const x=pool[Math.floor(Math.random()*pool.length)];loadDate(x.date);showAnniversary(x.date)};document.getElementById('todayBtn').onclick=()=>{const now=new Date(),md=`-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,match=[...dates].reverse().find(x=>x.endsWith(md));match?loadDate(match):sceneFor('')};
function runSearch(){const q=search.value.trim();if(!q){searchNote.textContent='ことばを入れてね';return}const hits=memories.filter(x=>(x.lines||[]).some(l=>String(l.text||'').includes(q)));if(!hits.length){searchNote.textContent='見つからんかった。';return}const readableHits=hits.filter(WareraData.readableScene),pool=readableHits.length?readableHits:hits,item=pool[Math.floor(Math.random()*pool.length)];loadDate(item.date,item.id,true);searchNote.textContent=`「${q}」を含む会話 ${hits.length}件`}searchBtn.onclick=runSearch;search.onkeydown=e=>{if(e.key==='Enter')runSearch()};
const params=new URLSearchParams(location.search),pd=params.get('date'),ps=params.get('scene'),pa=params.get('around')==='1',src=params.get('source');const qScene=ps?quizById.get(String(ps)):null;if((src==='quiz'||qScene)&&qScene)renderQuizContext(qScene);else if(pd&&grouped.has(pd))loadDate(pd,ps,pa);else loadDate(dates[Math.floor(Math.random()*dates.length)])})();
