export const NAMES={み:'みちゃこ',も:'もっち'};
export const DB_NAME='warera-grow';
export const STORE='pets';
export const KEY_PREFIX='warera_grow_v1_';
export const ROOM='./assets/room/';
export const COMMON_ASSET='./assets/pets/common/';
export const CHAR_ASSET='./assets/pets/';

const BLOCK=/https?:\/\/|画像は含まれていません|スタンプは含まれていません|ビデオは含まれていません|メッセージをピン留め|アンケート:|音声通話|ビデオ通話|このメッセージは削除されました/i;
const RX={
  morning:/おは|起き|おき|寝た|ねた|朝|お目覚め/,
  sleep:/おやす|ねる|寝る|ねむ|眠|オフトゥン|すや|おふとん/,
  feed:/ごはん|ご飯|飯|食べ|食う|腹|おなか|お腹|うま|おいし|美味|ランチ|おやつ|めし/,
  bath:/風呂|フロ|おふろ|カラダ・アラウ|シャワ|洗う|洗って|湯気/,
  affection:/好き|すき|しゅき|かわい|可愛|愛|メロ|はすはす|ぎゅ|ちゅ|幸せ|会いた|会えて|うれし|嬉し/,
  play:/w{2,}|草|わろ|遊|しょもしょも|ゲーム|おもろ|面白|笑|www|なんやこれ|なにこれ/,
  surprise:/ﾊｯ|ハッ|え[？?！!]|ま[？?]|なんで|はーん|ほう|うそ|マジ|まじ/,
  tease:/やめ|こら|おい|なんや|なにそれ|はいはい|うるさ|近い|しつこ|www|w{3,}/,
  ack:/^(うい|ういー|おけ|おけー|おけけ|りょ|了解|ふむ|ほう|そそ|あーね|なる|なるほど|はい|へい|よし|ん|うん)[！!。ー〜～w\s]*(.*)?$/i,
  return:/おかえり|ただいま|おつ|お疲れ|おつかれ|また明日|きた|来た/,
  comfort:/大丈夫|だいじょ|無理|むり|休|ゆっくり|よしよし|えらい|偉い/,
  rareLove:/大好き|だいすき|好きだ|すきだ|幸せ|しあわせ|会いたい|かわいい|可愛い|愛して|しゅき|メロ/,
};
export {RX};

const FALLBACK={
  み:{idle:['そそ','なある！','あーねw','おけけ','だん！','なんやこれ','もーなにこれ'],morning:['おはよん( ´꒳` )','あーんおはよ( ´꒳` )'],sleep:['おやすみーーん！！','ねるよーー！！'],feed:['おなかすいた','飯！','うまそ'],bath:['フロダン！','カラダ・アラウ'],play:['wwww','しょもしょも…','なんやこれw'],affection:['かわいいってば','ほんとすき','しゅきー'],tease:['やめろw','もーなにこれ'],surprise:['ﾊｯ！！！！！！！','え？'],return:['おかえりー'],comfort:['だいじょぶ','えらい']},
  も:{idle:['ういー','ほう','ふむ','おけー','あーねwww','うぇいよー','そりゃあねぇw'],morning:['おはよーん','おはよーーー！'],sleep:['おやすみね','また明日ねーー','おれもねるだよーーー'],feed:['腹へった','飯たすかる'],bath:['おつだああああん','カラダ・アラウ'],play:['wwww','しょもしょも','楽しい。'],affection:['気が合いますねえ（好き','今日もかわいかったぞ','んふふ'],tease:['はいはいw','近い。','なにw'],surprise:['ﾊｯ','はーーーん？'],return:['おかえりー','おつかれさーん'],comfort:['無理すんなよ','ゆっくりしな']}
};

export const getViewer=()=>{try{return localStorage.getItem('warera_chat_perspective')==='も'?'も':'み'}catch{return'み'}};
export const now=()=>Date.now();
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const cleanText=t=>String(t||'').replace(/[\u200e\u200f]/g,'').trim();
const usable=t=>{t=cleanText(t);return !!t&&t.length<=90&&t.split('\n').length<=3&&!BLOCK.test(t)};
const pick=a=>a[Math.floor(Math.random()*a.length)];
const clamp=(v,a=0,b=9999)=>Math.max(a,Math.min(b,Number(v)||0));

function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}catch(e){reject(e)}})}

function addPool(pools,key,e,seen){if(!pools[key])pools[key]=[];const nk=key+'\0'+e.text;if(seen.has(nk))return;seen.add(nk);pools[key].push(e)}
function buildCorpus(scenes,target){
  const pools={idle:[],short:[],morning:[],sleep:[],feed:[],bath:[],play:[],affection:[],rareLove:[],tease:[],surprise:[],ack:[],return:[],comfort:[],memory:[]};
  const seen=new Set(),sceneMap=new Map(),tokens=new Map();
  for(const sc of scenes||[]){
    sceneMap.set(String(sc.id),sc);
    const lines=(sc.lines||[]).filter(x=>x&&usable(x.text));
    for(let i=0;i<lines.length;i++){
      const l=lines[i];if(l.who!==target)continue;
      const text=cleanText(l.text),prev=i?cleanText(lines[i-1]?.text):'',e={text,date:sc.date||'',sceneId:String(sc.id||''),prev};
      if(text.length<=42)addPool(pools,'idle',e,seen);
      if(text.length<=16)addPool(pools,'short',e,seen);
      for(const [key,rx] of Object.entries(RX)){if(key==='rareLove')continue;if(rx.test(text)||rx.test(prev))addPool(pools,key,e,seen)}
      if(RX.rareLove.test(text)&&text.length<=58)addPool(pools,'rareLove',e,seen);
      if(text.length<=58)addPool(pools,'memory',e,seen);
      for(const w of ['おけけ','しょもしょも','オフトゥン','だん','かわいい','好き','すき','www','w','あーね','ほう','ふむ','うい','われわれ','カラダ・アラウ','はすはす','メロ'])if(text.includes(w))tokens.set(w,(tokens.get(w)||0)+1);
    }
  }
  for(const key of Object.keys(pools)){
    const lim=key==='idle'?1800:key==='memory'?1200:600;
    if(pools[key].length>lim){const step=pools[key].length/lim;pools[key]=Array.from({length:lim},(_,i)=>pools[key][Math.floor(i*step)])}
  }
  return{pools,sceneMap,tokens:[...tokens.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]),count:new Set(Object.values(pools).flat().map(x=>x.text)).size};
}
function quizToScenes(q){const out=[];let n=0;for(const x of q?.who||[]){if(x?.quote&&x?.answer)out.push({id:'quiz-who-'+n++,date:x.date||'',lines:[{who:x.answer,text:x.quote}]})}for(const x of q?.next||[]){if(!x)continue;const lines=[];if(x.prompt&&x.prompt_who)lines.push({who:x.prompt_who,text:x.prompt});if(x.answer&&x.answer_who)lines.push({who:x.answer_who,text:x.answer});if(lines.length)out.push({id:'quiz-next-'+n++,date:x.date||'',lines})}return out}
function mergeQuizCorpus(base,extra){const seen=new Set(Object.entries(base.pools).flatMap(([k,a])=>(a||[]).map(e=>k+'\0'+e.text)));for(const [k,rows] of Object.entries(extra.pools||{})){if(k==='memory')continue;for(const e of rows||[])addPool(base.pools,k,e,seen)}base.tokens=[...new Set([...(base.tokens||[]),...(extra.tokens||[])])].slice(0,12);base.count=new Set(Object.values(base.pools).flat().map(x=>x.text)).size;return base}

export class GrowModel{
  constructor(viewer=getViewer()){
    this.viewer=viewer;
    this.target=viewer==='み'?'も':'み';
    this.state=null;
    this.corpus=null;
    this.currentSpeechEntry=null;
  }
  key(){return `${KEY_PREFIX}${this.viewer}_${this.target}`}
  fresh(){return{id:this.key(),version:20,viewer:this.viewer,target:this.target,born:today(),stageRank:0,experience:0,totalCare:0,actions:{},lastActionAt:{},recent:[],traits:{clingy:0,independent:0,overcare:0,playful:0,gentle:0},eggActions:{},nights:0,lastNight:'',childType:'',childTypeVersion:0,personality:'',personalityVersion:0,favoritePhrases:{},learned:{},lastSpeech:'……',lastVisitAt:now(),manualSleepUntil:0,morningWakeDate:'',poop:false,poopDueAt:0,updatedAt:now()}}
  async readDb(){try{const db=await openDb(),x=await new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(this.key());q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)});db.close();return x}catch{return null}}
  readLocal(){try{return JSON.parse(localStorage.getItem(this.key())||'null')}catch{return null}}
  async load(){const [db,local]=await Promise.all([this.readDb(),Promise.resolve(this.readLocal())]);this.state=db&&local?(Number(db.updatedAt||0)>=Number(local.updatedAt||0)?db:local):(db||local)||this.fresh();this.migrate();await this.loadCorpus();this.initializeSpeech();await this.save();return this}
  async save(){const s=this.state;s.id=this.key();s.viewer=this.viewer;s.target=this.target;s.version=20;s.updatedAt=now();try{localStorage.setItem(this.key(),JSON.stringify(s))}catch{}try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(s);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch{}}
  async remove(){try{localStorage.removeItem(this.key())}catch{}try{const db=await openDb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).delete(this.key());q.onsuccess=()=>res();q.onerror=()=>rej(q.error)});db.close()}catch{}}
  migrate(){
    let s=this.state||this.fresh();const legacyXP=Number(s.growthXP||0);
    if(s.version<20||s.stageRank==null){s.stageRank=legacyXP>=520?3:legacyXP>=200?2:legacyXP>=48?1:0;s.experience=Math.max(Number(s.experience||0),Math.round(Number(s.totalCare||0)*1.2),s.stageRank===3?48:s.stageRank===2?16:s.stageRank===1?5:0)}
    s.version=20;s.actions=s.actions||{};s.lastActionAt=s.lastActionAt||{};s.recent=Array.isArray(s.recent)?s.recent:[];s.traits=s.traits||{};
    for(const k of ['clingy','independent','overcare','playful','gentle'])s.traits[k]=Number(s.traits[k]||0);
    if(s.profile){s.traits.clingy=Math.max(s.traits.clingy,Number(s.profile.affection||0)*.35);s.traits.independent=Math.max(s.traits.independent,Number(s.profile.practical||0)*.22);s.traits.overcare=Math.max(s.traits.overcare,Number(s.profile.overcare||0)*.5)}
    s.eggActions=s.eggActions||{};s.favoritePhrases=s.favoritePhrases||{};s.learned=s.learned||{};s.nights=Number(s.nights||0);s.lastNight=s.lastNight||'';s.childType=s.childType||'';s.childTypeVersion=Number(s.childTypeVersion||0);s.personality=s.personality||'';s.personalityVersion=Number(s.personalityVersion||0);s.manualSleepUntil=Number(s.manualSleepUntil||s.sleepUntil||0);s.morningWakeDate=s.morningWakeDate||'';s.poop=!!s.poop;s.poopDueAt=Number(s.poopDueAt||0);s.lastVisitAt=Number(s.lastVisitAt||now());s.lastSpeech=s.lastSpeech||'……';if(s.memoryEnabled==null)s.memoryEnabled=true;
    this.state=s;this.updateReturnTrait();this.resolveEvolution();
  }
  updateReturnTrait(){const s=this.state,gap=Math.max(0,(now()-Number(s.lastVisitAt||now()))/36e5);if(gap>=3)s.traits.independent+=Math.min(2.4,gap/8);s.lastVisitAt=now()}
  async loadCorpus(){let base=buildCorpus([],this.target);try{const scenes=await window.WareraData?.memories?.('../');if(scenes?.length)base=buildCorpus(scenes,this.target)}catch(e){console.warn('grow memories corpus fallback',e)}try{const q=await window.WareraData?.expandedQuiz?.('../');if(q)base=mergeQuizCorpus(base,buildCorpus(quizToScenes(q),this.target))}catch(e){console.warn('grow full-log corpus fallback',e)}this.corpus=base}
  initializeSpeech(){const st=this.stageKey(),s=this.state;if(st==='egg'){s.lastSpeech='……';this.currentSpeechEntry=null;return}if(st==='baby'&&(!s.lastSpeech||s.lastSpeech==='……おけけ？'||String(s.lastSpeech).length>18)){s.lastSpeech='…';this.currentSpeechEntry=null;return}if(!s.lastSpeech||s.lastSpeech==='……おけけ？'){const e=this.entryFor(new Date().getHours()<10?'morning':'idle');s.lastSpeech=e.text;this.currentSpeechEntry=e}else this.currentSpeechEntry={text:s.lastSpeech,date:'',sceneId:''}}
  stage(){return[['egg','たまご'],['baby','あかちゃん'],['child','こども'],['adult','おとな']][clamp(this.state.stageRank,0,3)]}
  stageKey(){return this.stage()[0]}
  ageDays(){return Math.max(1,Math.floor((new Date()-new Date((this.state.born||today())+'T00:00:00'))/864e5)+1)}
  uniqueCare(){return Object.keys(this.state.actions||{}).filter(k=>['feed','play','pat','bath','toilet'].includes(k)&&this.state.actions[k]>0).length}
  topScore(scores){return Object.entries(scores).sort((a,b)=>b[1]-a[1])[0]?.[0]||''}
  resolveEvolution(){const s=this.state;if(s.stageRank===0){const n=Object.values(s.eggActions||{}).reduce((a,b)=>a+Number(b||0),0),u=Object.keys(s.eggActions||{}).filter(k=>s.eggActions[k]>0).length;if(n>=5&&u>=3)s.stageRank=1}if(s.stageRank===1&&s.experience>=16&&this.uniqueCare()>=3)s.stageRank=2;if(s.stageRank===2&&s.experience>=48&&this.uniqueCare()>=4)s.stageRank=3;const t=s.traits;if(s.stageRank>=2&&Number(s.childTypeVersion||0)<2){s.childType=this.topScore({affection:t.clingy+t.overcare*.30+t.gentle*.10,playful:t.playful*1.15+t.clingy*.15,calm:t.gentle*1.10+t.independent*.12,independent:t.independent*1.12+t.gentle*.08});s.childTypeVersion=2}if(s.stageRank===3&&Number(s.personalityVersion||0)<2){s.personality=this.topScore({amaenbo:t.clingy*1.35+t.gentle*.22-t.independent*.20,playful:t.playful*1.38+t.clingy*.14+t.overcare*.08,gentle:t.gentle*1.18+t.independent*.18-t.overcare*.08,aloof:t.independent*1.28-t.clingy*.24,tsundere:t.overcare*1.20+t.independent*.34+t.clingy*.08,moody:t.overcare*.72+t.playful*.58+t.independent*.28,dere:t.clingy*.92+t.gentle*.62+t.playful*.12});s.personalityVersion=2}}
  branchLabel(){const st=this.stageKey();if(st==='child')return({affection:'かまわれ育ち',playful:'いたずら育ち',calm:'おだやか育ち',independent:'マイペース育ち',plain:'マイペース育ち'})[this.state.childType]||'マイペース育ち';if(st==='adult')return({amaenbo:'甘えんぼ系',playful:'いたずら系',gentle:'おだやか系',aloof:'そっけない系',tsundere:'ツンデレ系',moody:'気分屋系',dere:'でれ系'})[this.state.personality]||'でれ系';return''}
  localDateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  nightKey(d=new Date()){const x=new Date(d);if(x.getHours()<9)x.setDate(x.getDate()-1);return this.localDateKey(x)}
  markNight(){const k=this.nightKey();if(this.state.lastNight!==k){this.state.lastNight=k;this.state.nights++;this.state.experience+=1}}
  canSleepNow(){const h=new Date().getHours();return h>=21||h<9}
  canWakeNow(){const h=new Date().getHours();return h>=7&&h<9}
  nextNine(){const d=new Date();if(d.getHours()>=9)d.setDate(d.getDate()+1);d.setHours(9,0,0,0);return d.getTime()}
  isAsleep(){if(this.stageKey()==='egg')return false;const h=new Date().getHours(),s=this.state,manual=Number(s.manualSleepUntil||0)>now();if(h<7){this.markNight();s.morningWakeDate='';s.manualSleepUntil=Math.max(Number(s.manualSleepUntil||0),this.nextNine());return true}if(h>=7&&h<9){this.markNight();if(s.morningWakeDate===today())return false;if(!manual)s.manualSleepUntil=this.nextNine();return true}if(h>=21)return manual;if(h>=9&&h<21&&s.manualSleepUntil)s.manualSleepUntil=0;return false}
  minsSince(action){const t=Number(this.state.lastActionAt?.[action]||0);return t?Math.max(0,(now()-t)/60000):9999}
  updatePoop(){const s=this.state;if(s.poopDueAt&&now()>=s.poopDueAt&&!this.isAsleep()){s.poop=true;s.poopDueAt=0}}
  moment(){if(this.isAsleep())return{key:'sleep',emoji:'🌙',label:'すやすや寝てる',action:'sleep'};this.updatePoop();if(this.state.poop)return{key:'toilet',emoji:'💩',label:'なんか出てる',action:'toilet'};const vals=[['feed',this.minsSince('feed')/210,'🍚','なんか食べたそう'],['play',this.minsSince('play')/165,'🎮','ひまそう'],['bath',this.minsSince('bath')/540,'🫧','そろそろカラダ・アラウ'],['pat',this.minsSince('pat')/(this.state.traits.clingy>this.state.traits.independent?190:260),'💗','ちょっと構われたそう']].sort((a,b)=>b[1]-a[1]);if(vals[0][1]>=1)return{key:vals[0][0],emoji:vals[0][2],label:vals[0][3],action:vals[0][0]};if(new Date().getHours()>=21)return{key:'sleepSoon',emoji:'🌙',label:'夜になってきた',action:'sleep'};const quiet=this.state.traits.independent>this.state.traits.clingy*.95;return{key:'fine',emoji:quiet?'☀️':'✨',label:quiet?'ひとりでしょもしょもしてる':'なんでもない。たぶん。',action:''}}
  fallbackEntries(key){return(FALLBACK[this.target][key]||FALLBACK[this.target].idle||[]).map(text=>({text,date:'',sceneId:'',prev:''}))}
  recentTexts(){return new Set((this.state.recent||[]).slice(-24).map(x=>x.text).filter(Boolean))}
  weightedPick(arr,key){arr=arr?.length?arr:this.fallbackEntries(key);const recent=this.recentTexts(),fav=this.state.favoritePhrases||{};let pool=arr.filter(x=>!recent.has(x.text));if(!pool.length)pool=arr;const weighted=[];for(const e of pool){let n=1+Math.min(4,Number(fav[e.text]||0));if(e.text.length<=18)n++;for(let i=0;i<n;i++)weighted.push(e)}return pick(weighted.length?weighted:pool)}
  entryFor(key){return this.weightedPick(this.corpus?.pools?.[key],key)}
  recordRecent(type,text){this.state.recent.push({at:now(),type,text});if(this.state.recent.length>80)this.state.recent=this.state.recent.slice(-80)}
  repeats(a){const last=(this.state.recent||[]).slice(-8).filter(x=>x.type==='action');let n=0;for(let i=last.length-1;i>=0;i--){if(last[i].action===a)n++;else break}return n}
  contextualSpeech(a,matched,repeat){const st=this.stageKey(),rareChance=(st==='adult'?.055:st==='child'?.035:.018)+Math.min(.02,Object.keys(this.state.favoritePhrases||{}).length*.002);if(['pat','play'].includes(a)&&this.corpus?.pools?.rareLove?.length&&Math.random()<rareChance)return{entry:this.entryFor('rareLove'),rare:true};if(repeat>=4&&this.corpus?.pools?.tease?.length&&Math.random()<.35)return{entry:this.entryFor('tease'),rare:false};const map={feed:'feed',play:'play',pat:'affection',bath:'bath',toilet:'ack',sleep:'sleep',wake:'morning',return:'return'},key=map[a]||'idle';const actionRx={feed:/ごはん|ご飯|飯|食べ|たべ|お腹|おなか|腹減|うま|おいし/,play:/遊|あそ|ゲーム|ちょっかい|つつ|暇|ひま|www|笑/,pat:/かわい|可愛|好き|すき|撫|なで|愛で|ぎゅ|はすはす/,bath:/風呂|おふろ|シャワー|カラダ.?アラウ|洗|あら|湯/,toilet:/トイレ|うんこ|💩|便|出た|でた|すっきり/,sleep:/眠|ねむ|寝|おやす|オフトゥン|布団/,wake:/おはよ|起き|おき|朝/,return:/おかえり|ただいま|帰|きた/}[a],rows=this.corpus?.pools?.[key]||[];if(actionRx&&rows.length){const direct=rows.filter(e=>{actionRx.lastIndex=0;const hp=actionRx.test(String(e.prev||''));actionRx.lastIndex=0;return hp||actionRx.test(String(e.text||''))});if(direct.length)return{entry:this.weightedPick(direct,key),rare:false}}return{entry:this.entryFor(key),rare:false}}
  earlySpeech(a,e){if(this.stageKey()!=='baby')return{text:e?.text||'',entry:e||null};const bases={idle:['…','ん。','ふむ。'],feed:['もぐ。','んま。','ごはん。'],play:['…！','きゃ。','ふふ。'],pat:['んふ。','…♡','ぬくい。'],bath:['ふろ。','ぷは。','ほかほか。'],toilet:['すっきり。','…'],sleep:['ねむ。','…ねる。','すや。'],wake:['おきた。','…ん。'],return:['きた。','…！']};const base=pick(bases[a]||bases.idle),raw=cleanText(e?.text||'').replace(/\s+/g,' '),canMix=raw&&raw.length<=14,rate=a==='idle'?.22:.38;if(canMix&&Math.random()<rate)return{text:base+' '+raw,entry:e};return{text:base,entry:null}}
  experienceGain(a,matched,repeat){let g=1;if(matched)g+=1;if(this.state.recent.slice(-1)[0]?.action!==a)g+=.5;if(repeat>=2)g*=.55;return Math.max(.35,g)}
  applyTraits(a,matched,repeat){const t=this.state.traits;if(a==='pat'){t.clingy+=matched?1.8:1;t.gentle+=.5;if(!matched||repeat>=2)t.overcare+=.8+repeat*.15}if(a==='play'){t.playful+=matched?1.5:1;t.clingy+=.25;if(repeat>=3)t.overcare+=.4}if(['feed','bath','toilet'].includes(a)){t.gentle+=matched?1:.45;if(matched)t.independent+=.55;if(!matched&&repeat>=2)t.overcare+=.35}if(a==='sleep')t.gentle+=.4}
  reactionPet(a,repeat,rare){const st=this.stageKey();if(st==='egg')return'';if(st==='baby'){if(a==='play')return Math.random()<.5?'baby_left.png':'baby_right.png';return'baby_front.png'}if(st==='child'){if(['feed','play','pat'].includes(a))return'child_cheer.png';if(a==='sleep')return'blanket_rest.png';return'child_front.png'}const r=Math.random();if(a==='feed'){if(repeat>=4)return r<.55?'adult_pout.png':'adult_troubled.png';return r<.78?'adult_eat.png':r<.91?'adult_cheer.png':'adult_front.png'}if(a==='bath'){if(repeat>=4)return r<.6?'adult_pout.png':'adult_troubled.png';return r<.86?'adult_bath.png':r<.94?'adult_cheer.png':'adult_shy.png'}if(a==='toilet')return r<.86?'adult_toilet.png':r<.94?'adult_troubled.png':'adult_front.png';if(a==='pat'){if(rare)return'adult_shy.png';if(repeat>=5)return r<.55?'adult_angry.png':'adult_pout.png';if(repeat>=3)return r<.52?'adult_pout.png':'adult_head_pat.png';return r<.58?'adult_head_pat.png':r<.82?'adult_shy.png':'adult_cheer.png'}if(a==='play'){if(repeat>=5)return r<.48?'adult_angry.png':r<.78?'adult_pout.png':'adult_troubled.png';if(repeat>=3)return r<.34?'adult_pout.png':r<.70?'adult_cheer.png':r<.85?'adult_front.png':r<.925?'adult_left.png':'adult_right.png';return r<.55?'adult_cheer.png':r<.78?'adult_front.png':r<.89?'adult_left.png':'adult_right.png'}if(a==='sleep')return'adult_sleep.png';return''}
  async act(a){const s=this.state,before=this.stageKey(),sleeping=this.isAsleep();if(sleeping&&a!=='sleep'){const sp=this.earlySpeech('sleep',this.entryFor('sleep'));s.lastSpeech=sp.text;this.currentSpeechEntry=sp.entry;this.recordRecent('speech',s.lastSpeech);await this.save();return{reaction:'',anim:'',stageChanged:null}}if(a==='sleep'&&sleeping){if(this.canWakeNow()){s.manualSleepUntil=0;s.morningWakeDate=today();const r=this.contextualSpeech('wake',true,0),sp=this.earlySpeech('wake',r.entry);s.lastSpeech=sp.text;this.currentSpeechEntry=sp.entry;this.recordRecent('speech',s.lastSpeech);await this.save();return{reaction:'stand_front.png',anim:'bounce',stageChanged:null}}const sp=this.earlySpeech('sleep',this.entryFor('sleep'));s.lastSpeech=sp.text;this.currentSpeechEntry=sp.entry;this.recordRecent('speech',s.lastSpeech);await this.save();return{reaction:'',anim:'',stageChanged:null}}if(a==='sleep'&&!this.canSleepNow()){const sp=this.earlySpeech('idle',this.entryFor('idle'));s.lastSpeech=sp.text;this.currentSpeechEntry=sp.entry;this.recordRecent('speech',s.lastSpeech);await this.save();return{reaction:'',anim:'',stageChanged:null}}
    const m=this.moment(),matched=m.action===a,rep=this.repeats(a),existingPoopDue=a==='feed'&&!s.poop&&Number(s.poopDueAt||0)>now()?Number(s.poopDueAt):0;
    s.totalCare=Number(s.totalCare||0)+1;s.actions[a]=Number(s.actions[a]||0)+1;s.lastActionAt[a]=now();s.experience=Number(s.experience||0)+this.experienceGain(a,matched,rep);this.applyTraits(a,matched,rep);
    if(a==='feed'){const due=now()+(45+Math.random()*75)*60000;s.poopDueAt=existingPoopDue?Math.min(existingPoopDue,due):due}if(a==='toilet'){s.poop=false;s.poopDueAt=0}if(a==='sleep'){this.markNight();s.manualSleepUntil=this.nextNine();s.morningWakeDate=''}
    const r=this.contextualSpeech(a,matched,rep),sp=this.earlySpeech(a,r.entry);s.lastSpeech=sp.text;this.currentSpeechEntry=sp.entry;s.recent.push({at:now(),type:'action',action:a,text:s.lastSpeech});if(s.recent.length>80)s.recent=s.recent.slice(-80);this.resolveEvolution();const after=this.stageKey();if(after!==before)s.lastSpeech={baby:'……でた。',child:'なんか育った。',adult:'これがおとな。'}[after]||s.lastSpeech;await this.save();return{reaction:this.reactionPet(a,rep,r.rare),anim:a==='play'?'bounce':a==='pat'?'squish':'wiggle',stageChanged:after!==before?{from:before,to:after}:null}}
  async eggAct(a){const s=this.state,before=this.stageKey();s.eggActions[a]=Number(s.eggActions[a]||0)+1;s.totalCare=Number(s.totalCare||0)+1;s.experience+=1;const voice={warm:['……','…ぬく。'],call:['…？','……！'],tap:['ぴく。','…！'],hum:['♪','……♪'],listen:['……','（じー）'],word:['…！','？']}[a]||['……'];s.lastSpeech=pick(voice);this.currentSpeechEntry=null;this.recordRecent('speech',s.lastSpeech);this.resolveEvolution();const after=this.stageKey();if(after!==before)s.lastSpeech='……でた。';await this.save();return{reaction:this.basePet(),anim:'wiggle',stageChanged:after!==before?{from:before,to:after}:null}}
  idleSpeechKey(){const h=new Date().getHours();if(h<10)return'morning';const p=this.state.personality||'',r=Math.random();if(p==='amaenbo'){if(r<.30)return'affection';if(r<.46)return'ack'}else if(p==='playful'){if(r<.30)return'play';if(r<.48)return'tease';if(r<.58)return'surprise'}else if(p==='gentle'){if(r<.24)return'comfort';if(r<.42)return'ack'}else if(p==='aloof'){if(r<.28)return'ack';if(r<.36)return'tease'}else if(p==='tsundere'){if(r<.27)return'tease';if(r<.34)return'affection';if(r<.46)return'ack'}else if(p==='moody'){if(r<.18)return'tease';if(r<.34)return'affection';if(r<.50)return'play';if(r<.60)return'surprise'}else if(p==='dere'){if(r<.22)return'affection';if(r<.38)return'ack'}if(r<.16)return'ack';return'idle'}
  async idleSpeech(){if(this.stageKey()==='egg'||this.isAsleep())return false;const prev=String(this.state.lastSpeech||'');let chosen=null,spoken='';for(let i=0;i<5;i++){const e=this.entryFor(this.idleSpeechKey()),sp=this.earlySpeech('idle',e),t=String(sp.text||'').trim();if(!t)continue;spoken=t;chosen=sp.entry;if(t!==prev)break}if(!spoken||spoken===prev)return false;this.state.lastSpeech=spoken;this.currentSpeechEntry=chosen;this.recordRecent('speech',spoken);await this.save();return true}
  async likeSpeech(){const speech=cleanText(this.state.lastSpeech||''),entry=cleanText(this.currentSpeechEntry?.text||'');if(!entry||!speech.includes(entry))return false;if(!this.state.favoritePhrases[entry])this.state.favoritePhrases[entry]=3;await this.save();return true}
  basePet(){const st=this.stageKey();if(st==='egg')return'egg_idle.png';if(st==='baby')return'baby_front.png';if(st==='child')return this.state.childType==='affection'?'child_cheer.png':'child_front.png';return'adult_front.png'}
  currentPet(){const st=this.stageKey();if(st==='egg')return'egg_idle.png';if(this.isAsleep())return st==='adult'?'adult_sleep.png':'blanket_rest.png';const m=this.moment();if(m.key==='play'&&this.minsSince('play')>300)return st==='adult'?'adult_sad.png':this.basePet();return this.basePet()}
  idleOptions(){const st=this.stageKey(),p=this.state.personality||'',child=this.state.childType||'';if(st==='egg')return[{f:'egg_idle.png',a:'wiggle',w:5,fx:''},{f:'egg_idle.png',a:'squish',w:2,fx:'…'},{f:'egg_idle.png',a:'wiggle',w:1,fx:'？'}];if(this.isAsleep()){const f=st==='adult'?'adult_sleep.png':'blanket_rest.png';return[{f,a:'idle-breathe',w:7,fx:''},{f,a:'idle-doze',w:3,fx:'Zzz'},{f,a:'wiggle',w:1,fx:'…'}]}if(st==='baby')return[{f:'baby_front.png',a:'idle-breathe',w:7},{f:'baby_left.png',a:'idle-shuffle',w:2},{f:'baby_right.png',a:'idle-shuffle',w:2},{f:'baby_back.png',a:'idle-peek',w:1}];if(st==='child')return[{f:'child_front.png',a:'idle-breathe',w:6},{f:'child_left.png',a:'idle-shuffle',w:2},{f:'child_right.png',a:'idle-shuffle',w:2},{f:'child_back.png',a:'idle-peek',w:1},{f:'child_cheer.png',a:'bounce',w:child==='affection'?2.5:1}];const a=[{f:'adult_front.png',a:'idle-breathe',w:5},{f:'adult_left.png',a:'idle-shuffle',w:2.4},{f:'adult_right.png',a:'idle-shuffle',w:2.4},{f:'adult_back.png',a:'idle-breathe',w:1.2},{f:'adult_sit_front.png',a:'idle-breathe',w:4.6},{f:'adult_sit_back.png',a:'idle-peek',w:2.4},{f:'adult_phone.png',a:'idle-breathe',w:6},{f:'adult_doze_sit.png',a:'idle-doze',w:3.8,fx:'…'},{f:'adult_lie_down.png',a:'idle-breathe',w:3.2},{f:'adult_troubled.png',a:'idle-doze',w:.6,fx:'…'},{f:'adult_cheer.png',a:'bounce',w:.7,fx:'!'},{f:'adult_shy.png',a:'squish',w:.45,fx:'♡'},{f:'adult_pout.png',a:'idle-doze',w:.55,fx:'…'},{f:'adult_sad.png',a:'idle-doze',w:.35,fx:'…'},{f:'adult_angry.png',a:'idle-shuffle',w:.18,fx:'!'}];if(this.minsSince('pat')>720&&this.minsSince('play')>600)a.push({f:'adult_cry.png',a:'idle-doze',w:.65,fx:'…'});if(p==='dere')a.push({f:'adult_shy.png',a:'squish',w:2.6,fx:'♡'},{f:'adult_cheer.png',a:'bounce',w:1.8,fx:'♡'});if(p==='aloof')a.push({f:'adult_back.png',a:'idle-breathe',w:3.5},{f:'adult_left.png',a:'idle-shuffle',w:2.5},{f:'adult_pout.png',a:'idle-doze',w:1.2,fx:'…'},{f:'adult_shy.png',a:'squish',w:.35,fx:'♡'});if(p==='tsundere')a.push({f:'adult_angry.png',a:'idle-shuffle',w:1.4,fx:'…'},{f:'adult_pout.png',a:'idle-doze',w:2},{f:'adult_back.png',a:'idle-breathe',w:2},{f:'adult_shy.png',a:'squish',w:.7,fx:'♡'});return a}
  recentCareSummary(){const labels={feed:['🍚','ごはん'],play:['🎮','あそぶ'],pat:['💗','愛でる'],bath:['🫧','おふろ'],toilet:['🚽','かたづける']},rows=(this.state.recent||[]).filter(x=>x&&x.type==='action'&&labels[x.action]).slice(-24),counts={};for(const x of rows)counts[x.action]=Number(counts[x.action]||0)+1;let top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];if(!top)top=Object.entries(this.state.actions||{}).filter(([k,v])=>labels[k]&&Number(v)>0).sort((a,b)=>Number(b[1])-Number(a[1]))[0];if(!top)return'まだ、これといってない。';const l=labels[top[0]];return`${l[0]} ${l[1]}　いちばん多い`}
  recentPhraseSummary(){const counts={};for(const x of (this.state.recent||[]).slice(-60)){const t=cleanText(x?.text||'');if(!t||t.length>36||BLOCK.test(t))continue;counts[t]=Number(counts[t]||0)+1}return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||cleanText(this.state.lastSpeech||'')}
  recentRareMoment(){for(const x of (this.state.recent||[]).slice().reverse()){const t=cleanText(x?.text||'');if(!t||!RX.rareLove.test(t))continue;const d=Number(x.at||0)?new Date(Number(x.at)):null;return{text:t,date:d&&!Number.isNaN(d.getTime())?`${d.getMonth()+1}/${d.getDate()}`:''}}return null}
  topFavorites(){return Object.entries(this.state.favoritePhrases||{}).sort((a,b)=>b[1]-a[1]).slice(0,5).map(x=>x[0])}
}

const ADULT_MAP={'adult_front.png':'adult_front','adult_right.png':'adult_right','adult_left.png':'adult_left','adult_back.png':'adult_back','adult_sit_front.png':'adult_sit_front','adult_sit_back.png':'adult_sit_back','adult_cheer.png':'adult_cheer','adult_angry.png':'adult_angry','adult_pout.png':'adult_pout','adult_sad.png':'adult_sad','adult_shy.png':'adult_shy','adult_cry.png':'adult_cry','adult_lie_down.png':'adult_lie_down','adult_sleep.png':'adult_sleep','adult_troubled.png':'adult_troubled','adult_eat.png':'adult_eat','adult_bath.png':'adult_bath','adult_toilet.png':'adult_toilet','adult_head_pat.png':'adult_head_pat','adult_phone.png':'adult_phone','adult_doze_sit.png':'adult_doze_sit','stand_front.png':'adult_front','stand_left.png':'adult_left','quarter_left.png':'adult_right','stand_back.png':'adult_back','sit_sad.png':'adult_sad','crawl_angry.png':'adult_angry','hold_heart.png':'adult_shy','eat_onigiri.png':'adult_eat','eat_fish.png':'adult_eat'};
const LEGACY={'adult_front.png':'stand_front.png','adult_right.png':'quarter_left.png','adult_left.png':'stand_left.png','adult_back.png':'stand_back.png','adult_sit_front.png':'sit_sad.png','adult_sit_back.png':'stand_back.png','adult_cheer.png':'adult_happy.png','adult_angry.png':'crawl_angry.png','adult_pout.png':'adult_cool.png','adult_sad.png':'sit_sad.png','adult_shy.png':'hold_heart.png','adult_cry.png':'sit_sad.png','adult_lie_down.png':'blanket_rest.png','adult_sleep.png':'blanket_rest.png','adult_troubled.png':'sit_sad.png','adult_eat.png':'eat_onigiri.png','adult_bath.png':'stand_front.png','adult_toilet.png':'stand_front.png','adult_head_pat.png':'hold_heart.png','adult_phone.png':'stand_front.png','adult_doze_sit.png':'sit_sad.png'};
export function petStageKey(model,file){const st=model.stageKey();if(st==='egg')return'egg_idle';if(st==='baby')return({'baby_idle.png':'baby_front','baby_front.png':'baby_front','baby_right.png':'baby_right','baby_left.png':'baby_left','baby_back.png':'baby_back','stand_front.png':'baby_front','stand_left.png':'baby_left','quarter_left.png':'baby_right','stand_back.png':'baby_back'})[file]||null;if(st==='child'){const m={'child_plain.png':'child_front','child_happy.png':'child_cheer','child_front.png':'child_front','child_right.png':'child_right','child_left.png':'child_left','child_back.png':'child_back','child_cheer.png':'child_cheer','stand_front.png':'child_front','stand_left.png':'child_left','quarter_left.png':'child_right','stand_back.png':'child_back','adult_cheer.png':'child_cheer'};if(m[file])return m[file];if(['adult_eat.png','eat_onigiri.png','eat_fish.png','adult_head_pat.png','hold_heart.png'].includes(file))return'child_cheer';return null}return ADULT_MAP[file]||null}
export function petUrl(model,file){const key=petStageKey(model,file),prefix=model.target==='も'?'mo/mocchi':'mi/michako';return key?CHAR_ASSET+prefix+'_'+key+'.png':COMMON_ASSET+(LEGACY[file]||file)}