const H2C='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';

export class ShareService{
  constructor(){this.cachedFile=null;this.renderPromise=null;this.refreshTimer=0;this.lastRenderAt=0;this.bound=false}
  async loadHtml2Canvas(){if(window.html2canvas)return window.html2canvas;return new Promise((resolve,reject)=>{const old=document.querySelector('script[data-html2canvas]');if(old){old.addEventListener('load',()=>window.html2canvas?resolve(window.html2canvas):reject(new Error('html2canvas missing')),{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=H2C;s.async=true;s.dataset.html2canvas='1';s.onload=()=>window.html2canvas?resolve(window.html2canvas):reject(new Error('html2canvas missing'));s.onerror=()=>reject(new Error('html2canvas load failed'));document.head.append(s)})}
  waitForImages(node){return Promise.all([...node.querySelectorAll('img')].map(img=>{if(img.complete&&img.naturalWidth)return Promise.resolve();return new Promise(resolve=>{const done=()=>resolve();img.addEventListener('load',done,{once:true});img.addEventListener('error',done,{once:true});setTimeout(done,2500)})}))}
  roundRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
  async makeBlob(){const source=document.querySelector('#g12 .g12main');if(!source)throw new Error('育成カードを見つけられなかった');const html2canvas=await this.loadHtml2Canvas();await this.waitForImages(source);if(document.fonts?.ready)await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const rect=source.getBoundingClientRect(),scale=Math.min(3.2,Math.max(2,1080/Math.max(320,rect.width))),card=await html2canvas(source,{backgroundColor:'#fff',scale,useCORS:true,allowTaint:false,logging:false,imageTimeout:5000,scrollX:-window.scrollX,scrollY:-window.scrollY}),pad=Math.max(34,Math.round(card.width*.06)),radius=Math.max(28,Math.round(card.width*.038)),shadow=Math.max(10,Math.round(card.width*.016)),border=Math.max(2,Math.round(card.width*.003)),out=document.createElement('canvas');out.width=card.width+pad*2+shadow;out.height=card.height+pad*2+shadow;const g=out.getContext('2d'),x=pad,y=pad;g.fillStyle='#f4f4f4';g.fillRect(0,0,out.width,out.height);g.save();g.shadowColor='rgba(0,0,0,.28)';g.shadowOffsetX=shadow;g.shadowOffsetY=shadow;g.shadowBlur=0;g.fillStyle='#fff';this.roundRect(g,x,y,card.width,card.height,radius);g.fill();g.restore();g.save();this.roundRect(g,x,y,card.width,card.height,radius);g.clip();g.drawImage(card,x,y);g.restore();g.save();g.strokeStyle='#111';g.lineWidth=border;this.roundRect(g,x+border/2,y+border/2,card.width-border,card.height-border,Math.max(2,radius-border/2));g.stroke();g.restore();return new Promise((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('画像を作れなかった')),'image/png'))}
  makeFile(blob){const v=localStorage.getItem('warera_chat_perspective')==='も'?'も':'み',t=v==='み'?'も':'み',d=new Date(),date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');return new File([blob],`warera-pet-${t}-${date}.png`,{type:'image/png'})}
  canShare(file){if(!navigator.share)return false;try{return !navigator.canShare||navigator.canShare({files:[file]})}catch{return false}}
  async refresh(force=false){if(this.renderPromise)return this.renderPromise;if(!force&&Date.now()-this.lastRenderAt<1200&&this.cachedFile)return this.cachedFile;this.renderPromise=(async()=>{this.cachedFile=this.makeFile(await this.makeBlob());this.lastRenderAt=Date.now();return this.cachedFile})().catch(e=>{console.warn('share cache refresh failed',e);return null}).finally(()=>{this.renderPromise=null});return this.renderPromise}
  schedule(delay=650){clearTimeout(this.refreshTimer);this.refreshTimer=setTimeout(()=>this.refresh(true),delay)}
  bind(){if(this.bound)return;this.bound=true;const boot=()=>{const root=document.querySelector('#g12 .g12main');if(!root){setTimeout(boot,300);return}this.schedule(200)};boot()}
  async openNative(){const file=this.cachedFile;if(!file){alert('共有画像を準備中。少し待ってもう一度押してね。');this.refresh(true);return}if(!this.canShare(file)){alert('このブラウザでは端末の共有画面を開けません。');return}try{await navigator.share({files:[file],title:'われわれ育成所'})}catch(err){if(err?.name!=='AbortError'){console.warn('native share failed',err);alert('共有画面を開けなかった。もう一度ためしてみて。')}}}
}
