import {cleanText,getViewer} from './core.js';

const BABY_BASES=new Set(['…','ん。','ふむ。','もぐ。','んま。','ごはん。','…！','きゃ。','ふふ。','んふ。','…♡','ぬくい。','ふろ。','ぷは。','ほかほか。','すっきり。','ねむ。','…ねる。','すや。','おきた。','…ん。','きた。']);
const norm=s=>String(s??'').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export class SourceLog{
  constructor(){this.rows=[];this.sceneMap=new Map();this.ready=false;this.current=null;}
  async load(){if(this.ready)return;try{const [mem,q]=await Promise.all([window.WareraData?.expandedMemories?.('../')?.catch?.(()=>[])||[],window.WareraData?.expandedQuiz?.('../')?.catch?.(()=>null)||null]);for(const s of Array.isArray(mem)?mem:[]){if(s?.id!=null)this.sceneMap.set(String(s.id),s);if(s?.base_id!=null&&!this.sceneMap.has(String(s.base_id)))this.sceneMap.set(String(s.base_id),s);for(const l of s?.lines||[]){const text=norm(l?.text);if(text&&['み','も'].includes(l?.who))this.rows.push({who:l.who,text,date:s.date||'',scene:s})}}for(const x of q?.who||[]){const text=norm(x?.quote);if(!text||!['み','も'].includes(x?.answer))continue;const scene=this.sceneMap.get(String(x.scene_id||''))||{date:x.date||'',lines:[{who:x.answer,text:x.quote}]};this.rows.push({who:x.answer,text,date:x.date||scene.date||'',scene})}for(const x of q?.next||[]){const scene=this.sceneMap.get(String(x.scene_id||''))||{date:x.date||'',lines:[x.prompt&&x.prompt_who?{who:x.prompt_who,text:x.prompt}:null,x.answer&&x.answer_who?{who:x.answer_who,text:x.answer}:null].filter(Boolean)};for(const [who,text] of [[x.prompt_who,x.prompt],[x.answer_who,x.answer]]){const t=norm(text);if(t&&['み','も'].includes(who))this.rows.push({who,text:t,date:x.date||scene.date||'',scene})}}}catch(e){console.warn('source log lookup unavailable',e)}this.ready=true}
  find(speech,stageLabel,target){const text=norm(speech);if(!text||stageLabel.includes('たまご')||(stageLabel.includes('あかちゃん')&&BABY_BASES.has(text)))return null;let best=null;for(const row of this.rows){if(row.who!==target)continue;const q=norm(row.text);if(q.length<2)continue;if((text===q||text.includes(q))&&(!best||q.length>best.text.length))best=row}return best}
  async sync({speech,stageLabel,target,button}){if(!button)return;await this.load();this.current=this.find(speech,stageLabel,target);if(!this.current){button.hidden=true;button.removeAttribute('data-source-log');button.textContent='';return}button.hidden=false;button.dataset.sourceLog='1';button.innerHTML='<b>元ログを見る</b>'}
  open(){if(!this.current?.scene)return;const modal=this.ensureModal(),scene=this.current.scene;modal.querySelector('#g12sourceDate').textContent=String(this.current.date||scene.date||'元ログ').replaceAll('-','/');modal.querySelector('#g12sourceLines').innerHTML=(scene.lines||[]).map(l=>`<div class="g12sourceLine"><span class="g12sourceWho">${esc(l.who||'')}</span><span class="g12sourceText">${esc(l.text||'')}</span></div>`).join('');modal.hidden=false}
  ensureModal(){let modal=document.getElementById('g12sourceModal');if(modal)return modal;modal=document.createElement('div');modal.id='g12sourceModal';modal.hidden=true;modal.innerHTML='<div class="g12sourceDlg"><div class="g12sourceHead"><b id="g12sourceDate"></b><button type="button" id="g12sourceClose">閉じる</button></div><div id="g12sourceLines"></div></div>';document.body.append(modal);modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});modal.querySelector('#g12sourceClose').onclick=()=>{modal.hidden=true};return modal}
}
