import {NAMES,petUrl,cleanText} from './core.js?v=20260926-life-3';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=s=>encodeURIComponent(String(s??''));
const dec=s=>decodeURIComponent(String(s??''));
const uniq=a=>[...new Set((a||[]).map(x=>cleanText(x)).filter(Boolean))];
const shuffled=a=>{const out=[...(a||[])];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const sample=(a,n)=>shuffled(uniq(a)).slice(0,n);

export class GrowView{
  constructor(model,sourceLog,life){this.model=model;this.sourceLog=sourceLog;this.life=life;this.heldPose='';this.heldUntil=0;this.idleFxTimer=0;this.activity=null;this.mount();this.bindSourceButton()}
  setModel(model,life){this.model=model;this.life=life;this.releasePose();this.activity=null}
  $(id){return document.getElementById(id)}
  mount(){
    document.getElementById('g12')?.remove();const root=document.createElement('div');root.id='g12';
    root.innerHTML=`<section class="g12shell"><div class="g12top"><div class="g12brand"><span class="egg">🥚</span><div><b>われわれ育成所</b><small>ログからできた、相手っぽい生き物。</small></div></div><div class="g12top-actions"><button class="g12mini" id="g12share">画像にする</button><button class="g12mini g12danger" id="g12farewell">お別れ</button></div></div><div class="g12body"><div class="g12grid"><section class="g12main"><div class="g12head"><div class="g12name" id="g12name"></div><div class="g12stage" id="g12stage"></div></div><div class="g12room" id="g12room"><div class="g12status" id="g12status"></div><div class="g12speech" id="g12speech"></div><div class="g12petbox" id="g12petbox"><img class="g12pet" id="g12pet" alt=""></div><div class="g12outing" id="g12outing" hidden><span>🚪</span><b>おでかけ中</b><small>どっか行った。</small><button type="button" data-recall>呼び戻す</button></div><span class="g12idlefx" id="g12idlefx"></span><span class="g12poop" id="g12poop" hidden>💩</span><div class="g12branch" id="g12branch" hidden></div><button class="g12memory" id="g12memory" hidden></button></div><div class="g12under"><button class="g12like" id="g12like">♡ とっておく</button><span class="g12hint">ひろいものから、この子につかえる。</span></div></section><aside class="g12side"><div class="g12sidehead"><h2>ひろいもの</h2><span id="g12findCount"></span></div><div class="g12finds" id="g12finds"></div></aside><section class="g12actions"><div id="g12actions"></div></section></div></div></section><div class="g12modal" id="g12modal" hidden><div class="g12dlg" id="g12dlg"></div></div>`;
    (document.querySelector('.conversation-shell')||document.querySelector('main')||document.body).append(root)
  }
  bindSourceButton(){this.$('g12memory').addEventListener('click',e=>{if(!e.currentTarget.dataset.sourceLog)return;e.preventDefault();e.stopPropagation();this.sourceLog.open()})}
  poseHeld(){if(!this.heldPose)return false;if(Date.now()>=this.heldUntil){this.releasePose();return false}return true}
  releasePose(){this.heldPose='';this.heldUntil=0}
  applyPose(file,anim=''){const img=this.$('g12pet');if(!img||!file)return;img.onerror=()=>{img.onerror=null};img.src=petUrl(this.model,file);if(anim){img.classList.remove('bounce','wiggle','squish','idle-breathe','idle-peek','idle-doze','idle-shuffle');void img.offsetWidth;img.classList.add(anim);if(!anim.startsWith('idle-'))setTimeout(()=>img.classList.remove(anim),700)}}
  showReaction(file,anim='',holdMs){if(!file||this.life.isOuting())return;const ms=holdMs??(this.model.stageKey()==='adult'?6000:1250);this.heldPose=file;this.heldUntil=Date.now()+ms;this.applyPose(file,anim)}
  applyLifeEvent(event){if(!event)return;if(event.speech!=null)this.$('g12speech').textContent=event.speech||'…';if(event.pose&&!this.life.isOuting()){this.releasePose();this.applyPose(event.pose,event.anim||'')}if(event.fx)this.showIdleFx(event.fx)}
  showIdleFx(text){const el=this.$('g12idlefx');if(!el||!text)return;el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');clearTimeout(this.idleFxTimer);this.idleFxTimer=setTimeout(()=>el.classList.remove('show'),1900)}
  async render({preservePet=false}={}){
    const m=this.model,s=m.state,st=m.stage(),d=new Date(),outing=this.life.isOuting();m.updatePoop();
    this.$('g12room').classList.toggle('night',d.getHours()<6||d.getHours()>=18);this.$('g12name').textContent=NAMES[m.target];this.$('g12stage').textContent=`${m.ageDays()}日目・${st[1]}`;this.$('g12status').textContent=this.life.statusText();
    this.$('g12speech').textContent=s.lastSpeech||'…';this.$('g12speech').hidden=outing;this.$('g12petbox').hidden=outing;this.$('g12outing').hidden=!outing;
    this.$('g12petbox').className=`g12petbox s-${st[0]}`;if(!outing&&!preservePet&&!this.poseHeld())this.applyPose(m.currentPet());
    const branch=this.life.growthLabel();this.$('g12branch').hidden=!branch||outing;this.$('g12branch').textContent=branch;this.$('g12poop').hidden=outing||!s.poop;this.$('g12actions').innerHTML=this.actionButtons();
    const canSave=this.life.canSaveCurrentSpeech(),saved=this.life.isCurrentSpeechSaved(),keep=this.$('g12like');keep.disabled=!canSave||saved;keep.classList.toggle('liked',saved);keep.textContent=saved?'♥ とってある':'♡ とっておく';
    this.renderFinds();await this.sourceLog.sync({speech:outing?'':s.lastSpeech||'',stageLabel:st[1],target:m.target,button:this.$('g12memory')})
  }
  actionButtons(){
    const m=this.model,s=m.state;if(m.stageKey()==='egg'){const egg={warm:['🫶','あたためる'],call:['📣','名前を呼ぶ'],tap:['👉','つんつん'],hum:['🎵','うたう'],listen:['👂','ようすを見る'],word:['🌀','われわれ語']};return`<div class="g12action-grid">${Object.entries(egg).slice(0,4).map(([k,v])=>`<button class="g12action" data-e="${k}"><i>${v[0]}</i><b>${v[1]}</b></button>`).join('')}</div><div class="g12context">${Object.entries(egg).slice(4).map(([k,v])=>`<button data-e="${k}">${v[0]} ${v[1]}</button>`).join('')}</div>`}
    if(this.life.isOuting())return`<div class="g12recall"><b>おでかけ中。</b><span>呼べばすぐ帰ってくる。</span><button type="button" data-recall>呼び戻す</button></div>`;
    const asleep=m.isAsleep(),actions=[['feed','🍚','ごはん','食べさせる'],['play','🎮','あそぶ','いっしょに遊ぶ'],['pat','💗','愛でる','とりあえず触る'],['bath','🫧','おふろ','カラダ・アラウ']];
    let html=`<div class="g12action-grid">${actions.map(([k,icon,label,sub])=>`<button class="g12action" ${k==='play'?'data-play-menu':'data-a="'+k+'"'} ${asleep?'disabled':''}><i>${icon}</i><b>${label}</b><small>${asleep?'ねてる':sub}</small></button>`).join('')}</div>`;const extra=[];if(s.poop)extra.push('<button data-a="toilet">🚽 かたづける</button>');if(m.canSleepNow()||asleep)extra.push(`<button data-a="sleep">${asleep?(m.canWakeNow()?'☀️ 起こす':'😴 ねてる'):'🌙 ねる'}</button>`);if(extra.length)html+=`<div class="g12context">${extra.join('')}</div>`;return html
  }
  renderFinds(){const rows=this.life.finds(),all=rows.length,count=this.$('g12findCount');count.textContent=all?`${all}こ`:'';const box=this.$('g12finds');if(!rows.length){box.innerHTML='<p class="g12empty">まだなんもない。</p>';return}box.innerHTML=rows.map(x=>`<button class="g12find" data-find="${esc(x.id)}"><span class="g12findicon">${esc(x.icon||'•')}</span><span><b>${esc(x.title)}</b><small>${esc(x.subtitle||'')}</small></span><i>›</i></button>`).join('')}
  openModal(html){const modal=this.$('g12modal'),dlg=this.$('g12dlg');dlg.innerHTML=html;modal.hidden=false}
  closeModal(){this.$('g12modal').hidden=true;this.activity=null}
  showPlayMenu(){this.activity={type:'menu'};this.openModal(`<div class="g12modalhead"><div><b>あそぶ</b><small>なにする？</small></div><button data-modal-close>×</button></div><div class="g12playmenu"><button data-play-mode="tease"><span>🎮</span><b>いつものちょっかい</b><small>とりあえず構う。</small></button><button data-play-mode="words"><span>💬</span><b>ことばをくっつける</b><small>左・まんなか・右を1つずつ。</small></button><button data-play-mode="quiz"><span>❓</span><b>続きあて</b><small>この次なんて返した？</small></button></div>`)}
  randomizeWordGame(game){
    const short=(this.model.corpus?.pools?.short||[]).map(x=>cleanText(x?.text||'')).filter(x=>x&&x.length<=18),tokens=this.model.corpus?.tokens||[],seed=cleanText(game?.seed||'');
    const frontPool=[...(game?.front||[]),...tokens,...short.filter(x=>x.length<=10)],endPool=[...(game?.end||[]),...short,...tokens];
    let front=sample(frontPool,7),middle=sample(game?.middle||[],7),end=sample(endPool,7);
    if(seed){if(!front.includes(seed))front=[seed,...front].slice(0,7);if(!end.includes(seed))end=[...end.slice(0,6),seed]}
    return{...game,front,middle,end}
  }
  showWordGame(game){const randomized=this.randomizeWordGame(game||{});this.activity={type:'word',game:randomized,selections:{front:'',middle:'',end:''}};this.renderWordGame()}
  renderWordGame(){const a=this.activity;if(!a||a.type!=='word')return;const section=(slot,label,rows)=>`<div class="g12wordslot"><b>${label}</b><div>${(rows||[]).map(v=>`<button class="${a.selections[slot]===v?'is-selected':''}" data-word-choice data-slot="${slot}" data-v="${enc(v)}">${esc(v)}</button>`).join('')}</div></div>`,preview=this.life.wordPhrase(a.selections);this.openModal(`<div class="g12modalhead"><div><b>ことばをくっつける</b><small>左・つなぎ・右</small></div><button data-modal-close>×</button></div><div class="g12wordgame">${section('front','左',a.game.front)}${section('middle','つなぎ',a.game.middle)}${section('end','右',a.game.end)}<div class="g12wordpreview">${preview?esc(preview):'3つ選ぶとここにできる。'}</div><button class="g12primary" data-word-finish ${a.selections.front&&a.selections.middle&&a.selections.end?'':'disabled'}>これでいく</button></div>`)}
  chooseWord(slot,value){if(!this.activity||this.activity.type!=='word')return;this.activity.selections[slot]=dec(value);this.renderWordGame()}
  wordSelection(){return this.activity?.type==='word'?{...this.activity.selections}:null}
  showWordResult(result){this.activity={type:'word-result',item:result?.item};this.openModal(`<div class="g12modalhead"><div><b>できた。</b><small>ひろいものに入った。</small></div><button data-modal-close>×</button></div><div class="g12bigphrase">${esc(result?.phrase||'')}</div><div class="g12modalactions"><button data-item-charm="${esc(result?.item?.id||'')}">この子につかう</button><button data-play-mode="words">もう1個つくる</button><button data-modal-close>あとで</button></div>`)}
  showQuiz(q){if(!q){this.openModal(`<div class="g12modalhead"><b>続きあて</b><button data-modal-close>×</button></div><p class="g12empty">問題が見つからなかった。</p>`);return}this.activity={type:'quiz',question:q};const mine=q.prompt_who==='み';this.openModal(`<div class="g12modalhead"><div><b>続きあて</b><small>この次なんて返した？</small></div><button data-modal-close>×</button></div><div class="g12quizprompt ${mine?'mine':'theirs'}"><span>${esc(q.prompt_who||'')}</span><p>${esc(q.prompt).replaceAll('\n','<br>')}</p></div><div class="g12quizchoices">${q.options.map((v,i)=>`<button data-quiz-choice="${i}">${esc(v).replaceAll('\n','<br>')}</button>`).join('')}</div>`)}
  currentQuiz(){return this.activity?.type==='quiz'?this.activity.question:null}
  showQuizResult(r){this.activity={type:'quiz-result'};this.openModal(`<div class="g12modalhead"><div><b>${r.ok?'○ 正解':'× ちがう'}</b><small>${esc(r.date||'')}</small></div><button data-modal-close>×</button></div><div class="g12quizanswer"><small>答え</small><b>${esc(r.answer||'')}</b></div><div class="g12modalactions"><button data-quiz-next>もう1問</button><button data-modal-close>おわる</button></div>`)}
  showFindItem(item,{gift=false}={}){if(!item)return;this.activity={type:'find',item};const text=item.payload?.text||item.payload?.word||'',action=item.type==='quiz'?`<button data-item-quiz="${esc(item.id)}">続きあてにつかう</button>`:['charm','crafted'].includes(item.type)?`<button data-item-charm="${esc(item.id)}">この子につかう</button>`:`<button data-item-word="${esc(item.id)}">ことば遊びにつかう</button>`;this.openModal(`<div class="g12modalhead"><div><b>${gift?'おかえり。':`${esc(item.icon||'•')} ${esc(item.title||'')}`}</b><small>${gift?'なんか持ってきた。':esc(item.subtitle||'')}</small></div><button data-modal-close>×</button></div>${gift?`<div class="g12gift"><span>${esc(item.icon||'🎁')}</span><b>${esc(item.title||'おみやげ')}</b><small>${esc(item.subtitle||'')}</small></div>`:text?`<div class="g12memoryquote">${esc(text)}</div>`:''}<div class="g12modalactions">${action}<button data-item-drop="${esc(item.id)}">手放す</button><button data-modal-close>あとで</button></div>`)}
  showCharmResult(r){this.activity={type:'charm-result'};this.openModal(`<div class="g12modalhead"><div><b>メロがれた。</b><small>つかったものは、ひろいものからなくなった。</small></div><button data-modal-close>×</button></div><div class="g12bigphrase">${esc(r?.item?.payload?.text||r?.item?.payload?.word||r?.item?.title||'')}</div><div class="g12modalactions"><button data-modal-close>おけ</button></div>`)}
  showGift(item){this.showFindItem(item,{gift:true})}
  showStageUp(change){const label=change?.to==='baby'?'あかちゃん':change?.to==='child'?'こども':change?.to==='adult'?'おとな':String(change?.to||'');this.activity={type:'stage'};this.openModal(`<div class="g12stageup"><b>${esc(label)}</b><span>になった。</span><button type="button" data-modal-close>おけ</button></div>`)}
}
