import {NAMES,petUrl,now,cleanText} from './core.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pick=(arr,seed)=>arr[Math.abs(seed)%arr.length];
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};

class Observation{
  constructor(model){this.model=model;this.tick=1;this.nextAt=0;this.lastSig='';this.current='';}
  setModel(model){this.model=model;this.force()}
  schedule(){this.nextAt=Date.now()+120000+Math.random()*120000}
  mins(ts){return ts?Math.max(0,(Date.now()-Number(ts))/60000):9999}
  signature(){const s=this.model.state,stage=this.model.stage()[1],last=s?.lastActionAt||{},recent=Object.entries(last).map(([k,v])=>[k,this.mins(v)]).sort((a,b)=>a[1]-b[1])[0]||['',9999];return[stage,!!s?.poop,Number(s?.manualSleepUntil||0)>Date.now(),recent[0],Math.floor(recent[1]/8),Math.floor(new Date().getHours()/3)].join('|')}
  text(){const m=this.model,s=m.state,stage=m.stage()[1],h=new Date().getHours(),seed=hash(`${this.tick}|${s?.totalCare||0}|${stage}`);if(stage==='たまご')return pick(['🥚 中でなんかやってる','🥚 たまにぴくっとする','🥚 しずか。たぶん元気','🥚 なんかコトコトしてる','🥚 さっきより気配ある'],seed);const last=s.lastActionAt||{},recent=Object.entries(last).map(([k,v])=>[k,this.mins(v)]).sort((a,b)=>a[1]-b[1])[0]||['',9999],a=recent[0],min=recent[1];if(s.poop)return pick(['💩 なんか出てる','💩 こっち見ながら待ってる','💩 しれっとしてる','💩 気づいてほしそう'],seed);if(Number(s.manualSleepUntil||0)>Date.now())return pick(['🌙 すやすや寝てる','🌙 かなり寝てる','🌙 起きる気配なし','🌙 しずかに寝てる','🌙 たまに寝返りしてる'],seed);if(min<8){const map={feed:['🍚 さっきのごはんを反芻してる','🍚 まだ口がもぐもぐしてる','🍚 食べたので満足げ','🍚 ちょっと機嫌よさそう'],play:['🎮 まだ遊ぶ気でいる','🎮 さっきの余韻が残ってる','🎮 ちょっとテンション高い','🎮 まだこっち見てる'],pat:['💗 さっき触られたの覚えてる','💗 ちょっと満足げ','💗 まだ構われる気でいる','💗 なんか距離が近い'],bath:['🫧 ちょっとさっぱりしてる','🫧 ほかほかしてる','🫧 いつもよりきれいな顔してる','🫧 風呂あがりの顔してる'],toilet:['🚽 すっきりした顔してる','🚽 何事もなかった顔してる'],sleep:['☀️ まだちょっと寝ぼけてる','☀️ 起きたけど動きが遅い']};if(map[a])return pick(map[a],seed)}const t=s.traits||{};if(h>=23||h<5)return pick(['🌙 だいぶ夜の顔してる','🌙 ちょっと動きがゆっくり','📱 夜なのにまだなんかしてる','… 静かだけど起きてる','🌙 そろそろ眠そう'],seed);if(h>=5&&h<9)return pick(['☀️ まだちょっとぼんやり','☀️ 朝の顔してる','… 起きてるけど静か','👀 こっち見てる','☀️ 今日はわりと早い'],seed);if(h>=12&&h<14)return pick(['🍚 ごはんの気配は察知してそう','☀️ 昼の顔してる','📱 なんか見てる','… ぼーっとしてる','👀 ときどきこっち見る'],seed);if(h>=18&&h<22)return pick(['🌆 だいぶ落ち着いてきた','📱 なんか触ってる','👀 こっち見たり見なかったり','… ひとりでしょもしょもしてる','✨ 今日はまだ元気そう'],seed);if((t.clingy||0)>(t.independent||0)*1.2)return pick(['👀 さっきからこっち見てる','💗 なんとなく近くにいる','👀 構われ待ちっぽい','… 離れる気はなさそう','💗 ちょっと寄ってきてる'],seed);if((t.independent||0)>(t.clingy||0)*1.2)return pick(['📱 ひとりでなんかしてる','… こっちは気にしてなさそう','☀️ 勝手に過ごしてる','📱 しばらく一人で平気そう','… マイペースにしてる'],seed);if((t.playful||0)>6)return pick(['🎮 なんか企んでそう','👀 ちょっかい待ちの顔してる','✨ ちょっと落ち着きない','🎮 まだ遊べそう','… なんかやりたそう'],seed);return pick(['👀 さっきからこっち見てる','✨ なんか機嫌いい','… ひとりでしょもしょもしてる','📱 なんか触ってる','☀️ ふつうに過ごしてる','… ぼーっとしてる','👀 たまにこっち見る','✨ 今日はわりと元気','… なんでもない顔してる','📱 ちょっと暇そう'],seed)}
  get(force=false){const sig=this.signature();if(!force&&this.current&&sig===this.lastSig&&Date.now()<this.nextAt)return this.current;this.lastSig=sig;const prev=this.current;let text='';for(let i=0;i<5;i++){this.tick++;text=this.text();if(text!==prev)break}this.current=text;this.schedule();return text}
  force(){this.nextAt=0;this.lastSig=''}
}

export class GrowView{
  constructor(model,sourceLog){this.model=model;this.sourceLog=sourceLog;this.observation=new Observation(model);this.heldPose='';this.heldUntil=0;this.lastIdlePose='';this.idleFxTimer=0;this.mount();this.bindSourceButton();}
  setModel(model){this.model=model;this.observation.setModel(model);this.releasePose();this.lastIdlePose='';}
  $(id){return document.getElementById(id)}
  mount(){document.getElementById('g12')?.remove();const root=document.createElement('div');root.id='g12';root.innerHTML=`<section class="g12shell"><div class="g12top"><div class="g12brand"><span class="egg">🥚</span><div><b>われわれ育成所</b><small>ログからできた、相手っぽい生き物。</small></div></div><div class="g12top-actions"><button class="g12mini" id="g12share">画像にする</button><button class="g12mini g12danger" id="g12farewell">お別れ</button></div></div><div class="g12body"><div class="g12grid"><section class="g12main"><div class="g12head"><div class="g12name" id="g12name"></div><div class="g12stage" id="g12stage"></div></div><div class="g12room" id="g12room"><div class="g12status" id="g12status"></div><div class="g12speech" id="g12speech"></div><div class="g12petbox" id="g12petbox"><img class="g12pet" id="g12pet" alt=""></div><span class="g12idlefx" id="g12idlefx"></span><span class="g12poop" id="g12poop" hidden>💩</span><div class="g12branch" id="g12branch" hidden></div><button class="g12memory" id="g12memory" hidden></button></div><div class="g12under"><button class="g12like" id="g12like">♡ この言い方すき</button><span class="g12hint">好きな言い方は、だんだん出やすくなる。</span></div></section><aside class="g12side"><h2>この子の中身</h2><div class="g12about" id="g12about"></div><div class="g12words" id="g12words"></div><div class="g12lognote" id="g12lognote"></div></aside><section class="g12actions"><div id="g12actions"></div></section></div></div></section><div class="g12modal" id="g12modal" hidden><div class="g12dlg" id="g12dlg"></div></div>`;(document.querySelector('.conversation-shell')||document.querySelector('main')||document.body).append(root)}
  bindSourceButton(){this.$('g12memory').addEventListener('click',e=>{if(!e.currentTarget.dataset.sourceLog)return;e.preventDefault();e.stopPropagation();this.sourceLog.open()})}
  poseHeld(){if(!this.heldPose)return false;if(Date.now()>=this.heldUntil){this.releasePose();return false}return true}
  releasePose(){this.heldPose='';this.heldUntil=0}
  applyPose(file,anim=''){const img=this.$('g12pet');if(!img)return;img.onerror=()=>{img.onerror=null};img.src=petUrl(this.model,file);if(anim){img.classList.remove('bounce','wiggle','squish','idle-breathe','idle-peek','idle-doze','idle-shuffle');void img.offsetWidth;img.classList.add(anim);if(!anim.startsWith('idle-'))setTimeout(()=>img.classList.remove(anim),700)}}
  showReaction(file,anim='',holdMs){if(!file)return;const ms=holdMs??(this.model.stageKey()==='adult'?6000:1250);this.heldPose=file;this.heldUntil=Date.now()+ms;this.applyPose(file,anim);setTimeout(()=>{if(this.poseHeld())return;this.applyPose(this.model.currentPet())},ms+20)}
  weightedIdlePick(){const options=this.model.idleOptions(),pool=[];for(const x of options)for(let i=0;i<Math.max(1,Math.round((x.w||1)*10));i++)pool.push(x);let choices=pool.filter(x=>x.f!==this.lastIdlePose);if(!choices.length)choices=pool;return choices[Math.floor(Math.random()*choices.length)]}
  showIdlePose(){if(this.poseHeld())return false;const o=this.weightedIdlePick();if(!o)return false;this.lastIdlePose=o.f;this.applyPose(o.f,o.a||'');if(o.fx)this.showIdleFx(o.fx);return true}
  showIdleFx(text){const el=this.$('g12idlefx');if(!el||!text)return;el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');clearTimeout(this.idleFxTimer);this.idleFxTimer=setTimeout(()=>el.classList.remove('show'),1900)}
  forceObservation(){this.observation.force()}
  async render({preservePet=false,forceObservation=false}={}){const m=this.model,s=m.state,st=m.stage(),d=new Date();m.updatePoop();this.$('g12room').classList.toggle('night',d.getHours()<6||d.getHours()>=18);this.$('g12name').textContent=NAMES[m.target];this.$('g12stage').textContent=`${m.ageDays()}日目・${st[1]}`;this.$('g12status').textContent=this.observation.get(forceObservation);this.$('g12speech').textContent=s.lastSpeech||'…';this.$('g12petbox').className=`g12petbox s-${st[0]}`;if(!preservePet&&!this.poseHeld())this.applyPose(m.currentPet());const branch=m.branchLabel();this.$('g12branch').hidden=!branch;this.$('g12branch').textContent=branch;this.$('g12poop').hidden=!s.poop;this.$('g12actions').innerHTML=this.actionButtons();const speechText=cleanText(s.lastSpeech||''),entryText=cleanText(m.currentSpeechEntry?.text||''),likeable=!!entryText&&speechText.includes(entryText),liked=!!(likeable&&s.favoritePhrases?.[entryText]);const like=this.$('g12like');like.disabled=!likeable;like.classList.toggle('liked',liked);like.setAttribute('aria-pressed',liked?'true':'false');like.textContent=liked?'♥ すきにした':'♡ この言い方すき';this.renderAbout();await this.sourceLog.sync({speech:s.lastSpeech||'',stageLabel:st[1],target:m.target,button:this.$('g12memory')})}
  actionButtons(){const m=this.model,s=m.state;if(m.stageKey()==='egg'){const egg={warm:['🫶','あたためる'],call:['📣','名前を呼ぶ'],tap:['👉','つんつん'],hum:['🎵','うたう'],listen:['👂','ようすを見る'],word:['🌀','われわれ語']};return`<div class="g12action-grid">${Object.entries(egg).slice(0,4).map(([k,v])=>`<button class="g12action" data-e="${k}"><i>${v[0]}</i><b>${v[1]}</b></button>`).join('')}</div><div class="g12context">${Object.entries(egg).slice(4).map(([k,v])=>`<button data-e="${k}">${v[0]} ${v[1]}</button>`).join('')}</div>`}const asleep=m.isAsleep(),actions={feed:['🍚','ごはん','食べさせる'],play:['🎮','あそぶ','ちょっかい出す'],pat:['💗','愛でる','とりあえず触る'],bath:['🫧','おふろ','カラダ・アラウ']};let html=`<div class="g12action-grid">${Object.entries(actions).map(([k,v])=>`<button class="g12action" data-a="${k}" ${asleep?'disabled':''}><i>${v[0]}</i><b>${v[1]}</b><small>${asleep?'ねてる':v[2]}</small></button>`).join('')}</div>`;const extra=[];if(s.poop)extra.push('<button data-a="toilet">🚽 かたづける</button>');if(m.canSleepNow()||asleep)extra.push(`<button data-a="sleep">${asleep?(m.canWakeNow()?'☀️ 起こす':'😴 ねてる'):'🌙 ねる'}</button>`);if(extra.length)html+=`<div class="g12context">${extra.join('')}</div>`;return html}
  renderAbout(){const m=this.model,stage=m.stageKey(),rows=[];if(stage==='egg'){rows.push(['まだわからない','中で育ってる']);}else{const care=m.recentCareSummary?.(),phrase=m.recentPhraseSummary?.(),learned=m.topFavorites?.()?.[0],memory=m.recentRareMoment?.();if(care)rows.push(['最近よくされてること',care]);if(phrase)rows.push(['最近よく言う',phrase]);if(learned)rows.push(['覚えてる言い方',learned]);if(memory?.text)rows.push(['この前のやつ',`${memory.text}${memory.date?`　${memory.date}`:''}`]);}this.$('g12about').innerHTML=rows.map(([k,v])=>`<p><b>${esc(k)}</b>${esc(v)}</p>`).join('');const tokens=m.corpus?.tokens||[];this.$('g12words').innerHTML=tokens.length?`<h3>よく出ることば</h3><div>${tokens.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:'';this.$('g12lognote').textContent=m.corpus?.count?`ログ由来の言い方 ${m.corpus.count}件から育成中。`:''}
  showStageUp(label){const modal=this.$('g12modal'),dlg=this.$('g12dlg');dlg.innerHTML=`<div class="g12stageup"><b>${esc(label)}</b><span>になった。</span><button type="button">おけ</button></div>`;modal.hidden=false;dlg.querySelector('button').onclick=()=>{modal.hidden=true}}
}
