(async()=>{
  wireLock('../');
  const [memories,core,analytics]=await Promise.all([WareraData.expandedMemories('../'),WareraData.core('../'),WareraData.expandedAnalytics('../')]);
  const messageCount=analytics?.counts?.text_messages??core.stats?.counts?.text_messages??0;
  document.getElementById('sourceCount').textContent=`${Number(messageCount).toLocaleString()}通から`;
  const readable=memories.filter(WareraData.readableScene),source=readable.length?readable:memories,grouped=new Map();
  memories.forEach(x=>{if(!grouped.has(x.date))grouped.set(x.date,[]);grouped.get(x.date).push(x)});
  const scene=document.getElementById('scene'),date=document.getElementById('date'),next=document.getElementById('next'),around=document.getElementById('around'),shareScene=document.getElementById('shareScene'),openDay=document.getElementById('openDay'),RK='warera_memory_recent';let current=null,aroundMode=false;
  const chatNode=WareraUI.chatScene;
  function dayPool(item){const all=grouped.get(item.date)||[],r=all.filter(WareraData.readableScene);return r.length?r:all}
  function dayHref(item){const id=item.base_id??item.id;return`../on-this-day/?date=${encodeURIComponent(item.date)}&scene=${encodeURIComponent(id)}&around=1`}
  function renderSingle(item){current=item;aroundMode=false;date.textContent=fmtDate(item.date);scene.replaceChildren(chatNode(item));around.textContent='前後を見る';openDay.href=dayHref(item)}
  function renderAround(item){current=item;aroundMode=true;date.textContent=fmtDate(item.date);scene.replaceChildren();const pool=dayPool(item),idx=pool.findIndex(x=>String(x.id)===String(item.id)),wrap=document.createElement('div');wrap.className='memory-around';if(idx<0){wrap.append(chatNode(item));scene.append(wrap);return}for(let i=Math.max(0,idx-1);i<=Math.min(pool.length-1,idx+1);i++){const block=document.createElement('section'),label=document.createElement('div');block.className='memory-block'+(i===idx?' is-current':'');label.className='memory-label';label.textContent=i===idx?'いまの場面':i<idx?'少し前':'少しあと';block.append(label,chatNode(pool[i]));wrap.append(block)}scene.append(wrap);around.textContent='1場面に戻す';openDay.href=dayHref(item)}
  function sharePayload(){if(!current||!aroundMode)return current;const pool=dayPool(current),idx=pool.findIndex(x=>String(x.id)===String(current.id));if(idx<0)return current;const lines=[];for(let i=Math.max(0,idx-1);i<=Math.min(pool.length-1,idx+1);i++)lines.push(...(pool[i].lines||[]));return{date:current.date,lines}}
  function ageDays(item){if(!item?.date)return 0;const d=new Date(item.date+'T12:00:00'),now=new Date();now.setHours(12,0,0,0);return Math.max(0,Math.floor((now-d)/86400000))}
  function nostalgicPick(pool){const groups=[{min:0,max:30,weight:10,rows:[]},{min:31,max:90,weight:20,rows:[]},{min:91,max:180,weight:25,rows:[]},{min:181,max:Infinity,weight:45,rows:[]}];for(const item of pool){const age=ageDays(item),g=groups.find(x=>age>=x.min&&age<=x.max);if(g)g.rows.push(item)}const available=groups.filter(x=>x.rows.length);if(!available.length)return pool[Math.floor(Math.random()*pool.length)];const total=available.reduce((s,x)=>s+x.weight,0);let r=Math.random()*total,chosenGroup=available.at(-1);for(const g of available){r-=g.weight;if(r<0){chosenGroup=g;break}}return chosenGroup.rows[Math.floor(Math.random()*chosenGroup.rows.length)]}
  async function pick(){next.disabled=true;try{let recent=WareraUI.readJSON(RK,[]);const recentSet=new Set(recent);let pool=source.filter(x=>!recentSet.has(String(x.id)));if(!pool.length){recent=[];pool=source}const chosen=nostalgicPick(pool);if(!chosen)return;recent.push(String(chosen.id));WareraUI.writeJSON(RK,recent.slice(-200));renderSingle(chosen)}finally{next.disabled=false}}
  around.onclick=()=>{if(current)(aroundMode?renderSingle(current):renderAround(current))};shareScene.onclick=async()=>{const payload=sharePayload();if(!payload)return;shareScene.disabled=true;try{await WareraShare.shareScene(payload)}finally{shareScene.disabled=false}};next.onclick=pick;pick();
})();
